/* ===== Proposta 1 · Gestão de Mudanças · adoção do AXON ===== */
window.DECK={brandSub:"ONS · AXON · Gestão de Mudanças",rightLabel:"Proposta · Adoção do AXON",footLabel:"AXON · DO LEGADO À ROTINA",
parts:[["Contexto","Contexto"],["Entendimento","1 · Entendimento","O que é o AXON e o que muda no trabalho","#33556D"],["Impactos","2 · Impactos","Impactos, públicos, adoção e riscos","#5E8AB4"],["Método","3 · Método","ADKAR, transição e as sete frentes","#1F3263"],["Plano de trabalho","4 · Plano de trabalho","Pessoas, legados, capacitação, marca e roadmap","#F78C16"]],
chapters:{"1 · Entendimento":["01","Entendimento","O que é o AXON e por que ele muda o trabalho de tanta gente."],"2 · Impactos":["02","Impactos","Quem é afetado, de que jeito, e o que pode dar errado se nada for feito."],"3 · Método":["03","Método","ADKAR e a transição das pessoas: a mudança acontece uma pessoa de cada vez."],"4 · Plano de trabalho":["04","Plano de trabalho","Seis meses para tirar o AXON do MVP e colocá-lo na rotina de cinco gerências."]},
zoom:["pipe","timeBars","heat","curve","riskMx","bridges","threads","ladder","decay","vitrine","funnel","gantt","rasci"],
descDefault:"Tela da proposta de gestão de mudanças para a adoção do AXON.",
desc:{"Capa":"Abertura da proposta: levar cinco gerências do ONS (PE, PR, PL, OS e PD) dos sistemas legados ao AXON em no mínimo seis meses. A animação mostra a ideia central: os legados perdem força aos poucos enquanto as gerências se conectam à plataforma, e o anel ADKAR se completa.",
"Resumo executivo":"A proposta em quatro atos: o que muda com o AXON, quem é impactado, como conduziremos a mudança (ADKAR + transição de pessoas) e o que entregamos em seis meses. Abaixo, os métodos de referência e o roteiro das quatro partes.",
"O AXON em uma tela":"Leitura da plataforma em seis etapas, do container ao resultado. Clique em cada etapa para ver o que ela faz, o que muda para as pessoas e quais perfis são tocados. À direita, os recursos que mais mudam a relação com o trabalho e a evidência de teste informada pelo time.",
"O que muda no trabalho":"Comparação entre o trabalho de hoje e o trabalho com o AXON em sete situações do dia a dia. Alterne a visão no seletor. O gráfico ilustra a hipótese central: o tempo sai da operação de sistemas e vai para estudo e análise. A distribuição real será medida no diagnóstico.",
"Mapa de impactos":"Estrutura do mapa de impactos: cinco gerências × sete dimensões próprias do AXON. As intensidades são ilustrativas. Clique numa dimensão para ver a pergunta-chave, o que vamos observar e o que ela gera no plano; abaixo, como levantamos e as hipóteses que o raio-x vai testar.",
"Públicos e adoção":"Cinco perfis de uso do AXON, cada um com o que perde, o que ganha, o receio provável e a resposta da mudança. Abaixo, a curva de difusão de inovações mostra como cada grupo entra na plataforma e onde está o salto crítico.",
"Riscos e mitigação":"Dez riscos iniciais posicionados por probabilidade e impacto. Clique numa bolha ou num item para ver o sinal observável, a resposta proposta, como saberemos que funcionou e o dono.",
"Método ADKAR":"O método: cada pessoa passa por Consciência, Desejo, Conhecimento, Habilidade e Reforço. Para cada estágio, as ações no contexto do AXON e a evidência de avanço. Abaixo, a transição de Bridges: o que acaba, a zona neutra de convivência e o novo começo.",
"Cinco movimentos":"O método em ação: cinco movimentos em sequência (entender, engajar, capacitar, migrar e sustentar), cada um com como fazemos, o que entregamos e o estágio ADKAR que move, costurados por dois fios condutores: as pessoas e a medição.",
"Transição das pessoas":"Como tratar a capacidade liberada pelo AXON: cada atividade ganha um destino, nascem papéis novos e a ordem de prioridade é requalificar e realocar antes de qualquer decisão de quadro.",
"Desnutrição dos legados":"Desnutrição gradual: o legado perde funções aos poucos, por onda, até ser desligado. Clique nos cinco portões para ver o critério de passagem e o que acontece com as pessoas em cada um.",
"Capacitação e manual amigável":"Trilhas por perfil, da exploração à construção de containers, mais uma trilha de liderança. Ao lado, o sumário proposto do manual amigável, escrito por tarefa e na linguagem de quem usa.",
"Marca e engajamento":"Como fazer o AXON ser desejado: uma vitrine com indicadores da plataforma (maquete ilustrativa), seis alavancas de engajamento e a mensagem certa para cada estágio ADKAR.",
"Funil de adoção":"A adoção medida como funil, do público da onda até quem indica o AXON a colegas: a maior queda aponta o estágio ADKAR que travou. À direita, quatro sinais antecipados para agir antes e quatro resultados que decidem o go da próxima onda, incluindo a recaída ao legado.",
"Roadmap de 6 meses":"Roadmap relativo de seis meses, sem datas: cinco fases, os cinco movimentos e os dois fios no tempo, os marcos de decisão e o checklist de go/no-go que toda onda precisa cumprir (técnica, pessoas e rotina).",
"Governança e papéis":"Matriz RASCI das principais decisões da mudança, com um único aprovador por decisão; os três fóruns (Conselho AXON, Mesa de adoção e Pulso da onda) e o caminho que uma barreira percorre até ser resolvida.",
"Canvas da proposta":"A proposta inteira em uma tela: por quê, o quê, como, quem, como saberemos e o que entregamos, mais as cinco fases e as premissas."}};

const PHASES=[["01","Raio-x","mês 1","Públicos, rotinas, legados e pulso de partida","#5E8AB4"],["02","Preparação","mês 2","Narrativa, trilhas, caminhos das pessoas e fila de ondas","#5E8AB4"],["03","Piloto","mês 3","Gerência piloto, rodada paralela e ajustes","#F78C16"],["04","Ondas","meses 4–5","Lançamentos por gerência e desnutrição dos legados","#1F3263"],["05","Autonomia","mês 6","Reforço, funil 30/60/90 e repasse ao ONS","#33556D"]];
const ADK={A:["#002B49","Consciência"],D:["#33556D","Desejo"],K:["#5E8AB4","Conhecimento"],H:["#F78C16","Habilidade"],R:["#1F3263","Reforço"]};
const adkChip=l=>`<span class="adk" title="${ADK[l][1]}" style="background:${ADK[l][0]};${l==="H"?"color:#0E1C39":""}">${l==="H"?"A":l}</span>`;

/* ---------- CAPA: rede neural · legados se apagam, gerências se ligam ao AXON ---------- */
(function(){const s=$("cvArt"),cx=380,cy=380;const df=S("defs",null,s);const rg=S("radialGradient",{id:"cvCore"},df);S("stop",{offset:0,"stop-color":"#33556D"},rg);S("stop",{offset:1,"stop-color":"#122143"},rg);
const G=["PE","PR","PL","OS","PD"],pt=(a,r)=>[cx+r*Math.cos(a),cy+r*Math.sin(a)];
S("circle",{cx,cy,r:300,fill:"none",stroke:"rgba(255,255,255,.06)","stroke-width":1},s);S("circle",{cx,cy,r:228,fill:"none",stroke:"rgba(255,255,255,.05)","stroke-width":1,"stroke-dasharray":"2 6"},s);
const legs=[],grey=[],flows=[];
G.forEach((g,i)=>{const a=-Math.PI/2+i*2*Math.PI/5,[x,y]=pt(a,300);
[-.2,.2].forEach((o,k)=>{const[lx,ly]=pt(a+o,222);const ln=S("line",{x1:x,y1:y,x2:lx,y2:ly,stroke:"rgba(255,255,255,.35)","stroke-width":1.4},s);grey.push(ln);const sq=S("rect",{x:lx-11,y:ly-11,width:22,height:22,rx:4,fill:"rgba(157,183,206,.35)",stroke:"rgba(255,255,255,.5)","stroke-width":1.2,style:"transition:opacity .4s"},s);legs.push(sq)});
const[fx,fy]=pt(a,166);const fl=S("line",{x1:x,y1:y,x2:fx,y2:fy,stroke:"#F78C16","stroke-width":2.6,class:"cv-flow",opacity:0},s);flows.push(fl)});
// anel ADKAR
const R=148,L=2*Math.PI*R,seg=L/5,gap=10,cols=["#9DBBD9","#5E8AB4","#BFD0E1","#F78C16","#F9A64A"],lets=["A","D","K","A","R"],arcs=[];
S("circle",{cx,cy,r:R,fill:"none",stroke:"rgba(255,255,255,.08)","stroke-width":16},s);
lets.forEach((l,i)=>{const c=S("circle",{cx,cy,r:R,fill:"none",stroke:cols[i],"stroke-width":16,"stroke-dasharray":`0 ${L}`,"stroke-dashoffset":-(i*seg),transform:`rotate(-90 ${cx} ${cy})`},s);arcs.push(c);const a=-Math.PI/2+(i+.5)*2*Math.PI/5,[x,y]=pt(a,R+30);T(s,x,y+6,l,{"text-anchor":"middle",fill:"#DDEAF5",style:"font:800 18px var(--fh)"})});
S("circle",{cx,cy,r:118,fill:"url(#cvCore)",stroke:"rgba(157,187,217,.5)","stroke-width":2},s);
T(s,cx,cy-30,"PLATAFORMA ÚNICA",{"text-anchor":"middle",fill:"#9DB7CE",style:"font:700 11px var(--fb);letter-spacing:.16em"});
T(s,cx,cy+22,"AXON",{"text-anchor":"middle",fill:"#fff",style:"font:800 58px var(--fh);letter-spacing:.1em"});
const pct=T(s,cx,cy+52,"adoção 0%",{"text-anchor":"middle",fill:"#F78C16",style:"font:700 14px var(--fb)"});
G.forEach((g,i)=>{const a=-Math.PI/2+i*2*Math.PI/5,[x,y]=pt(a,300);const gg=S("g",{class:"cv-node",style:`animation-delay:${i*.45}s`},s);S("circle",{cx:x,cy:y,r:36,fill:"#5E8AB4",stroke:"#9DBBD9","stroke-width":2},gg);T(gg,x,y+7,g,{"text-anchor":"middle",fill:"#fff",style:"font:800 21px var(--fh);letter-spacing:.04em"})});
const lg=S("g",null,s);S("rect",{x:206,y:716,width:16,height:16,rx:3,fill:"rgba(157,183,206,.35)",stroke:"rgba(255,255,255,.5)"},lg);T(lg,230,729,"legados · desnutrição gradual",{fill:"#9DB7CE",style:"font:600 12px var(--fb)"});S("line",{x1:420,y1:724,x2:452,y2:724,stroke:"#F78C16","stroke-width":2.6,"stroke-dasharray":"5 6"},lg);T(lg,460,729,"rotina no AXON",{fill:"#9DB7CE",style:"font:600 12px var(--fb)"});
let raf=0;ENTER["Capa"]=()=>{cancelAnimationFrame(raf);const t0=performance.now(),D=2600,dl=500;
const st=t=>{const k=clamp((t-t0-dl)/D,0,1),e=1-Math.pow(1-k,3);arcs.forEach((c,i)=>{const p=clamp(e*5-i,0,1);c.setAttribute("stroke-dasharray",`${Math.max(0,(seg-gap)*p)} ${L}`)});legs.forEach(q=>q.setAttribute("opacity",1-.82*e));grey.forEach(q=>q.setAttribute("opacity",1-.9*e));flows.forEach(f=>f.setAttribute("opacity",e));pct.textContent="adoção "+Math.round(e*100)+"%";if(k<1)raf=requestAnimationFrame(st);else pct.textContent="rotina das 5 gerências"};raf=requestAnimationFrame(st)}})();

/* ---------- RESUMO ---------- */
(function(){const A=[["search","#5E8AB4","Ato 1 · O que muda","1","plataforma no lugar de vários legados","O AXON orquestra rodadas de modelos eletroenergéticos em fluxos low code, com custo previsível na nuvem, e substitui sistemas e arquivos mantidos por muitas pessoas."],
["people","#F78C16","Ato 2 · Quem é impactado","5","gerências · 5 perfis de uso","PE, PR, PL, OS e PD. Quem constrói, prepara, executa, consulta ou lidera sente a mudança de um jeito: cada perfil terá o seu modelo de impacto."],
["refresh","#1F3263","Ato 3 · Como conduziremos","ADKAR","+ transição de pessoas","Consciência, desejo, conhecimento, habilidade e reforço por público, com a transição de Bridges para cuidar do que as pessoas deixam para trás."],
["flag","#33556D","Ato 4 · O que entregamos","6 meses","de jornada, em ondas","Adoção por ondas, legados desnutridos aos poucos, pessoas requalificadas e um painel que mostra a mudança acontecendo."]];
A.forEach(([ic,c,e,n,l,t],i)=>{const w=H("div",{"data-a":"stack",style:`--d:${3+i*1.1};--sx:${(1.5-i)*381}px;--r:${(i-1.5)*4}deg;position:relative;padding-top:30px`},$("acts"));const cc=H("div",{class:"card tlt",style:`border-radius:12px;border-top:4px solid ${c};padding:34px 16px 14px;height:100%;min-height:220px`},w);
const b=H("div",{style:`position:absolute;left:50%;top:0;transform:translateX(-50%);width:58px;height:58px;border-radius:50%;background:${c};display:grid;place-items:center;box-shadow:0 0 0 6px #fff,0 6px 16px rgba(14,28,57,.2);z-index:3`},w);b.innerHTML=icon(ic,"#fff",28);
H("div",{class:"eye",style:`color:${c==="#F78C16"?"#B35F00":c};margin-bottom:4px`},cc,e);H("div",{style:`font:800 44px/1 var(--fh);color:${c}`},cc,n);H("div",{class:"small",style:"font-weight:700;color:#35516A;margin:2px 0 8px"},cc,l);H("p",{style:"font-size:12.5px;line-height:1.5"},cc,t)});
[["people","Pessoas antes de sistemas","A plataforma só vale quando vira rotina de alguém."],["search","Evidência antes de opinião","Impactos, metas e ondas nascem do diagnóstico."],["layers","Ondas, não big bang","Piloto, rodada paralela e expansão por prontidão."],["chat","Ninguém descobre por boato","Quem é impactado sabe primeiro, pela liderança."]].forEach(([ic,t,d],i)=>{const x=H("div",{"data-a":"up",style:`--d:${10+i*.4};display:grid;grid-template-columns:38px 1fr;gap:10px;align-items:center;background:#EEF3F8;border-radius:10px;padding:9px 12px`},$("princ0"));H("span",{style:`width:38px;height:38px;border-radius:50%;background:${i%2?"#F78C16":"#122143"};display:grid;place-items:center`,html:icon(ic,"#fff",19)},x);const y=H("div",null,x);H("div",{style:"font:800 15px/1.1 var(--fh);color:#002B49"},y,t);H("div",{class:"small",style:"font-size:11px"},y,d)});
const M=[["ADKAR · Prosci","estágios da mudança individual e ponto de barreira","#002B49"],["Transição · Bridges","fim, zona neutra e novo começo para as pessoas","#33556D"],["Difusão · Rogers","curva de adoção e o salto para a maioria","#5E8AB4"],["Mapa de impactos","gerência × 7 dimensões, com evidência","#F78C16"],["Checklist de go/no-go","técnica, pessoas e rotina antes de cada onda","#1F3263"],["Funil de adoção","onde as pessoas param, e por quê","#33556D"]];
M.forEach(([t,d,c],i)=>{const x=H("div",{"data-a":"up",style:`--d:${8+i*.5};background:#fff;border:1px solid var(--line);border-left:4px solid ${c};border-radius:8px;padding:8px 10px`},$("methods"));H("div",{style:"font:800 14px var(--fh);color:#002B49"},x,t);H("div",{class:"small",style:"font-size:10.5px"},x,d)})})();

/* ---------- O AXON EM UMA TELA ---------- */
(function(){const P=[["box","Container","código, configuração e contrato","O modelo (Python ou outra linguagem) é empacotado com um arquivo que documenta os jobs disponíveis, as entradas que espera e as saídas que entrega. Build, logs e segurança são monitorados e cada execução é versionada.","O “como roda” deixa de morar na cabeça de quem mantém o legado e passa a estar documentado. Documentar bem vira competência crítica.",["Construtores"]],
["grid","Catálogo de jobs","caixinhas geradas pela documentação","A documentação do container gera, automaticamente, os blocos do catálogo. O contrato de entrada e saída garante que só roda o que bate com o código.","Quem prepara estudos passa a escolher blocos prontos em vez de pedir ajustes a quem desenvolveu.",["Construtores","Preparadores"]],
["flow","Pipeline","arrastar, conectar e orquestrar","Fluxos montados por clique e arraste, como num quadro branco. A plataforma orquestra a sequência pelas entradas e saídas de cada job, para qualquer domínio.","A lógica da rodada fica visível para todos; o conhecimento sai das planilhas e scripts pessoais.",["Preparadores"]],
["sliders","Estudo","interface de parâmetros sob medida","Em vez de vários arquivos de definição, cada estudo ganha uma interface gerada pelos parâmetros: faixa, número, seleção, multisseleção, data, texto e tabela. Fica salva, pode ser duplicada e ajustada; parâmetro novo não exige pedir desenvolvimento.","Quem executa só precisa preencher; quem prepara monta a interface uma vez para todos.",["Preparadores","Executores"]],
["cloud","Execução","nuvem com custo previsível","Escolha de máquina e de escala, milhares de casos em paralelo, custo previsto por rodada e consumo contra o orçamento mensal e anual do time.","Autonomia com responsabilidade: cada time passa a gerir o próprio orçamento de rodadas.",["Executores","Gestores"]],
["out","Resultado","saída para onde o trabalho continua","Saídas para o catálogo de dados corporativo, download direto ou Axon Drive, que espelha no notebook os arquivos dos projetos em que a pessoa tem permissão.","Quem consome resultados precisa saber onde encontrar o que antes estava no legado.",["Consumidores","Executores"]]];
const det=$("pipeDet");function sel(i){[...$("pipe").children].forEach((b,k)=>b.classList.toggle("sel",k===i));const[ic,t,s,d,p,who]=P[i];
det.innerHTML=`<div style="display:flex;align-items:center;gap:12px"><span style="width:46px;height:46px;border-radius:50%;background:#F78C16;display:grid;place-items:center">${icon(ic,"#fff",24)}</span><div><div class="eye" style="margin:0;color:#B35F00">Etapa ${i+1} de 6</div><div style="font:800 24px/1.05 var(--fh);color:#002B49">${t} · <span style="color:#5E8AB4">${s}</span></div></div></div>
<p style="font-size:13.5px;line-height:1.5;margin-top:10px;color:#35516A">${d}</p>
<div style="margin-top:10px;background:#FEF1E2;border-radius:8px;padding:9px 12px;border-left:4px solid #F78C16"><div style="font:800 10.5px var(--fb);letter-spacing:.12em;color:#B35F00;text-transform:uppercase">O que muda para as pessoas</div><div style="font:600 13px/1.45 var(--fb);color:#002B49;margin-top:2px">${p}</div></div>
<div style="display:flex;gap:6px;align-items:center;margin-top:10px"><span class="small" style="font-weight:700">Perfis tocados:</span>${who.map(w=>`<span class="pill">${w}</span>`).join("")}</div>`}
P.forEach(([ic,t,s],i)=>{const b=H("button",{class:"pp-step","data-a":"up",style:`--d:${3+i*.6}`},$("pipe"));b.innerHTML=`<span class="n">0${i+1}</span><div class="ic">${icon(ic,"#fff",22)}</div><b>${t}</b><span>${s}</span>`;b.addEventListener("click",()=>sel(i))});sel(0);
const F=[["ai","Conexão MCP","A IA monta a configuração de parâmetros e estudos a partir de uma conversa."],["bug","Reportar bug","Tela, versão e sessão capturadas; correções simples saem assistidas por IA, com aprovação humana."],["inbox","Caixa de entrada","Dados de agentes entram, são processados e o retorno sai pelo mesmo canal, em loop."],["drive","Axon Drive","Arquivos dos projetos permitidos montados como um drive no notebook."]];
F.forEach(([ic,t,d],i)=>{const x=H("div",{class:"card","data-a":"up",style:`--d:${10+i*.4};border-radius:10px;padding:9px 12px;display:grid;grid-template-columns:34px 1fr;gap:10px;align-items:start`},$("feat"));H("span",{style:"width:34px;height:34px;border-radius:9px;background:#122143;display:grid;place-items:center",html:icon(ic,"#fff",18)},x);const y=H("div",null,x);H("h4",{style:"margin:0"},y,t);H("p",{style:"font-size:11.5px;line-height:1.35"},y,d)})})();

/* ---------- O QUE MUDA ---------- */
(function(){const R=[["sliders","Configurar um estudo","Vários <b>arquivos de definição</b> por tipo de estudo, editados à mão.","<b>Interface de parâmetros</b> por estudo, salva e duplicável; parâmetro novo sem pedir desenvolvimento."],
["cpu","Rodar um modelo","Servidores e filas locais; lotes grandes levam <b>dias</b>.","Nuvem escalável: milhares de casos em paralelo, em <b>horas</b>."],
["coin","Custo da rodada","Pouco visível e <b>difícil de prever</b>.","<b>Custo previsto</b> por rodada e orçamento mensal e anual por time."],
["layers","Sistemas","Vários <b>legados e satélites</b>, cada um com interface e mantenedores próprios.","<b>Uma plataforma</b> para qualquer modelo empacotado em container."],
["inbox","Validar com agentes","Ligações e e-mails; <b>validação manual</b>, caso a caso.","<b>Caixa de entrada</b>: processamento e retorno automáticos, no mesmo canal."],
["search","Encontrar resultados","Arquivos <b>espalhados</b> em pastas e máquinas.","<b>Catálogo corporativo</b>, download ou Axon Drive."],
["bug","Pedir suporte","Chamado genérico, <b>sem contexto</b>.","Bug com <b>tela, versão e sessão</b>; correções simples assistidas."]];
const c=$("cmp");R.forEach(([ic,k,o,n])=>{H("div",{class:"k",html:`${icon(ic,"#5E8AB4",18)}<span>${k}</span>`},c);H("div",{class:"v",html:`<span class="o">${o}</span><span class="n">${n}</span>`},c)});
const seg=$("cmpSeg");const set=v=>{seg.querySelectorAll("button").forEach(b=>b.classList.toggle("on",b.dataset.v===String(v)));c.classList.toggle("fut",v===1);bars(v)};seg.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{clearTimeout(auto);set(+b.dataset.v)}));
const s=$("timeBars"),D=[[55,25,20],[20,30,50]],C=["#5E8AB4","#9DBBD9","#F78C16"],L=["Operar sistemas e arquivos","Preparar estudos","Analisar e decidir"],X0=10,W=380;const rows=[];
["Hoje","Com o AXON"].forEach((n,r)=>{const y=18+r*84;T(s,X0,y,n,{fill:r?"#F9A64A":"#DDEAF5",style:"font:800 14px var(--fh);letter-spacing:.04em;text-transform:uppercase"});const g=[];let x=X0;D[r].forEach((v,k)=>{const w=W*v/100,rc=S("rect",{x,y:y+8,width:w-2,height:40,rx:5,fill:C[k],opacity:r||k!==2?1:.85},s);const tt=T(s,x+w/2,y+33,v+"%",{"text-anchor":"middle",fill:k===1?"#0E1C39":"#fff",style:"font:800 15px var(--fh)"});tip(rc,`${n} · ${L[k]}`,`${v}% do tempo · ilustrativo`);g.push([rc,tt]);x+=w});rows.push(g)});
L.forEach((l,k)=>{const y=188+k*20;S("rect",{x:X0,y:y-10,width:12,height:12,rx:3,fill:C[k]},s);T(s,X0+20,y,l,{fill:"#C8DBEB",style:"font:600 12px var(--fb)"})});
const ar=T(s,390,233,"",{"text-anchor":"end",fill:"#F9A64A",style:"font:800 13px var(--fb)"});
function bars(v){rows[1].forEach(([rc,tt])=>{rc.style.transition="opacity .4s";rc.style.opacity=v?1:.25;tt.style.opacity=v?1:.25});ar.textContent=v?"+30 p.p. em análise":""}
let auto=0;ENTER["O que muda no trabalho"]=()=>{set(0);clearTimeout(auto);auto=setTimeout(()=>set(1),2600)};set(0)})();

/* ---------- MAPA DE IMPACTOS ---------- */
(function(){const G=["PE","PR","PL","OS","PD"],Dm=[["Rotinas de rodada","Quais rodadas mudam de dono, de passo a passo ou de frequência?","Rodadas observadas ao vivo: quem dispara, quanto tempo leva, onde trava.","Mapa das rotinas que migram, mudam ou deixam de existir.","A"],
["Legados e satélites","Que sistemas, planilhas e scripts pessoais deixam de ser necessários?","Lista de legados com mantenedores, usuários e o que só eles sabem.","Fila de desnutrição: o que sai primeiro e quem é o guardião.","H"],
["Papéis e alçadas","Quem passa a montar, rodar, aprovar e pagar cada estudo?","Quem hoje decide, quem executa e quem só recebe o resultado.","Papéis novos e quem aprova o quê dentro do AXON.","K"],
["Competências","O que cada perfil precisa saber fazer sozinho no AXON?","Autoavaliação curta e uma tarefa prática por perfil.","Lacunas que definem trilhas e multiplicadores.","K"],
["Capacidade liberada","Quanto tempo volta para a equipe, e para onde ele vai?","Horas por rotina hoje, picos de demanda e estudos parados na fila.","Destinos da capacidade: requalificar, realocar e papéis novos.","D"],
["Interface com agentes","Quem fora do ONS percebe a mudança de canal ou de prazo?","Fluxos de validação com agentes e com outras áreas.","Comunicação externa e transição para a Caixa de entrada.","A"],
["Confiança no resultado","As pessoas acreditam no número que sai do AXON?","Rodada paralela, divergências conhecidas e pulso de confiança.","Critério de paridade por modelo e ações de reforço.","D"]];
const V=[[3,3,2,3,2,1,2],[2,3,2,2,2,1,2],[3,2,2,3,3,1,0],[2,2,3,2,2,2,3],[3,3,2,2,3,3,0]],LB={3:"Alto",2:"Médio",1:"Baixo",0:"?"},CL={3:"l3",2:"l2",1:"l1",0:"lx"};
const t=$("heat"),hr=H("tr",null,t);H("th",null,hr,"");Dm.forEach((d,j)=>{const th=H("th",{class:"ch"},hr,d[0]);th.addEventListener("click",()=>sel(j,true))});
G.forEach((g,i)=>{const tr=H("tr",null,t);H("th",{class:"rh"},tr,g);V[i].forEach((v,j)=>{const td=H("td",{class:CL[v]},tr,LB[v]);td.dataset.j=j;tip(td,`${g} · ${Dm[j][0]}`,v?`intensidade ${LB[v].toLowerCase()} · ilustrativa`:"a investigar no diagnóstico");td.addEventListener("click",()=>sel(j,true))})});
function sel(j,dim){t.querySelectorAll("th.ch").forEach((h,k)=>h.classList.toggle("sel",k===j));t.classList.toggle("dim",!!dim);t.querySelectorAll("td").forEach(td=>td.classList.toggle("on",+td.dataset.j===j));const[n,q,e,o,a]=Dm[j];
$("heatDet").innerHTML=`<div class="eye" style="color:#B35F00">Dimensão ${j+1} de 7</div><div style="font:800 27px/1.05 var(--fh);color:#002B49">${n}</div>
<div style="margin-top:12px;font:800 10.5px var(--fb);letter-spacing:.12em;color:#5E8AB4;text-transform:uppercase">Pergunta-chave</div><div style="font:700 15px/1.35 var(--fb);color:#002B49;margin-top:2px">${q}</div>
<div style="margin-top:12px;font:800 10.5px var(--fb);letter-spacing:.12em;color:#5E8AB4;text-transform:uppercase">O que vamos observar</div><div style="font:500 13px/1.45 var(--fb);color:#35516A;margin-top:2px">${e}</div>
<div style="margin-top:12px;background:#EEF3F8;border-radius:8px;padding:9px 12px"><div style="font:800 10.5px var(--fb);letter-spacing:.12em;color:#33556D;text-transform:uppercase">Saída para o plano</div><div style="font:700 13.5px/1.4 var(--fb);color:#002B49;margin-top:2px">${o}</div></div>
<div style="display:flex;align-items:center;gap:8px;margin-top:12px"><span class="small" style="font-weight:700">Estágio ADKAR mais sensível:</span>${adkChip(a)}<span class="small">${ADK[a][1]}</span></div>
<div class="small" style="margin-top:12px;border-top:1px solid var(--line2);padding-top:8px">Levantado no raio-x do mês 1 e revisto antes de cada onda.</div>`}
[["chat","Conversas","gerentes, mantenedores e times do MVP"],["eye","Rodadas observadas","ao lado de quem roda hoje"],["people","Oficinas por gerência","rotina a rotina, com quem faz"],["pulse","Pulso de partida","confiança e prontidão por perfil"]].forEach(([ic,t,d],i)=>{const x=H("div",{"data-a":"up",style:`--d:${8+i*.3};display:grid;grid-template-columns:30px 1fr;gap:8px;align-items:center;background:#fff;border:1px solid var(--line);border-radius:8px;padding:7px 10px`},$("hmHow"));H("span",{style:"width:30px;height:30px;border-radius:8px;background:#122143;display:grid;place-items:center",html:icon(ic,"#fff",16)},x);const y=H("div",null,x);H("div",{style:"font:800 13.5px/1.1 var(--fh);color:#002B49"},y,t);H("div",{class:"small",style:"font-size:10.5px"},y,d)});
[["H1","Quem mais dispara rodadas no legado é quem mais sente a mudança."],["H2","Gerências que validam dados com agentes mudam também o canal externo."],["H3","A velocidade da adoção depende mais da confiança no resultado do que do treinamento."]].forEach(([k,t],i)=>{const x=H("div",{"data-a":"up",style:`--d:${11+i*.3};display:grid;grid-template-columns:34px 1fr;gap:8px;align-items:center;background:#FEF6EC;border:1px dashed #F5B570;border-radius:8px;padding:8px 10px`},$("hyp"));H("span",{style:"display:grid;place-items:center;width:32px;height:32px;border-radius:50%;background:#F78C16;color:#0E1C39;font:800 12px var(--fb)"},x,k);H("span",{style:"font:600 12px/1.35 var(--fb);color:#002B49"},x,t)});
sel(0,false);ENTER["Mapa de impactos"]=()=>sel(0,false)})();

/* ---------- PÚBLICOS ---------- */
(function(){const P=[["code","#002B49","Construtores","desenvolvem e mantêm modelos",4,"O controle artesanal do “seu” sistema e servidor.","Versionamento, build e escala sem infraestrutura própria.","“Vou ter que reescrever tudo?”","Padrão de container e mentoria técnica."],
["flow","#33556D","Preparadores","montam pipelines e estudos",4,"Arquivos de definição e ajustes manuais.","Interface de parâmetros por estudo; duplicar e ajustar.","“E se o resultado não bater com o legado?”","Rodada paralela e trilha de preparação."],
["bolt","#F78C16","Executores","rodam estudos prontos",5,"Parte da operação diária que hoje ocupa a agenda.","Tempo para análise e para estudos que hoje não cabem.","“O meu trabalho vai acabar?”","Plano de transição individual e requalificação."],
["eye","#5E8AB4","Consumidores","usam resultados para decidir",2,"O caminho conhecido até o arquivo de sempre.","Resultado no catálogo e no Axon Drive.","“Onde encontro o que eu usava?”","Guia de bolso e de-para do legado."],
["coin","#1F3263","Gestores","lideram times e orçamento",3,"O desenho atual de equipe e de rotina.","Custo por rodada e orçamento visíveis.","“Como redistribuo o meu time?”","Kit do líder e decisões com RH."]];
P.forEach(([ic,c,n,r,lv,lo,ga,wo,re],i)=>{const x=H("div",{class:"pers tlt","data-a":"up",style:`--d:${3+i*.5};border-top:5px solid ${c};--ic:${c}`},$("pers"));
x.innerHTML=`<div class="top"><span class="av" style="background:${c}">${icon(ic,"#fff",24)}</span><div><h4>${n}</h4><div class="ro">${r}</div></div><div class="int" title="intensidade do impacto ${lv}/5">${[1,2,3,4,5].map(k=>`<i class="${k<=lv?"on":""}"></i>`).join("")}</div></div>
<div class="row"><b class="l">Perde</b><span>${lo}</span></div><div class="row"><b class="g">Ganha</b><span>${ga}</span></div><div class="row"><b class="w">Receio</b><span><i>${wo}</i></span></div><div class="row"><b style="color:#002B49">Resposta</b><span style="font-weight:700;color:#002B49">${re}</span></div>`});
const s=$("curve"),z0=-3,z1=3,X=z=>30+(z-z0)/(z1-z0)*1000,Y=z=>118-102*Math.exp(-z*z/2);
const SG=[[-3,-2,"#F78C16","Inovadores · 2,5%","times do MVP"],[-2,-1,"#F9A64A","Primeiros adeptos · 13,5%","multiplicadores por gerência"],[-1,0,"#5E8AB4","Maioria inicial · 34%","piloto e onda 1"],[0,1,"#33556D","Maioria tardia · 34%","onda 2, com rodada paralela"],[1,3,"#1F3263","Retardatários · 16%","escuta e apoio individual"]];
SG.forEach(([a,b,c,n,d],i)=>{let p=`M${X(a)} 118`;for(let z=a;z<=b+1e-9;z+=.05)p+=` L${X(z).toFixed(1)} ${Y(z).toFixed(1)}`;p+=` L${X(b)} 118 Z`;const g=S("g",{"data-a":"fade",style:`--d:${10+i*.5}`},s);const pa=path(p,{fill:c,opacity:.9,stroke:"#fff","stroke-width":2},g);tip(pa,n,d);
const cx=X(Math.max(a,-2.75)+((Math.min(b,2.6))-Math.max(a,-2.75))/2);T(g,cx,140,n,{"text-anchor":"middle",fill:"#002B49",style:"font:800 12.5px var(--fb)"});T(g,cx,158,d,{"text-anchor":"middle",fill:"#6B7B8C",style:"font:600 11.5px var(--fb)"})});
S("line",{x1:X(-1),y1:8,x2:X(-1),y2:122,stroke:"#BC0404","stroke-width":2,"stroke-dasharray":"5 5"},s);const cg=S("g",null,s);S("rect",{x:X(-1)-46,y:2,width:92,height:20,rx:10,fill:"#BC0404"},cg);T(cg,X(-1),16,"o salto",{"text-anchor":"middle",fill:"#fff",style:"font:800 11px var(--fb);letter-spacing:.08em;text-transform:uppercase"});tip(cg,"O salto crítico","Dos entusiastas para a maioria: exige prova social, confiança no resultado e suporte próximo");
S("line",{x1:30,y1:118,x2:1030,y2:118,stroke:"#B6C0CD"},s)})();

/* ---------- RISCOS ---------- */
(function(){const R=[["Medo de perder o trabalho","Pessoas",4,5,"Perguntas sobre cortes nos corredores; pessoas evitando o piloto.","Conversa do líder antes de qualquer anúncio; cada impactado sai com um caminho combinado (trilha ou papel novo).","Impactados com caminho combinado ÷ impactados.","Patrocinador + RH","D"],
["Perda de conhecimento dos legados","Conhecimento",4,5,"Exceções e “macetes” que só o mantenedor conhece.","O mantenedor vira guardião do legado: registra os casos especiais e valida a paridade.","Casos especiais registrados por legado.","Gerências + produto","K"],
["Resultado do AXON diferente do legado","Confiança",3,5,"Gente rodando nos dois sistemas “por garantia” depois do go.","Tolerância de paridade definida por modelo antes da onda, com aceite do dono do modelo.","Modelos com paridade aceita; recaída ao legado.","Dono do produto","H"],
["Convivência dupla sobrecarrega as equipes","Capacidade",4,4,"Horas extras e entregas com prazo ficando apertadas.","Rodada paralela com começo e fim marcados e ondas fora dos picos do calendário.","Horas extras e incidentes durante a convivência.","Gerências","H"],
["Disputa de governança com a TI","Governança",3,4,"Exigências técnicas que aparecem na véspera do go.","TI com assento no Conselho AXON e requisitos de segurança acordados antes do piloto.","Exigências tardias por onda.","Patrocinador","A"],
["Produto dependente de uma pessoa","Produto",4,4,"Dúvidas e pedidos indo sempre para o mesmo nome.","Multiplicadores como primeira linha, triagem assistida de bugs e documentação viva.","Pedidos resolvidos sem o dono do produto.","Patrocinador + produto","R"],
["Demanda de melhorias maior que a capacidade","Produto",4,3,"Pedidos sem resposta e frustração depois de cada onda.","Escuta organizada, critério público de prioridade e retorno a quem pediu.","Inquietações respondidas no ciclo.","Dono do produto","R"],
["Gasto de nuvem fora do orçamento","Custo",2,4,"Rodadas grandes disparadas sem olhar a previsão de custo.","Orçamento visível por time e trilha de liderança sobre custo de rodada.","Desvio entre custo previsto e realizado.","Gestores","K"],
["Baixa autonomia dos usuários básicos","Usabilidade",3,3,"A mesma dúvida chegando várias vezes.","Modo executar simples, guia de bolso e assistente via MCP para configurar.","Dias até a primeira rodada sozinho.","GMO + produto","K"],
["Mudança de canal com agentes externos","Externo",2,3,"Agentes respondendo pelo canal antigo.","Aviso prévio aos agentes e um período em que os dois canais valem.","Retornos recebidos pela Caixa de entrada.","Gerência da interface","A"]];
const sv=x=>x>=16?"#BC0404":x>=10?"#F78C16":"#5E8AB4";const s=$("riskMx"),x0=70,y0=14,W=470,Hh=470,cw=W/5,X=p=>x0+(p-.5)*cw,Y=i=>y0+Hh-(i-.5)*cw;
for(let p=1;p<=5;p++)for(let i=1;i<=5;i++){const v=p*i;S("rect",{x:x0+(p-1)*cw+1,y:y0+Hh-i*cw+1,width:cw-2,height:cw-2,rx:4,fill:v>=16?"rgba(188,4,4,.10)":v>=10?"rgba(247,140,22,.10)":"#F2F5F8"},s)}
for(let k=1;k<=5;k++){T(s,X(k),y0+Hh+20,k,{"text-anchor":"middle",fill:"#6B7B8C",style:"font:700 12px var(--fb)"});T(s,x0-14,Y(k)+4,k,{"text-anchor":"middle",fill:"#6B7B8C",style:"font:700 12px var(--fb)"})}
T(s,x0+W/2,y0+Hh+44,"PROBABILIDADE",{"text-anchor":"middle",fill:"#35516A",style:"font:800 11px var(--fb);letter-spacing:.14em"});T(s,18,y0+Hh/2,"IMPACTO",{"text-anchor":"middle",fill:"#35516A",transform:`rotate(-90 18 ${y0+Hh/2})`,style:"font:800 11px var(--fb);letter-spacing:.14em"});
T(s,x0+W-8,y0+18,"ZONA CRÍTICA",{"text-anchor":"end",fill:"#BC0404",style:"font:800 11px var(--fb);letter-spacing:.12em"});
const cells={};R.forEach((r,k)=>{const key=r[2]+"-"+r[3];(cells[key]=cells[key]||[]).push(k)});const pos=[];Object.values(cells).forEach(ks=>ks.forEach((k,j)=>{const n=ks.length,off=(j-(n-1)/2)*42;pos[k]=[X(R[k][2])+off,Y(R[k][3])+(n>2&&j%2?14:0)]}));
const bub=R.map((r,k)=>{const[x,y]=pos[k],g=S("g",{class:"rk","data-a":"pop",style:`--d:${3+k*.35};transform-box:fill-box;transform-origin:center`},s);S("circle",{class:"b",cx:x,cy:y,r:19,fill:sv(r[2]*r[3]),stroke:"#fff","stroke-width":3},g);T(g,x,y+4.5,"R"+(k+1),{"text-anchor":"middle",fill:"#fff",style:"font:800 12px var(--fb)"});tip(g,`R${k+1} · ${r[0]}`,`probabilidade ${r[2]} · impacto ${r[3]}`);g.addEventListener("click",()=>sel(k));return g});
const L=$("riskList"),items=R.map((r,k)=>{const b=H("button",{class:"rkl"},L);b.innerHTML=`<span class="id" style="background:${sv(r[2]*r[3])}">R${k+1}</span><div><b>${r[0]}</b><span>${r[1]} · P${r[2]} × I${r[3]}</span></div>`;b.addEventListener("click",()=>sel(k));return b});
function sel(k){const r=R[k];items.forEach((b,j)=>b.classList.toggle("sel",j===k));bub.forEach((g,j)=>g.style.opacity=j===k?1:.45);
$("riskDet").innerHTML=`<div style="display:flex;align-items:center;gap:10px"><span style="display:grid;place-items:center;width:38px;height:38px;border-radius:50%;background:${sv(r[2]*r[3])};color:#fff;font:800 13px var(--fb)">R${k+1}</span><div style="flex:1"><div class="eye" style="margin:0">${r[1]} · severidade ${r[2]*r[3]} de 25</div><div style="font:800 21px/1.1 var(--fh);color:#002B49">${r[0]}</div></div>${adkChip(r[8])}</div>
<div style="display:grid;grid-template-columns:1fr 1.25fr 1fr;gap:12px;margin-top:10px">
<div><div style="font:800 10px var(--fb);letter-spacing:.12em;color:#BC0404;text-transform:uppercase">Sinal observável</div><div style="font:500 12.5px/1.4 var(--fb);color:#35516A;margin-top:3px">${r[4]}</div></div>
<div style="background:#EEF3F8;border-radius:8px;padding:7px 10px"><div style="font:800 10px var(--fb);letter-spacing:.12em;color:#33556D;text-transform:uppercase">Resposta proposta</div><div style="font:700 12.5px/1.4 var(--fb);color:#002B49;margin-top:3px">${r[5]}</div></div>
<div><div style="font:800 10px var(--fb);letter-spacing:.12em;color:#B35F00;text-transform:uppercase">Como saberemos</div><div style="font:500 12.5px/1.4 var(--fb);color:#35516A;margin-top:3px">${r[6]}</div><div class="small" style="margin-top:6px"><b style="color:#002B49">Dono:</b> ${r[7]}</div></div></div>`}
sel(0);ENTER["Riscos e mitigação"]=()=>sel(0)})();

/* ---------- ADKAR + BRIDGES ---------- */
(function(){const A=[["A","Consciência","#002B49","Por que mudar?",["Narrativa do patrocinador: por que o ONS investe no AXON","Mostrar o custo do legado: tempo, risco e dependência de pessoas","Roadshow por gerência com demonstrações reais"],"Pulso de consciência acima do critério por gerência"],
["D","Desejo","#33556D","O que eu ganho com isso?",["“O que muda para mim” por perfil","Transição transparente: ninguém descobre por boato","Multiplicadores e casos de colegas"],"Intenção de uso e adesão voluntária ao piloto"],
["K","Conhecimento","#5E8AB4","Como eu faço?",["Trilhas por perfil: explorar, executar, preparar, construir","Manual amigável e vídeos curtos","Ambiente de prática com estudos-exemplo"],"Trilha concluída por perfil e por gerência"],
["A","Habilidade","#F78C16","Consigo fazer no dia a dia?",["Prática assistida em rodadas reais","Plantões e multiplicadores durante a onda","Rodada paralela até a paridade"],"Aprovação em cenários críticos da rotina"],
["R","Reforço","#1F3263","Isso veio para ficar?",["Reconhecimento e “você pediu, fizemos”","Legado desligado: sem caminho de volta","Indicadores no ritual de cada gerência"],"Uso sustentado em 30, 60 e 90 dias"]];
const els=A.map(([L,n,c,q,li,ev],i)=>{const b=H("button",{class:"ak","data-a":"up",style:`--d:${3+i*.6}`},$("adkar"));b.innerHTML=`<div class="hd2" style="background:${c}"><span class="L">${L}</span><span class="nm">${n}<small>estágio ${i+1} de 5</small></span></div><div class="bd2"><div class="q">${q}</div><ul>${li.map(x=>`<li>${x}</li>`).join("")}</ul><div class="ev">Evidência · ${ev}</div></div>`;b.addEventListener("click",()=>{const on=b.classList.contains("sel");els.forEach(e=>{e.classList.remove("sel");e.style.opacity=""});if(!on){b.classList.add("sel");els.forEach(e=>{if(e!==b)e.style.opacity=.45})}});return b});
const s=$("bridges"),Z=[[0,430,"Fim","reconhecer o que se perde","Rotinas que deixam de existir, o legado que se dominava, o status de especialista. Nomear as perdas e valorizar o conhecimento acumulado.","#002B49"],[430,1050,"Zona neutra","convivência e aprendizado","Legado e AXON lado a lado, rodada paralela, dúvidas e produtividade em queda temporária. Suporte próximo, metas ajustadas e escuta ativa.","#5E8AB4"],[1050,1500,"Novo começo","a nova rotina","Novos papéis, primeiras vitórias e reconhecimento. O AXON vira o jeito normal de trabalhar e o legado sai de cena.","#F78C16"]];
Z.forEach(([a,b,t,st,d,c],i)=>{const g=S("g",{"data-a":"fade",style:`--d:${12+i}`},s);S("rect",{x:a+2,y:4,width:b-a-4,height:192,rx:10,fill:i===1?"#EEF3F8":i===0?"#F4F7FA":"#FEF6EC"},g);S("rect",{x:a+2,y:4,width:6,height:192,rx:3,fill:c},g);
fo(g,a+18,10,b-a-36,100,`<div style="font:800 19px/1.1 var(--fh);color:#002B49">${t} <span style="font:600 13px var(--fb);color:${c}">· ${st}</span></div><div style="font:500 12.5px/1.45 var(--fb);color:#35516A;margin-top:4px">${d}</div>`)});
const cv=path("M20 132 C200 130 330 132 430 142 C560 172 700 186 800 180 C930 170 990 150 1050 134 C1200 108 1340 98 1480 94",{fill:"none",stroke:"#002B49","stroke-width":3,class:"dr",pathLength:1,style:"--d:14;--dur:1.8s"},s);
T(s,1478,120,"engajamento e produtividade",{"text-anchor":"end",fill:"#6B7B8C",style:"font:600 11px var(--fb)"});
[["A·D",200],["K·A",740],["R",1270]].forEach(([l,x],i)=>{const g=S("g",{"data-a":"pop",style:`--d:${16+i};transform-box:fill-box;transform-origin:center`},s);S("rect",{x:x-26,y:160,width:52,height:22,rx:11,fill:"#122143"},g);T(g,x,175,l,{"text-anchor":"middle",fill:"#fff",style:"font:800 11px var(--fb)"});tip(g,"Estágios ADKAR mais trabalhados nesta zona",l)})})();

/* ---------- CINCO MOVIMENTOS + DOIS FIOS ---------- */
const MOVES=[["01","search","#5E8AB4","Entender","raio-x antes de agir",["Conversas com gerentes, mantenedores e times do MVP","Rodadas observadas ao lado de quem roda","Pulso de partida por perfil"],["Raio-x por gerência","Inventário de rotinas e legados","Mapa de impactos"],"A"],
["02","megaphone","#1F3263","Engajar","fazer o AXON ser desejado",["Coalizão de patrocinadores","Roadshow e AXON ao vivo","Histórias de colegas"],["Narrativa e kit do líder","Marca e vitrine AXON","Plano de comunicação por onda"],"AD"],
["03","cap","#33556D","Capacitar","até a primeira rodada sozinho",["Turmas com estudos reais","Plantões e prática assistida","Selo por nível"],["Trilhas por perfil","Manual amigável","Rede de multiplicadores"],"KH"],
["04","layers","#002B49","Migrar","rotina por rotina, com paridade",["Fila de ondas por valor e prontidão","Rodada paralela com aceite","Portões por legado"],["Plano de ondas","Checklist de go/no-go","Plano de desnutrição"],"HR"],
["05","refresh","#F78C16","Sustentar","o novo fica, o antigo não volta",["Escuta que vira backlog","Reconhecimento público","Vigiar a recaída ao legado"],["Canal de escuta","Rituais de reforço","Repasse ao ONS"],"R"]];
(function(){const el=$("moves");MOVES.forEach(([n,ic,c,t,v,cm,e,a],i)=>{const x=H("div",{class:"fr-card tlt","data-a":"up",style:`--d:${3+i*.5};--c:${c};padding:0;overflow:visible;display:flex;flex-direction:column;min-height:392px;border-top:0`},el);
x.innerHTML=`<div style="background:${c};color:#fff;border-radius:10px 10px 0 0;padding:12px 14px;position:relative"><div style="display:flex;align-items:center;justify-content:space-between"><span style="font:800 30px/1 var(--fh);opacity:.55">${n}</span><span style="width:40px;height:40px;border-radius:50%;background:rgba(255,255,255,.18);display:grid;place-items:center">${icon(ic,"#fff",21)}</span></div><div style="font:800 26px/1 var(--fh);margin-top:6px">${t}</div><div style="font:600 12px var(--fb);opacity:.9;margin-top:3px">${v}</div>${i<4?`<span style="position:absolute;right:-21px;top:50%;transform:translateY(-50%);width:20px;height:20px;color:${c};font:800 24px/20px var(--fb)">›</span>`:""}</div>
<div style="padding:10px 14px 12px;display:flex;flex-direction:column;gap:5px;flex:1"><div style="font:800 10px var(--fb);letter-spacing:.12em;color:#5E8AB4;text-transform:uppercase">Como fazemos</div><ul style="padding-left:16px;margin:0">${cm.map(z=>`<li style="font-size:12px;line-height:1.38;color:#35516A;margin-top:3px">${z}</li>`).join("")}</ul>
<div style="margin-top:6px;font:800 10px var(--fb);letter-spacing:.12em;color:#B35F00;text-transform:uppercase">Entregamos</div><ul style="padding-left:16px;margin:0">${e.map(z=>`<li style="font-size:12px;line-height:1.38;color:#002B49;font-weight:600;margin-top:3px">${z}</li>`).join("")}</ul>
<div style="margin-top:auto;display:flex;gap:4px;flex-wrap:wrap;padding-top:8px;border-top:1px solid var(--line2);align-items:center"><span class="small" style="font-weight:700;margin-right:4px">ADKAR</span>${[...a].map(adkChip).join("")}</div></div>`});
const s=$("threads"),W=1508,cw=(W-4*22)/5,cx=i=>i*(cw+22)+cw/2;
[["Fio · Pessoas","#F78C16",["quem é impactado e como","conversa antes do anúncio","trilha ou papel novo","caminho em prática","destino consolidado"]],["Fio · Medição","#33556D",["pulso de partida","pulso de confiança","1ª rodada sozinho","uso regular e recaída","horas devolvidas"]]].forEach(([n,c,L],k)=>{const y=30+k*88;path(`M0 ${y} H${W}`,{stroke:c,"stroke-width":6,"stroke-linecap":"round",fill:"none",class:"dr",pathLength:1,style:`--d:${8+k};--dur:1.6s`},s);const g=S("g",{"data-a":"fade",style:`--d:${8+k}`},s);S("rect",{x:0,y:y-14,width:132,height:28,rx:14,fill:c},g);T(g,66,y+5,n.toUpperCase(),{"text-anchor":"middle",fill:"#fff",style:"font:800 11px var(--fb);letter-spacing:.08em"});
L.forEach((l,i)=>{const x=Math.max(cx(i),200),d=S("g",{"data-a":"pop",style:`--d:${9+k+i*.3};transform-box:fill-box;transform-origin:center`},s);S("circle",{cx:x,cy:y,r:9,fill:"#fff",stroke:c,"stroke-width":4},d);T(d,x,y+32,l,{"text-anchor":"middle",fill:"#002B49",style:"font:700 13.5px var(--fb)"});tip(d,`${n} · ${MOVES[i][3]}`,l)})})})();

/* ---------- TRANSIÇÃO DAS PESSOAS ---------- */
(function(){const C=[["Eliminada","#BC0404","Editar arquivos de definição à mão"],["Automatizada","#F78C16","Disparar rodadas e validar com agentes"],["Transformada","#5E8AB4","Preparar estudos na interface de parâmetros"],["Mantida","#33556D","Analisar resultados e decidir"],["Nova","#002B49","Curar o catálogo e gerir o orçamento de nuvem"]];
C.forEach(([n,c,e],i)=>{const x=H("div",{"data-a":"up",style:`--d:${4+i*.4};border-radius:8px;background:#F4F7FA;border-top:4px solid ${c};padding:9px 10px;min-height:118px`},$("actCls"));H("div",{style:`font:800 16px var(--fh);color:${c}`},x,n);H("div",{style:"font:500 12px/1.4 var(--fb);color:#35516A;margin-top:3px"},x,"ex.: "+e)});
["Multiplicador AXON","Curador do catálogo de jobs","Dono de estudo","Guardião do legado","Validador de paridade","Gestor de orçamento de nuvem","Analista de dados de saída"].forEach((r,i)=>H("span",{class:"pill","data-a":"pop",style:`--d:${6+i*.3};background:${i===3?"#FEF1E2":"#DFE8F0"};color:${i===3?"#8A4A05":"#002B49"};font-size:13px;padding:9px 13px`},$("roles"),r));
chev($("steps4"),[["1","Saber primeiro","","conversa com o próprio líder, antes do anúncio","#5E8AB4"],["2","Escolher o caminho","","trilha no AXON ou papel novo, combinado","#33556D"],["3","Praticar com apoio","","multiplicador ao lado durante a onda","#F78C16"],["4","Assumir o papel","","reconhecimento público do novo papel","#1F3263"]]);
const s=$("ladder"),L=[["1","Requalificar no AXON","executor vira preparador; preparador vira construtor","#002B49"],["2","Realocar em estudos e análises","o tempo liberado vai para estudos que hoje não cabem na agenda","#33556D"],["3","Assumir papéis novos","multiplicador, curador, guardião do legado, dono de estudo","#5E8AB4"],["4","Apoiar outras demandas da gerência","projetos e frentes com falta de braço","#8FAAC8"],["5","Decisão de quadro, só como último recurso","com evidência, pela liderança e RH",null]];
L.forEach(([n,t,d,c],i)=>{const w=860-i*55,y=i*58,g=S("g",{"data-a":"left",style:`--d:${5+i*.5}`},s);S("rect",{x:0,y,width:w,height:50,rx:8,fill:c||"#fff",stroke:c?"none":"#BC0404","stroke-width":1.6,"stroke-dasharray":c?"0":"6 4"},g);
T(g,16,y+33,n,{fill:c?"#F9A64A":"#BC0404",style:"font:800 24px var(--fh)"});const tt=T(g,46,y+31,t,{fill:c?"#fff":"#BC0404",style:"font:800 15px var(--fh);letter-spacing:.01em"});const sp=S("tspan",{fill:c?"#DDEAF5":"#6B7B8C",style:"font:500 11.5px var(--fb)"},tt);sp.textContent="   ·  "+d;tip(g,`${n}º · ${t}`,d)});
const P=[["eye","Transparência antes do boato","quem é impactado sabe primeiro, pela liderança"],["people","Plano para cada pessoa muito impactada","conversa individual, trilha e destino combinados"],["star","O saber do legado vale ouro","quem mantém o legado vira guardião da migração"],["shield","Quadro é a última decisão","nunca a primeira, e nunca sem evidência"]];
P.forEach(([ic,t,d],i)=>{const x=H("div",{class:"card","data-a":"up",style:`--d:${9+i*.4};border-radius:10px;padding:12px 14px;min-height:150px`},$("princ"));H("div",{style:"width:32px;height:32px;border-radius:50%;background:#F78C16;display:grid;place-items:center;margin-bottom:6px",html:icon(ic,"#fff",17)},x);H("h4",null,x,t);H("p",{style:"font-size:11.5px;line-height:1.35"},x,d)})})();

/* ---------- DESNUTRIÇÃO DOS LEGADOS ---------- */
(function(){const s=$("decay"),x0=56,x1=985,y0=380,y1=30,X=m=>x0+m/6*(x1-x0),Y=v=>y0-v/100*(y0-y1);
[[2,3.5,"Piloto"],[3.5,4.5,"Onda 1"],[4.5,5.5,"Onda 2"],[5.5,6,"Sust."]].forEach(([a,b,l],i)=>{S("rect",{x:X(a),y:y1-6,width:X(b)-X(a),height:y0-y1+6,fill:i%2?"#F6F8FB":"#EEF3F8"},s);T(s,(X(a)+X(b))/2,y1+8,l,{"text-anchor":"middle",fill:"#35516A",style:"font:800 11px var(--fb);letter-spacing:.08em;text-transform:uppercase"})});
for(let v=0;v<=100;v+=25){S("line",{x1:x0,y1:Y(v),x2:x1,y2:Y(v),stroke:"#E3E9EF"},s);T(s,x0-8,Y(v)+4,v+"%",{"text-anchor":"end",fill:"#6B7B8C",style:"font:600 11px var(--fb)"})}
for(let m=0;m<6;m++)T(s,(X(m)+X(m+1))/2,y0+22,"Mês "+(m+1),{"text-anchor":"middle",fill:"#35516A",style:"font:800 11px var(--fb)"});
const LG=[[0,100],[2,100],[3,95],[3.5,80],[4,66],[4.5,46],[5,30],[5.5,18],[6,8]],AX=[[0,8],[2,10],[3,30],[3.5,42],[4,54],[4.5,68],[5,78],[5.5,87],[6,94]];
const pd=a=>a.map(([m,v],i)=>(i?"L":"M")+X(m).toFixed(1)+" "+Y(v).toFixed(1)).join(" ");
path(pd(LG)+` L${X(6)} ${y0} L${X(0)} ${y0} Z`,{fill:"rgba(0,43,73,.10)"},s);
const dfs=S("defs",null,s),pt=S("pattern",{id:"hatch",width:8,height:8,patternUnits:"userSpaceOnUse",patternTransform:"rotate(45)"},dfs);S("rect",{width:4,height:8,fill:"rgba(247,140,22,.25)"},pt);
S("rect",{x:X(2),y:Y(100),width:X(3.5)-X(2),height:Y(30)-Y(100),fill:"url(#hatch)",rx:6},s);T(s,(X(2)+X(3.5))/2,Y(58),"convivência",{"text-anchor":"middle",fill:"#B35F00",style:"font:800 12px var(--fb)"});T(s,(X(2)+X(3.5))/2,Y(52),"rodada paralela",{"text-anchor":"middle",fill:"#B35F00",style:"font:600 11px var(--fb)"});
path(pd(LG),{fill:"none",stroke:"#002B49","stroke-width":3.5,class:"dr",pathLength:1,style:"--d:4;--dur:1.8s"},s);path(pd(AX),{fill:"none",stroke:"#F78C16","stroke-width":3.5,class:"dr",pathLength:1,style:"--d:6;--dur:1.8s"},s);
LG.slice(2).forEach(([m,v])=>{const c=S("circle",{cx:X(m),cy:Y(v),r:4.5,fill:"#fff",stroke:"#002B49","stroke-width":2},s);tip(c,`Legado · ${v}% das rotinas`,`mês ${Math.ceil(m)}`)});AX.slice(2).forEach(([m,v])=>{const c=S("circle",{cx:X(m),cy:Y(v),r:4.5,fill:"#fff",stroke:"#F78C16","stroke-width":2},s);tip(c,`AXON · ${v}% das rotinas`,`mês ${Math.ceil(m)}`)});
T(s,X(6)-6,Y(8)-10,"legado",{"text-anchor":"end",fill:"#002B49",style:"font:800 13px var(--fb)"});T(s,X(6)-6,Y(94)+22,"AXON",{"text-anchor":"end",fill:"#F78C16",style:"font:800 13px var(--fb)"});
const G=[["Mapear","inventário do legado","Inventariar funções, usuários, dependências, exceções e quem mantém.","Inventário aceito pelo dono do legado.","Quem mantém o legado é convidado a ser guardião da migração.","A"],
["Espelhar","rodada paralela","A mesma rodada no legado e no AXON, lado a lado.","Paridade dentro da tolerância definida para cada modelo.","Guardiões e preparadores validam juntos; a confiança nasce da comparação.","K"],
["Transferir","AXON vira oficial","O legado perde funções aos poucos; o AXON passa a ser a fonte oficial.","Usuários treinados e aprovados no cenário crítico.","Plantões e multiplicadores próximos; metas da área ajustadas na transição.","H"],
["Congelar","somente leitura","Legado sem novas rodadas, apenas consulta ao histórico.","Ciclos completos sem incidente relevante.","Comunicar o fim com data; celebrar quem fez a transição.","R"],
["Desligar","fim do legado","Desligamento, arquivo do histórico e comunicação.","Aceite formal do dono do legado e da TI.","Capacidade liberada segue a ordem: requalificar e realocar primeiro.","R"]];
const gt=$("gates"),bs=G.map(([t,s2],i)=>{const b=H("button",null,gt);b.innerHTML=`<b>${i+1} · ${t}</b><span>${s2}</span>`;b.addEventListener("click",()=>sel(i));return b});
function sel(i){bs.forEach((b,k)=>{b.classList.toggle("on",k===i);b.classList.toggle("done",k<i)});const[t,s2,d,c,p,a]=G[i];
$("gateDet").innerHTML=`<div class="eye" style="color:#5E8AB4">Portão ${i+1} de 5</div><div style="font:800 28px/1.05 var(--fh);color:#002B49">${t} <span style="font:600 14px var(--fb);color:#6B7B8C">· ${s2}</span></div>
<p style="font-size:13.5px;line-height:1.5;margin-top:10px;color:#35516A">${d}</p>
<div style="margin-top:10px;background:#EEF3F8;border-radius:8px;padding:9px 12px"><div style="font:800 10.5px var(--fb);letter-spacing:.12em;color:#33556D;text-transform:uppercase">Critério para avançar</div><div style="font:700 13.5px/1.4 var(--fb);color:#002B49;margin-top:2px">${c}</div></div>
<div style="margin-top:10px;background:#FEF1E2;border-radius:8px;padding:9px 12px"><div style="font:800 10.5px var(--fb);letter-spacing:.12em;color:#B35F00;text-transform:uppercase">E as pessoas?</div><div style="font:600 13px/1.4 var(--fb);color:#002B49;margin-top:2px">${p}</div></div>
<div style="display:flex;align-items:center;gap:8px;margin-top:10px"><span class="small" style="font-weight:700">Estágio ADKAR em foco:</span>${adkChip(a)}<span class="small">${ADK[a][1]}</span></div>`}
sel(0);ENTER["Desnutrição dos legados"]=()=>sel(0)})();

/* ---------- CAPACITAÇÃO ---------- */
(function(){const T5=[["Explorar","todos · consumidores",100,"#9DBBD9","O que é o AXON e por que muda; onde ficam os resultados; catálogo e Axon Drive.","Vídeo curto, guia de bolso e roadshow.","Encontra sozinho o resultado que usava no legado."],
["Executar","executores",150,"#5E8AB4","Rodar um estudo pronto, acompanhar a execução, ler o custo previsto e reportar um erro.","Prática guiada no ambiente de testes e plantões.","Roda o estudo crítico da sua rotina sem ajuda."],
["Preparar","preparadores",200,"#33556D","Montar pipelines, configurar a interface de parâmetros, duplicar estudos e usar o assistente via MCP.","Oficinas com estudos reais da gerência, com o multiplicador ao lado.","Monta e valida um estudo novo com paridade aceita."],
["Construir","construtores",250,"#002B49","Empacotar o modelo em container, documentar entradas e saídas, build, logs e versões.","Mentoria técnica com o time do produto, padrões e exemplos.","Publica um container que gera as caixinhas corretas no catálogo."],
["Liderar","gestores · trilha paralela",175,"#F78C16","Orçamento do time, leitura do painel de adoção e conversa de transição com a equipe.","Kit do líder e sessões curtas.","Conduz o ritual da gerência com os indicadores."]];
const el=T5.map(([t,p,h,c,co,fm,ok],i)=>{const b=H("button",{"data-a":"up",style:`--d:${3+i*.5};height:${h}px;border:0;border-radius:10px 10px 0 0;background:${c};color:${i===0?"#002B49":"#fff"};text-align:left;padding:10px 12px;position:relative;${i===4?"background:repeating-linear-gradient(135deg,#F78C16 0 10px,#F9A64A 10px 20px);":""}transition:transform .2s,box-shadow .2s`},$("trail"));
b.innerHTML=`<span style="position:absolute;top:-22px;left:2px;font:800 10.5px var(--fb);letter-spacing:.1em;color:#6B7B8C;text-transform:uppercase">${i<4?"nível "+(i+1):"liderança"}</span><div style="font:800 18px/1.05 var(--fh)">${t}</div><div style="font:600 11px var(--fb);opacity:.9;margin-top:3px">${p}</div>`;b.addEventListener("click",()=>sel(i));return b});
function sel(i){el.forEach((b,k)=>{b.style.transform=k===i?"translateY(-6px)":"";b.style.boxShadow=k===i?"0 12px 24px rgba(14,28,57,.25)":""});const[t,p,,c,co,fm,ok]=T5[i];
$("trailDet").innerHTML=`<div style="display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:14px"><div><div class="eye" style="margin:0;color:#B35F00">Trilha ${t} · ${p}</div><div style="font:500 12.5px/1.45 var(--fb);color:#35516A;margin-top:3px">${co}</div></div><div><div class="eye" style="margin:0">Formato</div><div style="font:500 12.5px/1.45 var(--fb);color:#35516A;margin-top:3px">${fm}</div></div><div style="background:#EEF3F8;border-radius:8px;padding:6px 10px"><div class="eye" style="margin:0;color:#33556D">Pronto quando</div><div style="font:700 12.5px/1.4 var(--fb);color:#002B49;margin-top:2px">${ok}</div></div></div>`}
sel(1);
[["book","Guia de bolso"],["clock","Vídeos de até 3 min"],["grid","Ambiente de prática"],["chat","Plantões de dúvidas"],["people","Multiplicadores"],["ai","Assistente IA via MCP"],["star","Selo AXON por nível"]].forEach(([ic,t],i)=>H("span",{class:"pill","data-a":"pop",style:`--d:${10+i*.3};display:inline-flex;align-items:center;gap:6px;background:#fff;border:1px solid var(--line);font-size:12px;padding:6px 11px`,html:icon(ic,"#F78C16",15)+t},$("formats")));
$("bookIc").innerHTML=icon("book","#fff",24);
[["O AXON em 5 minutos","o que é, por que existe e o que muda para mim"],["Minha primeira rodada","passo a passo com telas reais"],["Onde está o que eu usava?","o de-para do legado para o AXON"],["Quanto custa minha rodada?","máquina, escala e orçamento do time"],["Deu erro: e agora?","reportar bug e acompanhar a correção"],["Perguntas que todo mundo faz","inclusive “e o meu trabalho?”"]].forEach(([t,d],i)=>{const x=H("div",{"data-a":"right",style:`--d:${5+i*.45};display:grid;grid-template-columns:34px 1fr;gap:10px;align-items:center;background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.14);border-radius:9px;padding:9px 10px`},$("toc"));H("span",{style:`display:grid;place-items:center;width:30px;height:30px;border-radius:50%;background:${i===5?"#F78C16":"#5E8AB4"};color:#fff;font:800 13px var(--fb)`},x,String(i+1));const y=H("div",null,x);H("div",{style:"font:800 15px/1.1 var(--fh);color:#fff"},y,t);H("div",{style:"font:500 11.5px var(--fb);color:#9DB7CE"},y,d)});
[["Por tarefa","não por tela"],["Linguagem","de quem usa"],["Visual","e curto"],["Vivo","a cada release"]].forEach(([a,b],i)=>{const x=H("div",{"data-a":"up",style:`--d:${9+i*.3};text-align:center;border-radius:8px;background:rgba(247,140,22,.14);border:1px solid rgba(247,140,22,.4);padding:6px 4px`},$("tocP"));H("div",{style:"font:800 14px var(--fh);color:#F9A64A"},x,a);H("div",{style:"font:600 10.5px var(--fb);color:#DDEAF5"},x,b)})})();

/* ---------- MARCA E ENGAJAMENTO ---------- */
(function(){[["1.240","rodadas no mês"],["2,3 mi","casos processados"],["860 h","devolvidas às equipes"],["±4%","custo previsto × realizado"],["3 de 12","legados desligados"],["96","usuários ativos"]].forEach(([v,l],i)=>{const t=H("div",{class:"tile","data-a":"pop",style:`--d:${5+i*.3}`},$("vtTiles"));H("b",null,t,v);H("span",null,t,l)});
const s=$("vtBars");[["PE",72],["PR",55],["PL",64],["OS",38],["PD",47]].forEach(([g,v],i)=>{const y=8+i*28;T(s,0,y+13,g,{fill:"#DDEAF5",style:"font:800 13px var(--fh)"});S("rect",{x:34,y,width:250,height:16,rx:8,fill:"rgba(255,255,255,.1)"},s);const r=S("rect",{class:"gbar",x:34,y,width:0,height:16,rx:8,fill:i%2?"#5E8AB4":"#F78C16"},s);r.dataset.w=250*v/100;T(s,318,y+13,v+"%",{"text-anchor":"end",fill:"#fff",style:"font:800 12px var(--fb)"})});
[["Parâmetro do tipo tabela no estudo de carga","entregue"],["Atalho para duplicar estudo","entregue"],["Exportar direto para o catálogo corporativo","em curso"]].forEach(([t,st])=>{const x=H("div",{style:"display:flex;align-items:center;gap:6px;font:600 11px/1.3 var(--fb);color:#DDEAF5"},$("vtFeed"));H("span",{style:`flex:none;font:800 9px var(--fb);letter-spacing:.06em;text-transform:uppercase;padding:2px 6px;border-radius:99px;background:${st==="entregue"?"#5E8AB4":"#F78C16"};color:#fff`},x,st);H("span",null,x,t)});
[["star","Identidade AXON","Nome, propósito e linguagem visual próprios: a rede que conecta os modelos."],["chart","Vitrine ao vivo","Indicadores da plataforma, chamados e entregas, abertos a todos."],["eye","AXON ao vivo","Roadshow e demonstrações por gerência, com estudos reais."],["chat","Histórias de colegas","Casos como o backtest de 176 mil casos, contados por quem fez."],["people","Rede de embaixadores","Multiplicadores com papel, agenda e reconhecimento."],["refresh","Escuta que vira entrega","Inquietações viram backlog; o retorno é público."]].forEach(([ic,t,d],i)=>{const x=H("div",{class:"card tlt","data-a":"up",style:`--d:${4+i*.4};border-radius:10px;padding:12px 14px;display:grid;grid-template-columns:36px 1fr;gap:10px;align-items:start`},$("engage"));H("span",{style:`width:36px;height:36px;border-radius:50%;background:${i%2?"#122143":"#F78C16"};display:grid;place-items:center`,html:icon(ic,"#fff",18)},x);const y=H("div",null,x);H("h4",{style:"margin:0"},y,t);H("p",{style:"font-size:11.5px;line-height:1.35"},y,d)});
chev($("launch"),[["01","Teaser","","curiosidade antes da onda","#5E8AB4"],["02","AXON ao vivo","","demo com estudo da gerência","#33556D"],["03","Primeiras vitórias","","casos e números da onda","#F78C16"],["04","Adeus ao legado","","celebrar o desligamento","#1F3263"]]);
[["A","Por que o ONS está mudando"],["D","O que muda para mim"],["K","Como eu faço"],["H","Estou fazendo de verdade"],["R","Isso veio para ficar"]].forEach(([l,m],i)=>{const x=H("div",{"data-a":"up",style:`--d:${13+i*.3};background:#fff;border-radius:8px;padding:6px 8px;border-top:3px solid ${ADK[l][0]}`},$("msgs"));x.innerHTML=`${adkChip(l)}<div style="font:700 11.5px/1.3 var(--fb);color:#002B49;margin-top:4px">“${m}”</div>`})})();

/* ---------- FUNIL DE ADOÇÃO ---------- */
(function(){const s=$("funnel"),F=[["","Público da onda",100,"#98A6B3"],["A","Sabem por que o ONS muda",90,"#002B49"],["D","Querem usar o AXON",66,"#33556D"],["K","Concluíram a trilha",60,"#5E8AB4"],["H","Primeira rodada sozinhos",52,"#F78C16"],["","Uso regular",44,"#C96A05"],["R","Indicam a colegas",30,"#1F3263"]],cx=380,maxW=560,bh=50,gp=12;
F.forEach(([l,n,v,c],i)=>{const y=6+i*(bh+gp),w=maxW*v/100,g=S("g",{"data-a":"grow",style:`--d:${3+i*.4};transform-box:fill-box;transform-origin:center`},s);S("rect",{x:cx-w/2,y,width:w,height:bh,rx:8,fill:c},g);
T(g,cx,y+21,n,{"text-anchor":"middle",fill:"#fff",style:"font:800 14px var(--fh);letter-spacing:.02em"});T(g,cx,y+39,v+"%",{"text-anchor":"middle",fill:"#fff",opacity:.85,style:"font:700 12px var(--fb)"});
if(l){const b=S("g",null,s);S("rect",{x:6,y:y+13,width:26,height:24,rx:5,fill:ADK[l][0]},b);T(b,19,y+30,l==="H"?"A":l,{"text-anchor":"middle",fill:l==="H"?"#0E1C39":"#fff",style:"font:800 12px var(--fb)"});T(b,40,y+30,ADK[l][1],{fill:"#6B7B8C",style:"font:600 11px var(--fb)"})}
if(i){const dr=F[i-1][2]-v;const t=T(s,cx+w/2+12,y+6,"−"+dr+" p.p.",{fill:dr>=20?"#BC0404":"#98A6B3",style:`font:800 ${dr>=20?13:11}px var(--fb)`});tip(g,n,`${v}% do público · queda de ${dr} p.p. em relação à etapa anterior`)}});
const an=S("g",{"data-a":"up",style:"--d:9"},s);S("rect",{x:4,y:444,width:682,height:50,rx:10,fill:"#FBEDEC",stroke:"#BC0404","stroke-dasharray":"5 4"},an);T(an,20,465,"PONTO DE BARREIRA · DESEJO (−24 p.p.)",{fill:"#BC0404",style:"font:800 11px var(--fb);letter-spacing:.08em"});T(an,20,483,"A maior queda diz onde agir primeiro: conversas de caminho, histórias de colegas e patrocinador presente.",{fill:"#002B49",style:"font:600 12px var(--fb)"});
const L=[["pulse","Pulso de confiança","0–100 por perfil, a cada 30 dias"],["cap","Trilha concluída","concluintes ÷ inscritos, por perfil"],["clock","Tempo até a 1ª rodada sozinho","dias entre a turma e a primeira rodada sem ajuda"],["people","Caminho combinado","impactados com destino definido ÷ impactados"]],R=[["chart","Uso regular","quem rodou no AXON nas últimas 4 semanas ÷ público da onda",0],["layers","Rotinas migradas","rotinas da onda que só rodam no AXON ÷ rotinas da onda",0],["refresh","Recaída ao legado","rodadas feitas no legado depois do go · meta: zero",1],["coin","Horas devolvidas","horas de operação por rotina, antes − depois",0]];
const card=(p,[ic,t,f,hl],i,d)=>{const x=H("div",{class:"kpi tlt","data-a":"up",style:`--d:${d+i*.35};--c:${hl?"#BC0404":p==="lead"?"#5E8AB4":"#002B49"};${hl?"background:#FBEDEC;":""}min-height:136px`},$(p));x.innerHTML=`<div style="display:flex;align-items:center;gap:8px"><span style="width:30px;height:30px;border-radius:8px;background:${hl?"#BC0404":p==="lead"?"#5E8AB4":"#122143"};display:grid;place-items:center;flex:none">${icon(ic,"#fff",16)}</span><h4 style="margin:0">${t}</h4></div><div class="f">${f}</div>`};
L.forEach((k,i)=>card("lead",k,i,6));R.forEach((k,i)=>card("lag",k,i,9))})();

/* ---------- ROADMAP ---------- */
(function(){chev($("rmPh"),PHASES);
gantt($("gantt"),[["Entender","#5E8AB4",[[0,1.5,"Raio-x por gerência"],[2.5,6,"Pulsos antes de cada onda",1]]],
["Engajar","#1F3263",[[.5,1.5,"Narrativa e coalizão"],[1.5,3,"Marca e vitrine AXON"],[3,6,"Lançamentos por gerência",1]]],
["Capacitar","#33556D",[[1,2.5,"Trilhas e manual"],[2.5,3.5,"Turma piloto"],[3.5,5.5,"Turmas por onda"]]],
["Migrar","#002B49",[[1,2,"Fila de ondas"],[2,3.5,"Piloto + paralela"],[3.5,4.5,"Onda 1"],[4.5,5.5,"Onda 2"],[5.5,6,"Desligar"]]],
["Sustentar","#5E8AB4",[[2,5.5,"Escuta → backlog → retorno",1],[5.5,6,"Repasse"]]],
["Fio · Pessoas","#F78C16",[[.5,2,"Quem é impactado"],[2,3.5,"Conversas e caminhos"],[3.5,6,"Caminhos em prática",1]]],
["Fio · Medição","#C96A05",[[.5,1.5,"Pulso de partida"],[1.5,2.5,"Funil no ar"],[2.5,6,"Funil, recaída e horas devolvidas por onda",1]]]],{lab:290,rh:46,top:40,ms:[[2,"Go do piloto"],[3.5,"Go onda 1"],[4.5,"Go onda 2"],[6,"Repasse ao ONS"]]});
[["cpu","Técnica",["Container documentado e caixinhas corretas","Paridade aceita pelo dono do modelo","Acesso e orçamento do time liberados"],"#002B49"],["people","Pessoas",["Pulso de confiança acima do critério","Trilha concluída e multiplicador na gerência","Impactados com caminho combinado"],"#F78C16"],["calendar","Rotina",["Fora de janelas com prazo crítico","Guardião do legado nomeado","Patrocinador presente no lançamento"],"#5E8AB4"]].forEach(([ic,t,L,c],i)=>{const x=H("div",{"data-a":"up",style:`--d:${12+i*.4};background:#fff;border:1px solid var(--line);border-top:4px solid ${c};border-radius:10px;padding:8px 12px`},$("rmGates"));x.innerHTML=`<div style="display:flex;align-items:center;gap:8px"><span style="width:26px;height:26px;border-radius:50%;background:${c};display:grid;place-items:center">${icon(ic,"#fff",14)}</span><b style="font:800 15px var(--fh);color:#002B49">${t}</b></div>${L.map(z=>`<div style="display:grid;grid-template-columns:16px 1fr;gap:6px;margin-top:4px;font:600 11.5px/1.3 var(--fb);color:#35516A">${icon("check",c,14)}<span>${z}</span></div>`).join("")}`})})();

/* ---------- GOVERNANÇA ---------- */
(function(){const RL=["Patrocinador executivo","Gerências PE–PD","Dono do produto AXON","TI · arquitetura e segurança","RH · Pessoas","Multiplicadores","A&M · GMO"];
const D=[["Go/no-go de cada onda","ARCCICS"],["Plano de transição das pessoas","CAIIRIS"],["Desligar um legado","IARRICS"],["Narrativa, marca e comunicação","ASCICSR"],["Trilhas e manual amigável","ICAICSR"],["Priorizar inquietações no backlog","ICACISR"],["Orçamento de nuvem por time","ARSCIII"],["Comunicar ao time o impacto no trabalho","CAIIRSS"]];
const CC={A:["#002B49","#fff"],R:["#5E8AB4","#fff"],S:["#DFE8F0","#002B49"],C:["#FDE3C4","#8A4A05"],I:["#F4F5F7","#98A6B3"]},NM={A:"Aprova",R:"Responsável",S:"Apoia",C:"Consultado",I:"Informado"};
const t=$("rasci"),h=H("tr",null,t);H("th",{style:"width:250px"},h,"Decisão \\ papel");RL.forEach(r=>H("th",{style:"text-align:center;font-size:9.5px;line-height:1.2"},h,r));
D.forEach(([d,l],i)=>{const tr=H("tr",{"data-a":"up",style:`--d:${4+i*.35}`},t);H("td",{style:"font-weight:700;color:#002B49"},tr,d);[...l].forEach((c,j)=>{const td=H("td",{style:`text-align:center;font:800 18px var(--fh);background:${CC[c][0]};color:${CC[c][1]};border:2px solid #fff;padding:12px 4px`},tr,c);tip(td,`${RL[j]} · ${NM[c]}`,d)})});
chev($("esc"),[["1","Multiplicador","no dia","resolve na rotina ou registra a barreira","#5E8AB4"],["2","Pulso da onda","na semana","GMO e produto atacam a causa","#33556D"],["3","Mesa de adoção","em 15 dias","gerências e RH decidem ajustes","#F78C16"],["4","Conselho AXON","no mês","prioridade, recurso ou go/no-go","#002B49"]]);
Object.keys(CC).forEach(k=>H("span",{style:"display:flex;align-items:center;gap:6px",html:`<i style="display:inline-grid;place-items:center;width:20px;height:20px;border-radius:4px;background:${CC[k][0]};color:${CC[k][1]};font:800 11px var(--fb);font-style:normal">${k}</i>${NM[k]}`},$("rasLeg")));
const G=$("govSide");[["Mensal","Conselho AXON","Patrocinador e gerentes PE–PD, com a TI","orçamento de nuvem · go/no-go das ondas · legados a desligar","#002B49"],["Quinzenal","Mesa de adoção","Gerências, RH, produto e GMO","funil por gerência · caminhos das pessoas · barreiras","#F78C16"],["Semanal","Pulso da onda","GMO, produto e multiplicadores","dúvidas · bugs · recaídas · ações da semana","#5E8AB4"]].forEach(([f,n,w,p,c],i)=>{const x=H("div",{class:"card","data-a":"left",style:`--d:${6+i*.5};border-radius:12px;padding:12px 14px;border-left:6px solid ${c};margin-left:${i*18}px`},G);x.innerHTML=`<div style="display:flex;align-items:baseline;gap:8px"><span style="font:800 22px var(--fh);color:${c}">${f}</span><span style="font:800 15px var(--fh);color:#002B49">${n}</span></div><div class="small" style="font-weight:700;color:#35516A">${w}</div><div style="font:600 12px var(--fb);color:#002B49;margin-top:4px">${p}</div>`});
const x=H("div",{class:"card nv","data-a":"up",style:"--d:9;border-radius:12px;padding:12px 16px"},G);x.innerHTML=`<div class="eye" style="color:#F9A64A">Regra de ouro</div><div style="font:800 19px/1.15 var(--fh);color:#fff">Um único A por decisão, e a liderança comunicando primeiro.</div><p style="margin-top:6px;font-size:12px">Multiplicadores: pelo menos um por gerência e por perfil crítico, com tempo protegido na agenda.</p>`})();

/* ---------- CANVAS DA PROPOSTA ---------- */
(function(){const mv=MOVES.map(m=>`<span class="pill" style="background:${m[2]};color:#fff;margin:2px 3px 0 0;display:inline-block">${m[0]} ${m[3]}</span>`).join("");
canvas($("canvas"),[["warn","Por quê","O desafio","O AXON substitui legados mantidos por muitas pessoas. Sem gestão da mudança, a plataforma fica restrita aos entusiastas e o medo de perder o trabalho freia a adoção.",1],
["layers","O quê","5 movimentos + 2 fios",mv+`<div style="margin-top:6px">costurados pelos fios <b style="color:#B35F00">Pessoas</b> e <b style="color:#33556D">Medição</b>.</div>`],
["refresh","Como","Método","ADKAR por pessoa, transição de Bridges para o que se perde, adoção por ondas com rodada paralela e desnutrição gradual dos legados."],
["people","Quem","Papéis","<b style='color:#002B49'>ONS:</b> patrocinador, gerências PE–PD, dono do produto, TI, RH, multiplicadores e guardiões dos legados. <b style='color:#002B49'>A&amp;M:</b> liderança da mudança e especialistas de engajamento, capacitação e medição."],
["target","Como saberemos","Sucesso","Funil de adoção por gerência, recaída ao legado igual a zero, pessoas com caminho combinado e horas devolvidas às equipes."],
["check","O que entregamos","Entregáveis","Raio-x por gerência · narrativa, marca e vitrine · trilhas, manual amigável e multiplicadores · fila de ondas, checklist de go/no-go e desnutrição · caminhos das pessoas · funil e repasse ao ONS."]]);chev($("ptPh"),PHASES)})();

