/* ===== Proposta 2 · Gestão de Mudanças (GMO) · adoção do AXON · 6 páginas ===== */
window.DECK={brandSub:"ONS · AXON · Gestão de Mudanças",rightLabel:"Proposta 2 · GMO",footLabel:"AXON · ADOÇÃO · GMO",
parts:[["Capa","Contexto"],["Contexto","1 · Contexto"],["Método","2 · Método"],["Plano de trabalho","3 · Plano de trabalho"]],
chapters:{"1 · Contexto":["01","Contexto","O AXON já funciona. O que muda, para quem, e o que pode dar errado."],"2 · Método":["02","Método","ADKAR, transição de pessoas e adoção por ondas: uma pessoa de cada vez."],"3 · Plano de trabalho":["03","Plano de trabalho","Cinco movimentos e seis meses para o AXON virar rotina nas cinco gerências."]},
zoom:["pipe","timeBars","heat","riskMx","bridges","curve","threads","gantt"],
descDefault:"Proposta de gestão de mudanças para a adoção do AXON.",
desc:{"Capa":"Capa em Particle System (efeito 30 do Guia DTS): a rede viva representa pessoas, sistemas e gerências conectados. Mova o cursor para afastar as partículas e clique para emitir um pulso.",
"O AXON e o que muda":"Contexto 1 de 2. Como o AXON funciona, do container ao resultado (clique numa etapa: o foco destaca e a legenda mostra o que muda para as pessoas); hoje × com o AXON em seis situações; para onde vai o tempo das equipes; e o ponto de partida.",
"Quem é impactado e os riscos":"Contexto 2 de 2. Cinco categorias de uso, cada uma com o que perde, o que ganha, o receio e a resposta; o mapa de impactos por gerência e dimensão (ilustrativo) e o radar de riscos, em que os mais graves são sobre pessoas.",
"Método ADKAR":"O método: ADKAR para avançar uma pessoa de cada vez, atacando o primeiro elo que falha; a transição de Bridges para o que as pessoas deixam para trás; e a curva de adoção que define quem entra em cada onda.",
"Como faremos":"Plano de trabalho 1 de 2. Cinco movimentos (Entender, Engajar, Capacitar, Migrar, Sustentar) costurados pelos fios Pessoas e Medição, com os três temas mais sensíveis: legados, destino das pessoas e capacitação.",
"Roadmap e resultados":"Plano de trabalho 2 de 2. Roadmap relativo de seis meses: o cursor percorre os meses e acende movimentos, fios e marcos de go. Abaixo, o checklist de go/no-go, os resultados esperados e o que entregamos."}};

const ADK={A:["#002B49","Consciência"],D:["#33556D","Desejo"],K:["#5E8AB4","Conhecimento"],H:["#F78C16","Habilidade"],R:["#1F3263","Reforço"]};
const adkChip=l=>`<span class="adk" title="${ADK[l][1]}" style="background:${ADK[l][0]};${l==="H"?"color:#0E1C39":""}">${l==="H"?"A":l}</span>`;
const PHASES=[["01","Raio-x","mês 1","Públicos, rotinas, legados e pulso de partida","#5E8AB4"],["02","Preparação","mês 2","Narrativa, trilhas, caminhos e fila de ondas","#5E8AB4"],["03","Piloto","mês 3","Gerência piloto e rodada paralela","#F78C16"],["04","Ondas","meses 4–5","Lançamentos e desnutrição dos legados","#1F3263"],["05","Autonomia","mês 6","Reforço e repasse ao ONS","#33556D"]];
const SL=t=>[...document.querySelectorAll(".slide")].find(s=>s.dataset.t===t);
document.querySelectorAll(".slide").forEach(s=>{if(s.querySelector("[data-fx-type]"))FXR.add(s,fxTypography(s,{delay:220,gap:120}));if(s.querySelector("[data-fx-reveal]"))FXR.add(s,fxMaskReveal(s,{stagger:120,delay:500}))});

/* ---------- CAPA ---------- */
(function(){const sl=SL("Capa");FXR.add(sl,fxCoverParticles(sl,{count:140}));FXR.add(sl,fxShimmerSweep(sl,{delay:1100,every:6500}))})();

/* ---------- 2 · O AXON E O QUE MUDA ---------- */
(function(){const sl=SL("O AXON e o que muda");
const P=[["box","Container","código + contrato de E/S","o modelo é empacotado com a documentação dos jobs, das entradas e das saídas; build, logs e versões monitorados","o “como roda” sai da cabeça de quem mantém o legado"],["grid","Catálogo de jobs","caixinhas geradas pela doc","a documentação do container gera os blocos; o contrato garante que só roda o que bate com o código","escolher um bloco pronto em vez de pedir ajuste"],["flow","Pipeline","orquestrado por E/S","fluxos montados por arrastar e conectar; a sequência é resolvida pelas entradas e saídas","a lógica da rodada fica visível para todos"],["sliders","Estudo","UI dinâmica de parâmetros","faixa, número, seleção, multisseleção, data, texto e tabela, salvos por estudo e duplicáveis","parâmetro novo sem pedir desenvolvimento"],["cloud","Execução","nuvem, fan-out e orçamento","máquina e escala escolhidas, milhares de casos em paralelo, custo previsto por rodada e orçamento do time","cada time gere o próprio orçamento"],["out","Resultado","catálogo, download, Axon Drive","saída para o catálogo corporativo, download ou Axon Drive com os projetos permitidos","saber onde está o que antes ficava no legado"]];
const pp=$("pipe");P.forEach(([ic,t,s2,d,pe],i)=>{const b=H("div",{class:"st","data-fx-node":"p"+i,"data-fx-step":String(i+1),"data-fx-caption":`${i+1} · ${t}: ${d}. Para as pessoas: ${pe}.`,style:"min-height:138px;gap:6px"},pp);b.innerHTML=`<span class="n">0${i+1}</span><div style="display:flex;align-items:center;gap:10px"><div class="ic" style="flex:none">${icon(ic,"#fff",20)}</div><div><b style="display:block;margin:0">${t}</b><i>${s2}</i></div></div><div class="pe">Para as pessoas: ${pe}</div>`});
$("pipeCap").textContent=`1 · Container: ${P[0][3]}. Para as pessoas: ${P[0][4]}.`;
FXR.add(sl,fxConnector(pp,{edges:[["p0","p1"],["p1","p2"],["p2","p3"],["p3","p4"],["p4","p5"]],stagger:200,hover:false,auto:false,dim:false,speed:90}));
const sp=fxSpotlight(pp,{caption:$("pipeCap"),auto:false,dim:.5,pad:6,delay:2400});FXR.add(sl,{play(){sp.play()},stop(){sp.stop();sp.clear()}});
pp.querySelectorAll(".st").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();pp.querySelectorAll(".st").forEach(x=>x.classList.toggle("sel",x===b));sp.focus(b)}));
const R=[["sliders","Configurar estudo","vários arquivos de definição editados à mão","UI de parâmetros salva e duplicável; parâmetro novo sem pedir desenvolvimento"],["cpu","Rodar modelo","servidores e filas locais; lotes grandes levam dias","nuvem escalável; milhares de casos em paralelo, em horas"],["coin","Custo da rodada","pouco visível e difícil de prever","custo previsto por rodada e orçamento mensal e anual por time"],["layers","Sistemas","legados e satélites, cada um com seus mantenedores","uma plataforma para qualquer modelo em container"],["inbox","Validar com agentes","e-mails e ligações, caso a caso","Caixa de entrada: processamento e retorno automáticos, no mesmo canal"],["bug","Suporte","chamado genérico, sem contexto","bug com tela, versão e sessão; correção simples assistida por IA, com aprovação humana"]];
const c=$("cmp3");R.forEach(([ic,k,o,n],i)=>{const r=H("div",{style:"display:grid;grid-template-columns:180px 1fr;border-bottom:1px solid var(--line2);min-height:50px"},c);H("div",{style:"display:flex;align-items:center;gap:8px;font:800 14px/1.15 var(--fh);color:#002B49;background:#F4F7FA;padding:5px 10px",html:icon(ic,"#5E8AB4",16)+`<span>${k}</span>`},r);const v=H("div",{style:"position:relative;display:flex;align-items:center;padding:5px 12px;font:500 12.5px/1.35 var(--fb);color:#6B4A2A"},r);H("span",null,v,o);const nn=H("div",{class:"cmpN",style:`transition-delay:${i*90}ms`},v);nn.textContent=n});
const sg=$("cmpSeg");const set=v=>{sg.querySelectorAll("button").forEach(b=>b.classList.toggle("on",+b.dataset.v===v));c.classList.toggle("fut",v===1);bars(v)};sg.querySelectorAll("button").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();clearTimeout(au);set(+b.dataset.v)}));
const s=$("timeBars"),D=[[55,25,20],[20,30,50]],CL=["#5E8AB4","#9DBBD9","#F78C16"],L=["Operar sistemas e arquivos","Preparar estudos","Analisar e decidir"],rows=[];
["Hoje","Com o AXON"].forEach((n,r)=>{const y=4+r*58;T(s,0,y+12,n,{fill:r?"#F9A64A":"#DDEAF5",style:"font:800 13px var(--fh);letter-spacing:.05em;text-transform:uppercase"});let x=0;const g=[];D[r].forEach((v,k)=>{const w=548*v/100,rc=S("rect",{x,y:y+18,width:w-2,height:30,rx:5,fill:CL[k]},s),tt=T(s,x+w/2,y+38,v+"%",{"text-anchor":"middle",fill:k===1?"#0E1C39":"#fff",style:"font:800 14px var(--fh)"});tip(rc,`${n} · ${L[k]}`,`${v}% do tempo · ilustrativo`);g.push([rc,tt,k]);x+=w});rows.push(g)});
L.forEach((l,k)=>{S("rect",{x:k*180,y:128,width:12,height:12,rx:3,fill:CL[k]},s);T(s,k*180+18,139,l,{fill:"#C8DBEB",style:"font:600 11.5px var(--fb)"})});const plus=T(s,548,162,"",{"text-anchor":"end",fill:"#F9A64A",style:"font:800 13px var(--fb)"});
function bars(v){rows[1].forEach(([rc,tt,k])=>{rc.style.transition=tt.style.transition="opacity .4s";rc.style.opacity=tt.style.opacity=v?(k===2?1:.35):.18});rows[0].forEach(([rc,tt,k])=>{rc.style.opacity=tt.style.opacity=v&&k!==2?.45:1});plus.textContent=v?"+30 p.p. em análise e decisão":""}
let au=0;FXR.add(sl,{play(){set(0);clearTimeout(au);au=setTimeout(()=>set(1),3000)},stop(){clearTimeout(au)}});set(0);
FXR.add(sl,fxGlowLightSweep($("evGlow"),{interval:6500,delay:2200,entrance:false}))})();

/* ---------- 3 · QUEM É IMPACTADO E OS RISCOS ---------- */
(function(){const sl=SL("Quem é impactado e os riscos");
const PS=[["code","#002B49","Construtores","desenvolvem e empacotam modelos",4,"o controle artesanal do próprio servidor","versionamento, build e escala","“Vou ter que reescrever tudo?”","padrão de container e mentoria"],["bolt","#F78C16","Usam só o AXON","rodam estudos todos os dias",5,"a operação diária que ocupa a agenda","tempo para análise e novos estudos","“O meu trabalho vai acabar?”","caminho individual e requalificação"],["flow","#33556D","Usam de vez em quando","preparam ou rodam estudos pontuais",3,"o arquivo de definição que já sabiam editar","estudo salvo para duplicar","“Vou esquecer como faz?”","manual por tarefa e assistente MCP"],["eye","#5E8AB4","Consultam","usam resultados para decidir",2,"o caminho até o arquivo de sempre","resultado no catálogo e no Axon Drive","“Onde encontro o que eu usava?”","guia de bolso e de-para do legado"],["coin","#1F3263","Gestores","lideram time e orçamento",3,"o desenho atual de equipe","custo por rodada visível","“Como redistribuo o meu time?”","kit do líder e decisões com RH"]];
const pe=$("pers3");PS.forEach(([ic,cl,n,r,lv,lo,ga,wo,re],i)=>{const x=H("div",{class:"pers","data-a":"up",style:`--d:${5+i*.35};border-top:5px solid ${cl};--ic:${cl};padding:10px 12px;gap:5px;min-height:176px`},pe);if(i===1)x.dataset.fxStep="1";x.innerHTML=`<div class="top"><span class="av" style="background:${cl};width:34px;height:34px">${icon(ic,"#fff",18)}</span><div><h4 style="font-size:15px">${n}</h4><div class="ro" style="font-size:10.5px">${r}</div></div><div class="int" title="intensidade ${lv}/5 (ilustrativa)">${[1,2,3,4,5].map(k=>`<i class="${k<=lv?"on":""}" style="height:16px;width:5px"></i>`).join("")}</div></div>${[["l","Perde",lo],["g","Ganha",ga],["w","Receio",`<i>${wo}</i>`],["", "Resposta",`<b style="color:#002B49">${re}</b>`]].map(([c2,lb,tx])=>`<div class="row" style="font-size:11px;grid-template-columns:58px 1fr;line-height:1.3"><b class="${c2}" ${c2?"":"style='color:#002B49'"}>${lb}</b><span>${tx}</span></div>`).join("")}`});
const sp=fxSpotlight(pe,{auto:false,dim:.55,pad:6,delay:3000});let t2=0;FXR.add(sl,{play(){sp.play();clearTimeout(t2);t2=setTimeout(()=>sp.clear(),5800)},stop(){clearTimeout(t2);sp.stop();sp.clear()}});
pe.querySelectorAll(".pers").forEach(card=>card.addEventListener("pointerenter",()=>{clearTimeout(t2);sp.focus(card)}));pe.addEventListener("pointerleave",()=>sp.clear());
const G=["PE","PR","PL","OS","PD"],Dm=[["Rotinas de rodada","Quais rodadas mudam de dono, de passo a passo ou de frequência?","mapa das rotinas que migram, mudam ou somem"],["Legados e satélites","Que sistemas, planilhas e scripts pessoais deixam de ser necessários?","fila de desnutrição e guardião de cada legado"],["Papéis e alçadas","Quem passa a montar, rodar, aprovar e pagar cada estudo?","papéis novos e quem aprova o quê"],["Competências","O que cada perfil precisa saber fazer sozinho no AXON?","lacunas que definem trilhas e multiplicadores"],["Capacidade liberada","Quanto tempo volta para a equipe, e para onde vai?","destinos: requalificar e realocar"],["Interface com agentes","Quem fora do ONS percebe a mudança de canal?","comunicação externa e Caixa de entrada"],["Confiança no resultado","As pessoas acreditam no número que sai do AXON?","critério de paridade por modelo"]];
const V=[[3,3,2,3,2,1,2],[2,3,2,2,2,1,2],[3,2,2,3,3,1,0],[2,2,3,2,2,2,3],[3,3,2,2,3,3,0]],LB={3:"Alto",2:"Médio",1:"Baixo",0:"?"},CL={3:"l3",2:"l2",1:"l1",0:"lx"};
const t=$("heat");t.style.borderSpacing="4px";const hr=H("tr",null,t);H("th",{style:"width:46px"},hr,"");Dm.forEach((d,j)=>{const th=H("th",{class:"ch",style:"font-size:9px;padding:3px 2px 4px"},hr,d[0]);th.addEventListener("click",e=>{e.stopPropagation();sel(j,true)})});
G.forEach((g,i)=>{const tr=H("tr",null,t);H("th",{class:"rh",style:"font-size:16px"},tr,g);V[i].forEach((v,j)=>{const td=H("td",{class:CL[v],style:"height:38px;font-size:10px"},tr,LB[v]);td.dataset.j=j;tip(td,`${g} · ${Dm[j][0]}`,v?`intensidade ${LB[v].toLowerCase()} · ilustrativa`:"a investigar no raio-x");td.addEventListener("click",e=>{e.stopPropagation();sel(j,true)})})});
function sel(j,dim){t.querySelectorAll("th.ch").forEach((h,k)=>h.classList.toggle("sel",k===j));t.classList.toggle("dim",!!dim);t.querySelectorAll("td").forEach(td=>td.classList.toggle("on",+td.dataset.j===j));const[n,q,o]=Dm[j];$("heatDet").innerHTML=`<div style="display:grid;grid-template-columns:1.3fr 1fr;gap:12px;align-items:center"><div><span class="eye" style="color:#B35F00">${n} · </span><span style="font:700 12.5px/1.35 var(--fb);color:#002B49">${q}</span></div><div style="background:#EEF3F8;border-radius:8px;padding:5px 10px"><span class="eye" style="color:#33556D">Saída para o plano · </span><span style="font:700 12px var(--fb);color:#002B49">${o}</span></div></div>`}
sel(1,false);
const RK=[["Medo de perder o trabalho",4,5,"conversa do líder antes de qualquer anúncio; caminho combinado para cada impactado",1],["Perda do saber dos legados",4,5,"mantenedor vira guardião e registra os casos especiais",1],["Resultado diferente do legado",3,5,"rodada paralela com tolerância de paridade aceita",1],["Convivência dupla sobrecarrega",4,4,"paralela com começo e fim, fora dos picos",1],["Produto com time enxuto",4,4,"multiplicadores como 1ª linha e triagem assistida",0],["Recaída ao legado “por garantia”",3,4,"legado congelado após o go e recaída medida",0]];
const sv=v=>v>=16?"#BC0404":v>=10?"#F78C16":"#5E8AB4",s=$("riskMx"),x0=22,y0=4,cw=34,X=p=>x0+(p-.5)*cw,Y=i=>y0+5*cw-(i-.5)*cw;
for(let p=1;p<=5;p++)for(let i=1;i<=5;i++){const v=p*i;S("rect",{x:x0+(p-1)*cw+1,y:y0+(5-i)*cw+1,width:cw-2,height:cw-2,rx:3,fill:v>=16?"rgba(188,4,4,.13)":v>=10?"rgba(247,140,22,.13)":"#F2F5F8"},s)}
T(s,x0+5*cw/2,y0+5*cw+16,"PROBABILIDADE →",{"text-anchor":"middle",fill:"#35516A",style:"font:800 9px var(--fb);letter-spacing:.1em"});T(s,9,y0+5*cw/2,"IMPACTO →",{"text-anchor":"middle",fill:"#35516A",transform:`rotate(-90 9 ${y0+5*cw/2})`,style:"font:800 9px var(--fb);letter-spacing:.1em"});
const cells={};RK.forEach((r,k)=>{const key=r[1]+"-"+r[2];(cells[key]=cells[key]||[]).push(k)});const pos=[];Object.values(cells).forEach(ks=>ks.forEach((k,j)=>{pos[k]=[X(RK[k][1])+(j-(ks.length-1)/2)*16,Y(RK[k][2])]}));
const bub=RK.map((r,k)=>{const[x,y]=pos[k],g=S("g",{"data-a":"pop",style:`--d:${5+(6-k)*.3};transform-box:fill-box;transform-origin:center;cursor:pointer`},s);if(r[4])S("circle",{cx:x,cy:y,r:12,fill:"rgba(247,140,22,.35)",class:"pulse",style:`animation-delay:${k*.3}s`},g);S("circle",{cx:x,cy:y,r:8.5,fill:sv(r[1]*r[2]),stroke:"#fff","stroke-width":1.5},g);T(g,x,y+3,"R"+(k+1),{"text-anchor":"middle",fill:"#fff",style:"font:800 7.5px var(--fb)"});tip(g,`R${k+1} · ${r[0]}`,`P${r[1]} × I${r[2]} · ${r[3]}`);g.addEventListener("click",e=>{e.stopPropagation();pick(k)});return g});
const items=RK.map((r,k)=>{const b=H("div",{class:"rkl","data-a":"left",style:`--d:${6+k*.25};padding:4px 8px;grid-template-columns:24px 1fr;gap:7px`},$("riskList"));b.innerHTML=`<span class="id" style="width:22px;height:22px;font-size:9px;background:${sv(r[1]*r[2])}">R${k+1}</span><div><b style="font-size:11.5px">${r[0]}</b><span style="font-size:10.5px;color:#35516A">→ ${r[3]}</span></div>`;b.addEventListener("click",e=>{e.stopPropagation();pick(k)});return b});
function pick(k){items.forEach((b,j)=>b.classList.toggle("sel",j===k));bub.forEach((g,j)=>g.style.opacity=j===k?1:.35)}
FXR.add(sl,{play(){bub.forEach(g=>g.style.opacity=1);items.forEach(b=>b.classList.remove("sel"))},stop(){}})})();

/* ---------- 4 · MÉTODO ADKAR ---------- */
(function(){const sl=SL("Método ADKAR");
const A=[["A","Consciência","#002B49","Por que mudar?",["Narrativa do patrocinador: por que o ONS investe no AXON","Custo do legado em tempo, risco e dependência de pessoas","Roadshow com demonstrações reais"],"pulso de consciência por gerência"],["D","Desejo","#33556D","O que eu ganho com isso?",["“O que muda para mim” por categoria de uso","Transição transparente: ninguém descobre por boato","Multiplicadores e histórias de colegas"],"adesão voluntária ao piloto"],["K","Conhecimento","#5E8AB4","Como eu faço?",["Trilhas por perfil","Manual amigável e vídeos curtos","Ambiente de prática com estudos-exemplo"],"trilha concluída por perfil"],["A","Habilidade","#F78C16","Consigo fazer no dia a dia?",["Prática assistida em rodadas reais","Plantões e multiplicadores na onda","Rodada paralela até a paridade"],"1ª rodada sozinho no cenário crítico"],["R","Reforço","#1F3263","Isso veio para ficar?",["Reconhecimento e “você pediu, fizemos”","Legado congelado, sem caminho de volta","Indicadores no ritual da gerência"],"uso sustentado em 30, 60 e 90 dias"]];
const box=$("adkar");const els=A.map(([L,n,c,q,li,ev],i)=>{const b=H("div",{class:"ak","data-fx-node":"a"+i,"data-a":"pop",style:`--d:${4+i*.5};min-height:276px`},box);b.innerHTML=`<div class="hd2" style="background:${c};padding:8px 12px"><span class="L" style="font-size:42px">${L}</span><span class="nm">${n}<small>estágio ${i+1} de 5</small></span></div><div class="bd2" style="padding:8px 12px 10px"><div class="q">${q}</div><ul style="margin-top:4px">${li.map(x=>`<li style="font-size:11.5px">${x}</li>`).join("")}</ul><div class="ev" style="margin-top:6px">Evidência · ${ev}</div></div>`;b.addEventListener("click",e=>{e.stopPropagation();const on=b.classList.contains("sel");els.forEach(x=>{x.classList.remove("sel");x.style.opacity=""});if(!on){b.classList.add("sel");els.forEach(x=>{if(x!==b)x.style.opacity=.45})}});return b});
H("div",{class:"bob",style:"position:absolute;z-index:4;left:calc(40% - 150px);top:-12px;background:#BC0404;color:#fff;border-radius:99px;padding:4px 10px;font:800 10px var(--fb);letter-spacing:.06em;box-shadow:0 6px 16px rgba(188,4,4,.4)","data-tv":"Ponto de barreira (exemplo)","data-tl":"o primeiro estágio que falha define onde agir primeiro; medido por onda"},$("adkWrap"),"● PONTO DE BARREIRA");
FXR.add(sl,fxConnector($("adkWrap"),{edges:[["a0","a1"],["a1","a2"],["a2","a3"],["a3","a4"]],hover:false,auto:false,dim:false,stagger:300,delay:900,speed:80}));
const s=$("bridges"),Z=[[0,250,"Fim","reconhecer o que se perde","rotinas, o legado que se dominava, o status de especialista; nomear perdas e valorizar o saber","#002B49","A·D"],[250,600,"Zona neutra","convivência e aprendizado","legado e AXON lado a lado, rodada paralela, produtividade em queda temporária; suporte próximo e escuta","#5E8AB4","K·A"],[600,860,"Novo começo","a nova rotina","novos papéis, primeiras vitórias e reconhecimento; o legado sai de cena","#F78C16","R"]];
Z.forEach(([a,b,t,st,d,c,l],i)=>{S("rect",{x:a+2,y:2,width:b-a-4,height:184,rx:10,fill:i===1?"#EEF3F8":i===0?"#F4F7FA":"#FEF6EC"},s);S("rect",{x:a+2,y:2,width:5,height:184,rx:3,fill:c},s);fo(s,a+14,8,b-a-26,96,`<div style="font:800 16px/1.1 var(--fh);color:#002B49">${t} <span style="font:600 11px var(--fb);color:${c}">· ${st}</span></div><div style="font:500 11px/1.38 var(--fb);color:#35516A;margin-top:3px">${d}</div>`);S("rect",{x:(a+b)/2-22,y:158,width:44,height:20,rx:10,fill:"#122143"},s);T(s,(a+b)/2,172,l,{"text-anchor":"middle",fill:"#fff",style:"font:800 10.5px var(--fb)"})});
path("M14 120 C130 118 200 120 250 128 C330 148 420 160 470 156 C540 150 570 136 600 124 C690 100 780 92 850 88",{fill:"none",stroke:"#002B49","stroke-width":3});T(s,850,80,"engajamento e produtividade",{"text-anchor":"end",fill:"#6B7B8C",style:"font:600 10.5px var(--fb)"});
const c=$("curve"),X=z=>10+(z+3)/6*570,Y=z=>112-96*Math.exp(-z*z/2),SG=[[-3,-2,"#F78C16","Inovadores 2,5%","times do MVP"],[-2,-1,"#F9A64A","Primeiros adeptos 13,5%","multiplicadores"],[-1,0,"#5E8AB4","Maioria inicial 34%","piloto e onda 1"],[0,1,"#33556D","Maioria tardia 34%","onda 2 com paralela"],[1,3,"#1F3263","Retardatários 16%","apoio individual"]];
SG.forEach(([a,b,col,n,d],i)=>{let p=`M${X(a)} 112`;for(let z=a;z<=b+1e-9;z+=.05)p+=` L${X(z).toFixed(1)} ${Y(z).toFixed(1)}`;p+=` L${X(b)} 112 Z`;const g=S("g",{"data-a":"fade",style:`--d:${9+i*.5}`},c);tip(path(p,{fill:col,stroke:"#fff","stroke-width":1.5},g),n,d);const cx=X(Math.max(a,-2.8)+(Math.min(b,2.7)-Math.max(a,-2.8))/2),yy=i%2?158:132;T(g,cx,yy,n,{"text-anchor":"middle",fill:"#002B49",style:"font:800 10.5px var(--fb)"});T(g,cx,yy+13,d,{"text-anchor":"middle",fill:"#6B7B8C",style:"font:600 10px var(--fb)"})});
S("line",{x1:X(-1),y1:6,x2:X(-1),y2:116,stroke:"#BC0404","stroke-width":2,"stroke-dasharray":"5 4"},c);const cg=S("g",null,c);S("rect",{x:X(-1)-34,y:0,width:68,height:16,rx:8,fill:"#BC0404"},cg);T(cg,X(-1),12,"o salto",{"text-anchor":"middle",fill:"#fff",style:"font:800 9.5px var(--fb);letter-spacing:.08em;text-transform:uppercase"});tip(cg,"O salto crítico","a maioria só adota quando vê colegas parecidos com ela usando, com resultado confiável e suporte por perto");
T(c,585,14,"percentuais de referência do modelo, não do ONS",{"text-anchor":"end",fill:"#98A6B3",style:"font:500 9.5px var(--fb)"})})();

/* ---------- 5 · COMO FAREMOS ---------- */
(function(){const sl=SL("Como faremos");
const M=[["01","search","#5E8AB4","Entender","raio-x antes de agir",["Conversas com gerentes, mantenedores e times do MVP","Rodadas observadas ao lado de quem roda"],["Raio-x e mapa de impactos","Inventário de rotinas e legados"],"A"],["02","megaphone","#1F3263","Engajar","fazer o AXON ser desejado",["Coalizão de patrocinadores e roadshow “AXON ao vivo”","Histórias de colegas e vitrine com indicadores"],["Narrativa e kit do líder","Marca e vitrine AXON"],"AD"],["03","cap","#33556D","Capacitar","até a 1ª rodada sozinho",["Turmas com estudos reais da gerência","Plantões, multiplicadores e selo por nível"],["Trilhas por perfil","Manual amigável"],"KH"],["04","layers","#002B49","Migrar","rotina por rotina, com paridade",["Fila de ondas por valor e prontidão","Rodada paralela com aceite e portões por legado"],["Plano de ondas e go/no-go","Plano de desnutrição"],"HR"],["05","refresh","#F78C16","Sustentar","o novo fica, o antigo não volta",["Escuta que vira backlog do produto","Vigilância da recaída ao legado"],["Rituais de reforço","Repasse ao ONS"],"R"]];
const el=$("moves");const cards=M.map(([n,ic,c,t,v,cm,e,a],i)=>{const x=H("div",{class:"fr-card","data-fx-node":"m"+i,"data-fx-step":String(i+1),style:`--c:${c};padding:0;overflow:hidden;display:flex;flex-direction:column;min-height:262px;border-top:0;cursor:pointer`},el);
x.innerHTML=`<div style="background:${c};color:#fff;padding:9px 13px;display:flex;align-items:center;gap:10px"><span style="font:800 26px/1 var(--fh);opacity:.55">${n}</span><div style="flex:1"><div style="font:800 22px/1 var(--fh)">${t}</div><div style="font:600 11px var(--fb);opacity:.9;margin-top:2px">${v}</div></div><span style="width:34px;height:34px;border-radius:50%;background:rgba(255,255,255,.18);display:grid;place-items:center">${icon(ic,"#fff",18)}</span></div>
<div style="padding:8px 12px 9px;display:flex;flex-direction:column;gap:3px;flex:1"><div style="font:800 9.5px var(--fb);letter-spacing:.12em;color:#5E8AB4;text-transform:uppercase">Como fazemos</div><ul style="padding-left:15px;margin:0">${cm.map(z=>`<li style="font-size:11.5px;line-height:1.35;color:#35516A;margin-top:2px">${z}</li>`).join("")}</ul><div style="margin-top:4px;font:800 9.5px var(--fb);letter-spacing:.12em;color:#B35F00;text-transform:uppercase">Entregamos</div><ul style="padding-left:15px;margin:0">${e.map(z=>`<li style="font-size:11.5px;line-height:1.35;color:#002B49;font-weight:600;margin-top:2px">${z}</li>`).join("")}</ul><div style="margin-top:auto;display:flex;gap:4px;align-items:center;padding-top:5px;border-top:1px solid var(--line2)"><span class="mini" style="font-weight:700;margin-right:4px">ADKAR</span>${[...a].map(adkChip).join("")}</div></div>`;return x});
FXR.add(sl,fxConnector(el,{edges:[["m0","m1"],["m1","m2"],["m2","m3"],["m3","m4"]],hover:false,auto:false,dim:false,delay:300,stagger:250}));
const s=$("threads"),W=1508,cw=(W-4*22)/5,cx=i=>i*(cw+22)+cw/2,TH=[["Fio · Pessoas","#F78C16",["quem é impactado e como","conversa antes do anúncio","trilha ou papel novo","caminho em prática","destino consolidado"]],["Fio · Medição","#33556D",["pulso de partida","pulso de confiança","1ª rodada sozinho","uso regular e recaída","horas devolvidas"]]],nodes=[[],[]];
TH.forEach(([n,c,L],k)=>{const y=16+k*52;path(`M0 ${y} H${W}`,{stroke:c,"stroke-width":5,"stroke-linecap":"round",fill:"none",class:"dr",pathLength:1,style:`--d:${7+k};--dur:1.8s`,id:"thr"+k},s);const g=S("g",null,s);S("rect",{x:0,y:y-12,width:118,height:24,rx:12,fill:c},g);T(g,59,y+4,n.toUpperCase(),{"text-anchor":"middle",fill:"#fff",style:"font:800 10px var(--fb);letter-spacing:.08em"});
for(let q=0;q<3;q++){const d=S("circle",{r:4,fill:"#fff",stroke:c,"stroke-width":2},s);const am=S("animateMotion",{dur:"7s",begin:(q*2.3)+"s",repeatCount:"indefinite"},d);S("mpath",{href:"#thr"+k},am)}
L.forEach((l,i)=>{const x=Math.max(cx(i),170),d=S("g",{"data-a":"pop",style:`--d:${8+k+i*.3};transform-box:fill-box;transform-origin:center`},s);S("circle",{cx:x,cy:y,r:8,fill:"#fff",stroke:c,"stroke-width":4},d);T(d,x,y+25,l,{"text-anchor":"middle",fill:"#002B49",style:"font:700 12px var(--fb)"});nodes[k].push(d);tip(d,`${n} · ${M[i][3]}`,l)})});
let cur=-1;function hi(i){cur=i;nodes.forEach(arr=>arr.forEach((d,j)=>{d.style.opacity=i<0||j===i?1:.22;d.querySelector("circle").setAttribute("r",j===i?12:8)}));cards.forEach((c,j)=>c.style.opacity=i<0||j===i?1:.45)}
cards.forEach((c,i)=>c.addEventListener("click",e=>{e.stopPropagation();hi(cur===i?-1:i)}));
const sp=fxSpotlight($("movesScene"),{auto:false,dim:.5,pad:8,delay:900,steps:cards});let tm=0;
FXR.add(sl,{play(){hi(-1);sp.play();let k=0;clearInterval(tm);tm=setInterval(()=>{k++;if(k<5)sp.focus(cards[k]);else{clearInterval(tm);sp.clear()}},1200)},stop(){clearInterval(tm);sp.stop();sp.clear()}});
chev($("gates5"),[["1","Mapear","","","#5E8AB4"],["2","Espelhar","","","#33556D"],["3","Transferir","","","#F78C16"],["4","Congelar","","","#1F3263"],["5","Desligar","","","#002B49"]]);[...$("gates5").children].forEach((d,i)=>{d.style.padding=i?"7px 18px 7px 22px":"7px 18px 7px 12px";tip(d,["Mapear · inventário aceito pelo dono do legado","Espelhar · rodada paralela dentro da tolerância","Transferir · AXON vira fonte oficial; usuários aprovados","Congelar · somente leitura, ciclos sem incidente","Desligar · aceite do dono e da TI"][i],"portão de desnutrição")});
[["1","Requalificar no AXON","quem executa passa a preparar"],["2","Realocar em estudos e análises","tempo para o que hoje não cabe"],["3","Assumir papéis novos","multiplicador, guardião, dono de estudo"],["4","Apoiar outras demandas","frentes com falta de braço"],["5","Decisão de quadro, só no fim","com evidência, pela liderança e RH"]].forEach(([n,t,d],i)=>{const w=100-i*8;const x=H("div",{"data-a":"left",style:`--d:${10+i*.3};width:${w}%;display:flex;align-items:center;gap:8px;border-radius:6px;padding:3px 9px;background:${i<4?["#002B49","#33556D","#5E8AB4","#8FAAC8"][i]:"#fff"};${i===4?"border:1.5px dashed #BC0404;":""}color:${i<4?"#fff":"#BC0404"}`},$("ladderL"));H("b",{style:`font:800 15px var(--fh);color:${i<4?"#F9A64A":"#BC0404"}`},x,n);H("span",{style:"font:700 11.5px var(--fb)"},x,t);H("span",{style:`font:500 10px var(--fb);opacity:.85;margin-left:auto;text-align:right;color:${i<4?"#DDEAF5":"#6B7B8C"}`},x,d)});
[["Explorar","#9DBBD9"],["Executar","#5E8AB4"],["Preparar","#33556D"],["Construir","#002B49"],["Liderar","#F78C16"]].forEach(([t,c],i)=>H("div",{"data-a":"grow",style:`--d:${10+i*.3};flex:1;height:${34+i*8}px;align-self:flex-end;border-radius:6px 6px 0 0;background:${c};color:${i?"#fff":"#002B49"};font:800 12px var(--fh);display:flex;align-items:flex-end;padding:4px 6px;transform-origin:bottom`},$("trailM"),t));$("trailM").style.alignItems="flex-end";
["Manual: O AXON em 5 min","Minha primeira rodada","Onde está o que eu usava?","Quanto custa minha rodada?","Deu erro: e agora?","E o meu trabalho?"].forEach((t,i)=>H("span",{class:"chip2","data-a":"pop",style:`--d:${12+i*.2};font-size:10.5px;padding:4px 8px;${i===5?"background:#FEF1E2;color:#8A4A05":""}`},$("tocM"),t))})();

/* ---------- 6 · ROADMAP E RESULTADOS ---------- */
(function(){const sl=SL("Roadmap e resultados");chev($("rmPh"),PHASES);const ph=[...$("rmPh").children],MAP=[0,1,2,3,3,4];
FXR.add(sl,gantt2($("gantt"),[["Entender","#5E8AB4",[[0,1.5,"Raio-x por gerência"],[2.5,6,"Pulsos antes de cada onda",1]]],["Engajar","#1F3263",[[.5,1.5,"Narrativa e coalizão"],[1.5,3,"Marca e vitrine AXON"],[3,6,"Lançamentos por gerência",1]]],["Capacitar","#33556D",[[1,2.5,"Trilhas e manual amigável"],[2.5,3.5,"Turma piloto"],[3.5,5.5,"Turmas por onda"]]],["Migrar","#002B49",[[1,2,"Fila de ondas"],[2,3.5,"Piloto + paralela"],[3.5,4.5,"Onda 1"],[4.5,5.5,"Onda 2"],[5.5,6,"Desligar"]]],["Sustentar","#5E8AB4",[[2,5.5,"Escuta → backlog → retorno",1],[5.5,6,"Repasse"]]],["Fio · Pessoas","#F78C16",[[.5,2,"Quem é impactado"],[2,3.5,"Conversas e caminhos"],[3.5,6,"Caminhos em prática",1]]],["Fio · Medição","#C96A05",[[.5,1.5,"Pulso de partida"],[1.5,2.5,"Funil no ar"],[2.5,6,"Funil, recaída e horas devolvidas por onda",1]]]],
{lab:170,rh:34,top:26,ms:[[2,"Go do piloto"],[3.5,"Go onda 1"],[4.5,"Go onda 2"],[6,"Repasse ao ONS"]],dur:5200,onMonth:m=>ph.forEach((p,k)=>p.classList.toggle("lit",m>0&&MAP[m-1]===k))}));
[["cpu","Técnica",["Container documentado","Paridade aceita","Acesso e orçamento liberados"],"#002B49"],["people","Pessoas",["Pulso acima do critério","Trilha e multiplicador","Caminho combinado"],"#F78C16"],["calendar","Rotina",["Fora de prazo crítico","Guardião nomeado","Patrocinador presente"],"#5E8AB4"]].forEach(([ic,t,L,c],i)=>{const x=H("div",{"data-a":"up",style:`--d:${12+i*.3};background:#fff;border:1px solid var(--line);border-top:4px solid ${c};border-radius:10px;padding:6px 10px`},$("rmGates"));x.innerHTML=`<div style="display:flex;align-items:center;gap:7px"><span style="width:22px;height:22px;border-radius:50%;background:${c};display:grid;place-items:center">${icon(ic,"#fff",12)}</span><b style="font:800 14px var(--fh);color:#002B49">${t}</b></div>${L.map(z=>`<div style="display:grid;grid-template-columns:14px 1fr;gap:5px;margin-top:3px;font:600 11px/1.3 var(--fb);color:#35516A">${icon("check",c,12)}<span>${z}</span></div>`).join("")}`});
[["5 de 5","gerências com rotinas no AXON","#002B49"],["0","rodadas no legado após o go","#BC0404"],["100%","impactados com caminho combinado","#F78C16"],["Fila","de legados congelada ou desligada","#33556D"]].forEach(([v,l,c],i)=>{const x=H("div",{class:"fx-sh-card fx-sh-card--light","data-a":"up",style:`--d:${13+i*.3};background:#fff;border:1px solid var(--line);border-left:5px solid ${c};border-radius:10px;padding:5px 10px`},$("res"));H("b",{style:`display:block;font:800 26px/1 var(--fh);color:${c}`},x,v);H("span",{style:"font:600 10.5px/1.3 var(--fb);color:#35516A"},x,l)});
["Raio-x por gerência e mapa de impactos","Narrativa, marca e vitrine AXON","Trilhas, manual amigável e multiplicadores","Ondas, go/no-go e desnutrição dos legados","Caminhos das pessoas e novos papéis","Painel de adoção e repasse ao ONS"].forEach((t,i)=>H("div",{style:"display:grid;grid-template-columns:16px 1fr;gap:6px;font:600 11.5px/1.3 var(--fb);color:#DDEAF5",html:icon("check","#F9A64A",14)+`<span>${t}</span>`},$("deliv"),null));
FXR.add(sl,fxGlowLightSweep($("nextGlow"),{interval:6000,delay:5800,entrance:false}));FXR.add(sl,fxShimmerSweep($("res"),{delay:5600,stagger:200}))})();
