/* ===== Proposta 1 · Transformation Office (PMO + GMO) · escala do AXON · 6 páginas ===== */
window.DECK={brandSub:"ONS · AXON · Transformation Office",rightLabel:"Proposta 1 · TMO",footLabel:"AXON · ESCALA · TMO",
parts:[["Capa","Contexto"],["Contexto","1 · Contexto"],["Método","2 · Método"],["Plano de trabalho","3 · Plano de trabalho"]],
chapters:{"1 · Contexto":["01","Contexto","O AXON funciona. O desafio agora é escalar de 2 times para 5 gerências, com coordenação."],"2 · Método":["02","Método","Transformation Office A&M: quatro pilares, governança em três níveis e disciplina de execução."],"3 · Plano de trabalho":["03","Plano de trabalho","Seis meses, sete frentes e um baseline: da mobilização ao TMO operado pelo ONS."]},
zoom:["pipe","pyr","gantt","dash"],
descDefault:"Proposta de Transformation Office (PMO + Gestão de Mudanças) para escalar o AXON.",
desc:{"Capa":"Capa em Particle System (efeito 30 do Guia DTS): a rede viva representa modelos, pessoas e gerências conectados pelo AXON. Mova o cursor para afastar as partículas e clique para emitir um pulso.",
"O AXON e o desafio de escala":"Contexto. A arquitetura do AXON, do container ao resultado (clique numa etapa: o foco destaca e a legenda mostra o que a escala exige dela); os serviços transversais; o salto do MVP para as cinco gerências; e as quatro pressões que a escala cria quando ninguém coordena.",
"Método A&M de TMO":"Método 1 de 2. As sete atividades do Transformation Office e os quatro pilares da abordagem A&M (três de PMO e um de GMO), cada um traduzido para o AXON, com os componentes do TO e os imperativos que guiam a execução.",
"Como o TMO opera":"Método 2 de 2. Governança em três níveis (comitê executivo, comitê gestor e gestão do TO), com quem participa, o que decide e o sentido de escalonamento; gestão de riscos em cinco passos, com exemplos ilustrativos do AXON; e as ferramentas do TMO.",
"Plano de trabalho":"Plano de trabalho. Roadmap relativo de seis meses em cinco fases: o cursor percorre os meses, acende a fase e os marcos de go. Sete frentes num único baseline e a gestão da mudança aplicada à governança do programa.",
"Resultados e entregáveis":"Resultados. Antes × depois em seis dimensões (a máscara revela o mês 6), a maquete do painel do TMO com números ilustrativos (o destaque alterna as leituras) e os entregáveis do programa."}};

const SL=t=>[...document.querySelectorAll(".slide")].find(s=>s.dataset.t===t);
document.querySelectorAll(".slide").forEach(s=>{if(s.querySelector("[data-fx-type]"))FXR.add(s,fxTypography(s,{delay:220,gap:120}));if(s.querySelector("[data-fx-reveal]"))FXR.add(s,fxMaskReveal(s,{stagger:120,delay:600}))});

/* ---------- CAPA ---------- */
(function(){const sl=SL("Capa");FXR.add(sl,fxCoverParticles(sl,{count:140}));FXR.add(sl,fxShimmerSweep(sl,{delay:1100,every:6500}))})();

/* ---------- 1 · CONTEXTO ---------- */
(function(){const sl=SL("O AXON e o desafio de escala");
const P=[["box","Container","código + contrato de E/S","o modelo é empacotado com a documentação dos jobs, das entradas e das saídas; build, logs e versões monitorados","fila de containers por gerência, com padrão e dono"],["grid","Catálogo de jobs","blocos gerados pela doc","a documentação do container gera os blocos do catálogo; o contrato garante que só roda o que bate com o código","curadoria e regras de publicação no catálogo"],["flow","Pipeline","DAG resolvido por E/S","fluxos montados por arrastar e conectar; a ordem de execução é resolvida pelas entradas e saídas de cada job","padrões de fluxo reaproveitados entre gerências"],["sliders","Estudo","UI dinâmica de parâmetros","faixa, número, seleção, data, texto e tabela, salvos por estudo e duplicáveis","paridade com o legado validada antes do go"],["cloud","Execução","nuvem, fan-out e orçamento","máquina e escala escolhidas por rodada, milhares de casos em paralelo, custo previsto e orçamento por time","alçada de custo e orçamento por gerência"],["out","Resultado","catálogo, download, Axon Drive","saída para o catálogo corporativo, download ou Axon Drive com os projetos permitidos","rastreabilidade e acesso por projeto"]];
const pp=$("pipe");P.forEach(([ic,t,s2,d,pe],i)=>{const b=H("div",{class:"st","data-fx-node":"p"+i,"data-fx-step":String(i+1),"data-fx-caption":`${i+1} · ${t}: ${d}. Na escala: ${pe}.`,style:"min-height:124px;gap:6px"},pp);b.innerHTML=`<span class="n">0${i+1}</span><div style="display:flex;align-items:center;gap:10px"><div class="ic" style="flex:none">${icon(ic,"#fff",20)}</div><div><b style="display:block;margin:0">${t}</b><i>${s2}</i></div></div><div class="pe">Na escala: ${pe}</div>`});
$("pipeCap").textContent=`1 · Container: ${P[0][3]}. Na escala: ${P[0][4]}.`;
FXR.add(sl,fxConnector(pp,{edges:[["p0","p1"],["p1","p2"],["p2","p3"],["p3","p4"],["p4","p5"]],stagger:200,hover:false,auto:false,dim:false,speed:90}));
const sp=fxSpotlight(pp,{caption:$("pipeCap"),auto:false,dim:.5,pad:6,delay:2400});FXR.add(sl,{play(){sp.play()},stop(){sp.stop();sp.clear()}});
pp.querySelectorAll(".st").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();pp.querySelectorAll(".st").forEach(x=>x.classList.toggle("sel",x===b));sp.focus(b)}));
const tr=$("trans");H("div",{style:"display:flex;align-items:center;font:800 11px var(--fb);letter-spacing:.12em;text-transform:uppercase;color:#5E8AB4;padding-right:4px"},tr,"Transversal");
[["ai","MCP e agentes","Caixa de entrada: processamento e retorno no mesmo canal"],["bug","Suporte assistido","bug com tela, versão e sessão; correção por IA com PR aprovado por humano"],["coin","Custo visível","previsto por rodada, orçamento mensal e anual por time"],["drive","Axon Drive","resultados e arquivos com acesso por projeto"]].forEach(([ic,t,d],i)=>{const x=H("div",{"data-a":"up",style:`--d:${4+i*.25};display:grid;grid-template-columns:28px 1fr;gap:8px;align-items:center;background:#F4F7FA;border:1px solid var(--line2);border-radius:9px;padding:5px 10px`},tr);x.innerHTML=`<span style="width:28px;height:28px;border-radius:50%;background:#DFE8F0;display:grid;place-items:center">${icon(ic,"#1F3263",15)}</span><div><b style="display:block;font:800 13px/1.1 var(--fh);color:#002B49">${t}</b><span style="font:500 10.5px/1.3 var(--fb);color:#35516A">${d}</span></div>`});
/* do MVP à escala: 2 times → 5 gerências */
const s=$("scaleArt"),df=S("defs",null,s),gl=S("filter",{id:"sgl",x:"-50%",y:"-50%",width:"200%",height:"200%"},df);S("feGaussianBlur",{stdDeviation:"3",result:"b"},gl);const fm=S("feMerge",null,gl);S("feMergeNode",{in:"b"},fm);S("feMergeNode",{in:"SourceGraphic"},fm);
const A=[[46,38],[46,78]],B=[[330,14],[392,30],[420,62],[392,94],[330,104]],G=["PE","PR","PL","OS","PD"];
T(s,46,108,"MVP · 2 times",{"text-anchor":"middle",fill:"#9DB7CE",style:"font:700 10.5px var(--fb)"});
const hub=[200,58];S("circle",{cx:hub[0],cy:hub[1],r:26,fill:"#1F3263",stroke:"#F78C16","stroke-width":2,filter:"url(#sgl)"},s);T(s,hub[0],63,"AXON",{"text-anchor":"middle",fill:"#fff",style:"font:800 13px var(--fh);letter-spacing:.06em"});
A.forEach(([x,y],i)=>{const p=path(`M${x+12} ${y} C120 ${y} 140 58 ${hub[0]-26} 58`,{fill:"none",stroke:"#5E8AB4","stroke-width":2,id:"sa"+i},s);S("circle",{cx:x,cy:y,r:12,fill:"#5E8AB4"},s);T(s,x,y+4,"T"+(i+1),{"text-anchor":"middle",fill:"#fff",style:"font:800 10px var(--fb)"})});
B.forEach(([x,y],i)=>{const g=S("g",{"data-a":"pop",style:`--d:${5+i*.3};transform-box:fill-box;transform-origin:center`},s);path(`M${hub[0]+26} 58 C270 58 ${x-50} ${y} ${x-14} ${y}`,{fill:"none",stroke:"#F78C16","stroke-width":2,"stroke-dasharray":"4 4",opacity:.8,id:"sb"+i},g);S("circle",{cx:x,cy:y,r:13,fill:"#F78C16",filter:"url(#sgl)"},g);T(g,x,y+4,G[i],{"text-anchor":"middle",fill:"#0E1C39",style:"font:800 10.5px var(--fb)"});
const d=S("circle",{r:3,fill:"#fff"},s);const am=S("animateMotion",{dur:"2.6s",begin:(i*.4)+"s",repeatCount:"indefinite"},d);S("mpath",{href:"#sb"+i},am)});
[["2 → 5","times do MVP → gerências"],["~150","usuários potenciais"],["176 mil","casos em ~2h (antes ~3 dias)"]].forEach(([v,l],i)=>{const x=H("div",{style:"border-left:3px solid #F78C16;padding-left:9px"},$("scaleNums"));H("b",{style:"display:block;font:800 28px/1 var(--fh);color:#fff"},x,v);H("span",{style:"font:600 11px/1.3 var(--fb);color:#C8DBEB"},x,l)});
FXR.add(sl,fxGlowLightSweep($("scaleGlow"),{interval:6500,delay:2600,entrance:false}));
[["inbox","Demanda","#5E8AB4","Pedidos de containers, melhorias e bugs de 5 gerências chegam a um time de produto enxuto.","fila sem critério: leva quem pede mais alto"],["layers","Legados","#1F3263","Sistemas, planilhas e scripts paralelos convivem com o AXON até a paridade ser provada.","convivência dupla sem data para acabar"],["people","Pessoas","#F78C16","Rotinas, papéis e receios mudam em cada gerência, em ritmos diferentes.","adoção de fachada e recaída ao legado"],["coin","Valor e custo","#33556D","Custo de nuvem por rodada e horas devolvidas precisam aparecer para a liderança.","investimento sem prova de retorno"]].forEach(([ic,t,c,d,r],i)=>{const x=H("div",{class:"fx-sh-card fx-sh-card--light","data-a":"up",style:`--d:${6+i*.3};background:#fff;border:1px solid var(--line);border-top:4px solid ${c};border-radius:12px;padding:10px 12px;display:flex;flex-direction:column;gap:6px`},$("press"));x.innerHTML=`<div style="display:flex;align-items:center;gap:8px"><span style="width:32px;height:32px;border-radius:50%;background:${c};display:grid;place-items:center">${icon(ic,"#fff",17)}</span><b style="font:800 18px var(--fh);color:#002B49">${t}</b></div><div style="font:500 12px/1.4 var(--fb);color:#35516A">${d}</div><div style="margin-top:auto;font:700 11px/1.35 var(--fb);color:#BC0404;background:#FBEDEC;border-radius:6px;padding:5px 8px">Sem TMO: ${r}</div>`;tip(x,t,r)});
FXR.add(sl,fxShimmerSweep($("press"),{delay:3800,stagger:220}))})();

/* ---------- 2 · MÉTODO A&M DE TMO ---------- */
(function(){const sl=SL("Método A&M de TMO");
const C=[["calendar","Planejamento","plano integrado por ondas"],["target","Definição de métricas","uso, paridade, custo e horas"],["megaphone","Engajamento","patrocinadores e gerências"],["cap","Capacitação","líderes, multiplicadores e times"],["eye","Acompanhamento","status semanal e riscos"],["chat","Comunicação","narrativa e protocolos únicos"],["chart","Report de resultados","valor para a liderança"]];
const ch=$("toChain");C.forEach(([ic,t,d],i)=>{const x=H("div",{class:"tonode","data-fx-node":"c"+i,"data-a":"pop",style:`--d:${3+i*.25}`},ch);x.innerHTML=`<span class="ci">${icon(ic,"#fff",22)}</span><b>${t}</b><span>${d}</span>`;tip(x,t,d)});
FXR.add(sl,fxConnector(ch,{edges:C.slice(1).map((_,i)=>["c"+i,"c"+(i+1)]),stagger:180,hover:false,auto:false,dim:false,speed:110,delay:600}));
const PL=[["target","#002B49","Estratégia e Metodologia","a base da cultura de gestão","Metodologia é a base para que uma cultura de gestão de projetos se instale.",["Abordagem ajustada ao ritmo do ONS e ao ciclo de releases do AXON","Priorização de entregas viáveis por valor e prontidão da gerência","Planejamento incremental por ondas, com a incerteza medida"],"Entrega · plano integrado e critérios de priorização"],
["shield","#1F3263","Governança e Estrutura","pessoas certas, rituais formais","Rituais formais, responsáveis e canais de reporte claros.",["Comitês com alçada para escopo, orçamento de nuvem e legados","Dono do produto, TI, segurança e gerências com papéis definidos","Decisões técnicas, operacionais e de negócio integradas"],"Entrega · estrutura de comitês e matriz de alçadas"],
["chart","#5E8AB4","Ferramentas e Indicadores","gestão e comunicação eficientes","Ferramentas, artefatos e indicadores são a chave da visibilidade.",["Painel de marcos, entregas, uso e custo por gerência","Templates únicos de status, decisão e go/no-go","Rastreabilidade de cada container, onda e legado"],"Entrega · painel do TMO e baseline único"],
["people","#F78C16","Gestão da Mudança","time capacitado e engajado","Pessoas engajadas buscam o melhor resultado do projeto.",["Comunicação estruturada sobre andamento e impactos","Apoio nas fricções entre produto, gerências e legados","Narrativa única: o AXON como plataforma do ONS"],"Entrega · plano de stakeholders e comunicação"]];
const cards=PL.map(([ic,c,t,s2,am,L,e],i)=>{const x=H("div",{class:"pil2","data-a":"up",style:`--d:${5+i*.3};border-color:${i===3?"#F5B570":"var(--line)"}`},$("pil"));x.innerHTML=`<div class="hd" style="background:${c}"><span style="width:34px;height:34px;border-radius:50%;background:rgba(255,255,255,.18);display:grid;place-items:center;flex:none">${icon(ic,"#fff",18)}</span><div><b>${t}</b><small>${s2}</small></div></div><div class="am">${am}</div><div style="padding:6px 12px 0;font:800 9.5px var(--fb);letter-spacing:.12em;color:${i===3?"#B35F00":"#5E8AB4"};text-transform:uppercase">No AXON</div><ul>${L.map(z=>`<li>${z}</li>`).join("")}</ul><div class="ent">${e}</div>`;return x});
const sp=fxSpotlight($("pilScene"),{auto:false,dim:.45,pad:6,delay:900,steps:cards});let tm=0;
FXR.add(sl,{play(){sp.play();let k=0;clearInterval(tm);tm=setTimeout(()=>{sp.focus(cards[0]);tm=setInterval(()=>{k++;if(k<4)sp.focus(cards[k]);else{clearInterval(tm);sp.clear()}},1500)},2200)},stop(){clearInterval(tm);clearTimeout(tm);sp.stop();sp.clear()}});
cards.forEach(c=>c.addEventListener("click",e=>{e.stopPropagation();clearInterval(tm);sp.focus(c)}));
[["link","Interdependências","Como evitar sobreposição e desalinhamento técnico?","impactos cruzados entre ondas, containers e legados; capacidade do time de produto"],["layers","Integração","Como ter visão única sem perder o detalhe crítico?","rituais, protocolos entre frentes e gate de validação técnica e de negócio"],["warn","Riscos","Como se antecipar aos problemas?","mapa por frente, mitigação com dono e prazo, ações preventivas"],["eye","Stakeholders e monitoramento","Como manter todos na mesma página?","fóruns técnicos, workshops de sensibilização e agentes da mudança"]].forEach(([ic,t,q,d],i)=>{const x=H("div",{"data-a":"up",style:`--d:${8+i*.25};background:#fff;border:1px solid var(--line);border-radius:10px;padding:8px 10px;border-left:4px solid #5E8AB4`},$("comp"));x.innerHTML=`<div style="display:flex;align-items:center;gap:6px">${icon(ic,"#1F3263",16)}<b style="font:800 14px/1.1 var(--fh);color:#002B49">${t}</b></div><div style="font:700 11.5px/1.3 var(--fb);color:#B35F00;margin-top:4px">${q}</div><div style="font:500 11px/1.35 var(--fb);color:#35516A;margin-top:3px">${d}</div>`;tip(x,t,d)});
["Sponsorship forte e participativo","Informação certa, decisão certa","Planejamento de capacidade","Controle de mudança de escopo","Governança permanente","Ferramenta digital de governança","Um baseline","Especialistas (SMEs)","Riscos e qualidade","Suporte à gestão da mudança","Gestão de stakeholders"].forEach((t,i)=>H("span",{class:"chip2 fx-sh-card","data-a":"pop",style:`--d:${9+i*.12};font-size:11px;padding:4px 9px;background:${i===6?"#F78C16":"rgba(255,255,255,.1)"};color:${i===6?"#0E1C39":"#DDEAF5"};border:1px solid rgba(255,255,255,.16)`},$("imp"),t));
FXR.add(sl,fxShimmerSweep($("imp"),{delay:5200,stagger:90}))})();

/* ---------- 3 · COMO O TMO OPERA ---------- */
(function(){const sl=SL("Como o TMO opera");
const s=$("pyr"),cx=196,L=[["Comitê Executivo","mensal ou bimestral","#002B49",["Acompanhar a transição e o valor do AXON","Decidir escopo, orçamento de nuvem e desligamento de legados","Aprovar ajustes de rota e tratar exceções críticas","Validar diretrizes de comunicação e mudança"],"Managing Directors, líder do TO e de change","alta liderança e gerências PE, PR, PL, OS e PD"],
["Comitê Gestor","quinzenal","#1F3263",["Acompanhar as frentes: produto, containers, ondas, legados, pessoas","Identificar riscos e interdependências técnicas","Resolver impedimentos e apoiar aprovações"],"líderes técnicos, líder do TO e de change","dono do produto AXON, TI e líderes das gerências"],
["Gestão do TO","semanal","#5E8AB4",["Monitorar cronograma, entregas e plano de riscos","Consolidar o status integrado e ativar ações de change","Facilitar conflitos e apoiar os líderes técnicos"],"equipe do TO e de change, especialistas","time do produto, líderes por frente e multiplicadores"]];
const top=6,h=176,gap=10,wT=96,wB=312;mk(s,"pyU","#F78C16");mk(s,"pyD","#1F3263");
L.forEach(([n,f,c,B,am,on],i)=>{const y=top+i*(h+gap),w0=wT+(wB-wT)*(i/3),w1=wT+(wB-wT)*((i+1)/3),g=S("g",{"data-a":"up",style:`--d:${3+i*.6}`},s);
path(`M${cx-w0/2} ${y} L${cx+w0/2} ${y} L${cx+w1/2} ${y+h} L${cx-w1/2} ${y+h} Z`,{fill:c},g);
const nm=n.split(" "),ty=i===0?y+104:y+h/2-4;T(g,cx,ty,nm[0],{"text-anchor":"middle",fill:"#fff",style:"font:800 17px var(--fh);letter-spacing:.03em"});T(g,cx,ty+18,nm.slice(1).join(" "),{"text-anchor":"middle",fill:"#fff",style:"font:800 17px var(--fh);letter-spacing:.03em"});T(g,cx,ty+38,f,{"text-anchor":"middle",fill:"#F9A64A",style:"font:700 11.5px var(--fb)"});
const ex=cx+(w0+w1)/4+4;S("line",{x1:ex,y1:y+h/2,x2:356,y2:y+h/2,stroke:"#B6C0CD","stroke-dasharray":"3 4"},g);S("circle",{cx:356,cy:y+h/2,r:4,fill:c},g);
fo(g,366,y+2,362,h-4,`<div style="font:800 15px/1.1 var(--fh);color:${c==="#5E8AB4"?"#33556D":c};letter-spacing:.02em">${n} <span style="font:700 11px var(--fb);color:#B35F00;margin-left:4px">${f}</span></div><ul style="padding-left:15px;margin:4px 0 0">${B.map(z=>`<li style="font:500 12px/1.4 var(--fb);color:#35516A">${z}</li>`).join("")}</ul><div style="display:grid;grid-template-columns:38px 1fr;gap:2px 6px;margin-top:5px;font:600 10.5px/1.3 var(--fb);color:#002B49"><span style="font-weight:800;color:#5E8AB4">A&amp;M</span><span>${am}</span><span style="font-weight:800;color:#B35F00">ONS</span><span>${on}</span></div>`,`height:${h-4}px;display:flex;flex-direction:column;justify-content:center`);tip(g,`${n} · ${f}`,B[0])});
const ya=top+8,yb=top+3*(h+gap)-gap-8;path(`M20 ${yb} L20 ${ya}`,{stroke:"#F78C16","stroke-width":3,fill:"none","marker-end":"url(#pyU)"},s);T(s,12,(ya+yb)/2,"ESCALA",{"text-anchor":"middle",fill:"#B35F00",transform:`rotate(-90 12 ${(ya+yb)/2})`,style:"font:800 10.5px var(--fb);letter-spacing:.16em"});
path(`M44 ${ya} L44 ${yb}`,{stroke:"#1F3263","stroke-width":3,fill:"none","marker-end":"url(#pyD)"},s);T(s,56,(ya+yb)/2,"DIRECIONA",{"text-anchor":"middle",fill:"#1F3263",transform:`rotate(90 56 ${(ya+yb)/2})`,style:"font:800 10.5px var(--fb);letter-spacing:.16em"});
const RK=[["1","Identificação","mapa por frente","Mapeamento dos riscos por frente (técnica, organizacional, operacional), com o produto, as gerências e a TI."],["2","Quantificação","probabilidade × impacto","Matriz de probabilidade × impacto e KPIs de alerta precoce para cada risco relevante."],["3","Mitigação","dono e prazo","Plano de resposta estruturado, com responsável, prazo e ação preventiva para evitar escalonamento."],["4","Governança","alçada certa","Cada risco sobe ao fórum certo pela criticidade: gestão do TO, comitê gestor ou comitê executivo."],["5","Monitoramento","contínuo","Processo dinâmico: o TO acompanha os alertas toda semana e revisa o mapa a cada onda."]];
chev($("rk5"),RK.map(([n,t,w],i)=>[n,t,"","",["#5E8AB4","#33556D","#1F3263","#002B49","#F78C16"][i]]));const st=[...$("rk5").children];
st.forEach((d,i)=>{d.style.padding=i?"7px 16px 7px 22px":"7px 16px 7px 12px";d.style.cursor="pointer";d.addEventListener("click",e=>{e.stopPropagation();clearInterval(rt);pick(i)})});
function pick(i){st.forEach((d,k)=>d.style.opacity=k===i?1:.45);$("rk5d").innerHTML=`<b style="color:#B35F00">${RK[i][1]} · ${RK[i][2]}</b> · ${RK[i][3]}`}let rt=0;
FXR.add(sl,{play(){let k=0;st.forEach(d=>d.style.opacity=1);$("rk5d").innerHTML=`<b style="color:#B35F00">${RK[0][1]} · ${RK[0][2]}</b> · ${RK[0][3]}`;clearInterval(rt);rt=setInterval(()=>{pick(k%5);k++;if(k>9)clearInterval(rt)},1800)},stop(){clearInterval(rt)}});
[["cpu","Tecnológicos","#5E8AB4",[["Resultado fora da paridade com o legado","a"],["Container sem contrato de E/S documentado","m"],["Custo de nuvem acima do orçamento do time","m"]]],["people","Organizacionais","#F78C16",[["Medo de perder o trabalho e resistência","a"],["Perda do saber de quem mantém o legado","a"],["Time de produto enxuto vira gargalo","m"]]],["warn","Operacionais","#BC0404",[["Convivência dupla sobrecarrega as equipes","a"],["Onda no meio de prazo crítico da operação","m"],["Acesso, segurança e dados entre projetos","m"]]]].forEach(([ic,t,c,R],i)=>{const x=H("div",{"data-a":"up",style:`--d:${8+i*.3};background:#F9FBFC;border:1px solid var(--line2);border-top:3px solid ${c};border-radius:8px;padding:6px 9px`},$("rkCat"));x.innerHTML=`<div style="display:flex;align-items:center;gap:6px">${icon(ic,c,15)}<b style="font:800 13.5px var(--fh);color:#002B49">${t}</b></div>`+R.map(([r,l])=>`<div style="display:grid;grid-template-columns:10px 1fr;gap:6px;align-items:start;margin-top:4px;font:500 11px/1.32 var(--fb);color:#35516A"><i style="width:8px;height:8px;border-radius:50%;margin-top:4px;background:${l==="a"?"#BC0404":"#F78C16"}"></i><span>${r}</span></div>`).join("")});
[["Paridade","fora da tolerância em 2 rodadas seguidas","#5E8AB4"],["Fila","pedido parado há mais de 3 semanas","#33556D"],["Uso","abaixo da meta duas semanas após o go","#F78C16"],["Custo","acima de 80% do orçamento do time","#BC0404"]].forEach(([t,d,c],i)=>{const x=H("div",{"data-a":"up",style:`--d:${10+i*.25};border:1px dashed ${c};border-radius:8px;padding:6px 9px;background:#fff`},$("rkKpi"));x.innerHTML=`<div style="display:flex;align-items:center;gap:6px">${icon("pulse",c,15)}<b style="font:800 14px var(--fh);color:#002B49">${t}</b></div><div style="font:500 11px/1.32 var(--fb);color:#35516A;margin-top:2px">${d}</div>`;tip(x,"KPI de alerta · "+t,d+" (gatilho ilustrativo)")});
[["map","Mapa de marcos","marcos e interdependências entre frentes e gerências"],["calendar","Plano integrado","entregas curtas em sprints progressivos"],["gauge","Dashboard de gestão","marcos, indicadores e alertas para remover impedimentos"],["grid","Plataforma digital","cronogramas, donos e status, com gates da ideia ao hypercare"]].forEach(([ic,t,d],i)=>{const x=H("div",{"data-fx-reveal":"",style:`background:#F4F7FA;border-radius:9px;padding:8px 10px;border-top:3px solid ${["#002B49","#1F3263","#5E8AB4","#F78C16"][i]}`},$("tools"));x.innerHTML=`<div style="display:flex;align-items:center;gap:6px"><span style="font:800 18px var(--fh);color:#C2CFDB">${i+1}</span>${icon(ic,"#1F3263",16)}</div><b style="display:block;font:800 14px/1.1 var(--fh);color:#002B49;margin-top:3px">${t}</b><span style="display:block;font:500 11px/1.33 var(--fb);color:#35516A;margin-top:2px">${d}</span>`});})();

/* ---------- 4 · PLANO DE TRABALHO ---------- */
(function(){const sl=SL("Plano de trabalho");
chev($("rmPh"),[["01","Mobilizar","mês 1","Governança no ar, baseline e leitura das frentes","#5E8AB4"],["02","Estruturar","mês 2","Plano integrado, fila priorizada e critérios de go","#33556D"],["03","Pilotar","mês 3","Gerência piloto com rodada paralela","#F78C16"],["04","Escalar","meses 4–5","Ondas, catálogo e desnutrição dos legados","#1F3263"],["05","Transferir","mês 6","TMO operado pelo ONS e lições aprendidas","#002B49"]]);
const ph=[...$("rmPh").children],MAP=[0,1,2,3,3,4];
FXR.add(sl,gantt2($("gantt"),[["Governança e PMO","#002B49",[[0,1,"Comitês, alçadas e baseline"],[1,6,"Status semanal · comitê gestor quinzenal · executivo mensal",1]]],["Produto e backlog","#33556D",[[0,1.5,"Triagem e critérios de prioridade"],[1.5,6,"Releases priorizadas por valor e por onda",1]]],["Containers e catálogo","#5E8AB4",[[.5,2,"Padrão de container e fila"],[2,3,"Containers do piloto"],[3,5.5,"Containers das ondas"]]],["Ondas de adoção","#F78C16",[[1,2,"Fila de ondas"],[2,3.5,"Piloto + paralela"],[3.5,4.5,"Onda 1"],[4.5,5.5,"Onda 2"]]],["Legados","#1F3263",[[.5,2,"Inventário e guardiões"],[2,5,"Paridade e congelamento",1],[5,6,"Desligar"]]],["Mudança e pessoas","#C96A05",[[0,1.5,"Stakeholders e narrativa"],[1.5,5.5,"Comunicação, trilhas e multiplicadores",1],[5.5,6,"Sustentar"]]],["Valor e custo","#35516A",[[.5,1.5,"Linha de base"],[1.5,6,"Uso, custo por rodada e horas devolvidas",1]]]],
{lab:180,rh:36,top:26,ms:[[.25,"Governança no ar"],[2,"Go do piloto"],[3.5,"Go onda 1"],[4.5,"Go onda 2"],[6,"TMO no ONS"]],dur:5200,onMonth:m=>ph.forEach((p,k)=>p.classList.toggle("lit",m>0&&MAP[m-1]===k))}));
[["people","Stakeholders","#002B49",["Mapa por gerência e por frente","Engajamento nos momentos críticos: go e desligamento","Resistências tratadas durante as entregas"]],["megaphone","Comunicação","#1F3263",["Templates únicos de status e decisão","Protocolos entre produto, gerências e TI: fluxo, cadência e alçada","Oficinas de alinhamento entre frentes"]],["warn","Conflitos e impedimentos","#F78C16",["Escuta ativa para detectar desalinhamento","Tratativa de conflitos técnicos e de prioridade","Escalonamento ao comitê pela criticidade"]],["refresh","Sustentação","#5E8AB4",["Apoio à adoção das rotinas definidas","Ferramentas e ritos padronizados","Lições aprendidas e repasse ao ONS"]]].forEach(([ic,t,c,L],i)=>{const x=H("div",{"data-a":"up",style:`--d:${10+i*.3};background:#fff;border:1px solid var(--line);border-left:5px solid ${c};border-radius:10px;padding:8px 12px`},$("gmGov"));x.innerHTML=`<div style="display:flex;align-items:center;gap:7px"><span style="width:28px;height:28px;border-radius:50%;background:${c};display:grid;place-items:center">${icon(ic,"#fff",15)}</span><b style="font:800 15px var(--fh);color:#002B49">${t}</b></div><ul style="padding-left:15px;margin:5px 0 0">${L.map(z=>`<li style="font:500 11.5px/1.36 var(--fb);color:#35516A">${z}</li>`).join("")}</ul>`})})();

/* ---------- 5 · RESULTADOS E ENTREGÁVEIS ---------- */
(function(){const sl=SL("Resultados e entregáveis");
const R=[["inbox","Prioridade","pela urgência de quem pede","fila única com critério de valor, onda e risco"],["box","Novos modelos","entram sem padrão nem dono","padrão de container, contrato de E/S e dono definido"],["layers","Legados","convivem sem data para sair","paridade, congelamento e desligamento com portão"],["coin","Custo de nuvem","aparece só na fatura","previsto por rodada e acompanhado por time"],["warn","Riscos","descobertos quando viram problema","mapa vivo, alerta precoce e dono por risco"],["flag","Decisões","dispersas em e-mails e reuniões","alçada clara e registro de decisão por comitê"]];
const c=$("cmpT");R.forEach(([ic,k,o,n],i)=>{const r=H("div",{style:"display:grid;grid-template-columns:160px 1fr;border-bottom:1px solid var(--line2);min-height:50px"},c);H("div",{style:"display:flex;align-items:center;gap:8px;font:800 14px/1.15 var(--fh);color:#002B49;background:#F4F7FA;padding:4px 10px",html:icon(ic,"#5E8AB4",16)+`<span>${k}</span>`},r);const v=H("div",{style:"position:relative;display:flex;align-items:center;padding:4px 12px;font:500 12.5px/1.35 var(--fb);color:#6B4A2A"},r);H("span",null,v,o);const nn=H("div",{class:"cmpN",style:`transition-delay:${i*90}ms`},v);nn.textContent=n});
const sg=$("cmpSeg");const set=v=>{sg.querySelectorAll("button").forEach(b=>b.classList.toggle("on",+b.dataset.v===v));c.classList.toggle("fut",v===1)};sg.querySelectorAll("button").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();clearTimeout(au);set(+b.dataset.v)}));
let au=0;FXR.add(sl,{play(){set(0);clearTimeout(au);au=setTimeout(()=>set(1),2800)},stop(){clearTimeout(au)}});set(0);
["Estrutura de governança, alçadas e rituais","Plano integrado e baseline único","Fila de demanda com critérios de prioridade","Painel do TMO: marcos, uso, custo e riscos","Ondas, go/no-go e desnutrição dos legados","Plano de stakeholders e comunicação","Mapa de riscos com alertas precoces","TMO repassado ao ONS, com manual de operação"].forEach((t,i)=>H("div",{"data-a":"up",style:`--d:${6+i*.15};display:grid;grid-template-columns:26px 1fr;gap:8px;align-items:center;font:600 12.5px/1.3 var(--fb);color:#DDEAF5;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);border-radius:8px;padding:8px 10px`,html:`<span style="width:26px;height:26px;border-radius:50%;background:rgba(247,140,22,.18);display:grid;place-items:center">${icon("check","#F9A64A",14)}</span><span>${t}</span>`},$("deliv")));
FXR.add(sl,fxGlowLightSweep($("delGlow"),{interval:6500,delay:4200,entrance:false}));
/* maquete do painel do TMO */
const d=$("dash");d.innerHTML=`<div style="display:flex;align-items:center;gap:12px;background:linear-gradient(100deg,#0E1C39,#1F3263);color:#fff;padding:9px 16px"><span style="font:800 17px var(--fh);letter-spacing:.06em;text-transform:uppercase">Painel do TMO · mês 4</span><span class="ilu">maquete · números ilustrativos</span><span style="margin-left:auto;font:600 11.5px var(--fb);color:#9DB7CE">Fase 04 · Escalar</span><span style="display:flex;align-items:center;gap:6px;background:rgba(247,140,22,.18);border:1px solid rgba(247,140,22,.6);border-radius:99px;padding:4px 11px;font:800 11px var(--fb);color:#F9A64A"><i class="dot d-a" style="width:11px;height:11px"></i>No prazo, com atenção</span></div>
<div style="display:grid;grid-template-columns:1fr 330px;gap:14px;padding:10px 16px 0;flex:1"><div style="display:flex;flex-direction:column"><div class="lbl" style="font-size:11.5px">Frentes</div><table id="dashT" style="width:100%;border-collapse:collapse;margin-top:4px;flex:1"></table></div>
<div style="display:flex;flex-direction:column"><div class="lbl" style="font-size:11.5px">Uso efetivo por gerência <small>clique nas barras</small></div><div class="fx-dh" id="dhUse" style="position:relative;flex:1;min-height:250px;--fx-dh-top:84px;margin-top:2px"><div class="fx-dh__plot"><div class="fx-dh__goal" style="--g:60%"><span>meta da onda</span></div></div></div></div></div>
<div style="display:grid;grid-template-columns:repeat(4,1fr) 1.3fr;gap:8px;padding:8px 16px 12px" id="dashK"></div>`;
const t=$("dashT");[["Governança e PMO","g",80,"comitê executivo"],["Produto e backlog","g",64,"release da onda 2"],["Containers e catálogo","a",52,"containers da onda 2"],["Ondas de adoção","a",48,"go da onda 2"],["Legados","r",30,"paridade do 2º legado"],["Mudança e pessoas","g",58,"turma da onda 2"],["Valor e custo","g",55,"relatório de valor"]].forEach(([n,s2,p,m],i)=>{const tr=H("tr",{"data-a":"left",style:`--d:${4+i*.15};border-bottom:1px solid #EEF2F5`},t);tr.innerHTML=`<td style="padding:9px 4px;font:700 12px var(--fb);color:#002B49">${n}</td><td style="padding:5px 4px;width:22px"><i class="dot d-${s2}" style="width:12px;height:12px"></i></td><td style="padding:5px 4px;width:150px"><div style="display:flex;align-items:center;gap:6px"><div style="flex:1;height:7px;border-radius:99px;background:#EEF2F5;overflow:hidden"><div style="height:100%;width:${p}%;background:${s2==="r"?"#BC0404":s2==="a"?"#F78C16":"#5E8AB4"}"></div></div><span style="font:700 10.5px var(--fb);color:#002B49;width:28px">${p}%</span></div></td><td style="padding:5px 4px;font:500 11px var(--fb);color:#6B7B8C">${m}</td>`});
const pl=d.querySelector(".fx-dh__plot");[["PE",78,"Onda 1 · rotina no AXON"],["PR",71,"Onda 1 · rotina no AXON"],["PL",64,"Piloto · acima da meta"],["OS",38,"Onda 2 · barreira em habilidade"],["PD",44,"Onda 2 · em convivência"]].forEach(([g,v,b])=>{const col=H("div",{class:"fx-dh__col","data-fx-item":"","data-title":`${g} · ${v}% de uso efetivo`,"data-body":b,style:`--h:${v}%;--p:${Math.max(v-14,10)}%`},pl);col.innerHTML=`<div class="fx-dh__track"><i class="fx-dh__ghost"></i><i class="fx-dh__bar"></i><em class="fx-dh__val">${v}%</em></div><span class="fx-dh__lbl">${g}</span>`});
FXR.add(sl,fxDataHighlight($("dhUse"),{insights:[{hi:[0,1,2],title:"PE, PR e PL acima da meta",body:"piloto e onda 1 com rotina no AXON",target:true},{hi:[3,4],title:"OS e PD abaixo da meta",body:"o TMO aciona plantão e multiplicador antes do go",target:true}],first:0,delay:1600,cycle:5200}));
[["86%","marcos no prazo","#002B49"],["9 dias","do pedido à entrega","#5E8AB4"],["3 de 5","gerências no AXON","#F78C16"],["420 h","devolvidas às equipes","#33556D"]].forEach(([v,l,cl],i)=>{const x=H("div",{class:"fx-sh-card fx-sh-card--light",style:`background:#F4F7FA;border-radius:9px;padding:7px 10px;border-left:4px solid ${cl}`},$("dashK"));H("div",{style:`font:800 24px/1 var(--fh);color:${cl}`},x,v);H("div",{style:"font:600 10.5px/1.3 var(--fb);color:#35516A;margin-top:2px"},x,l)});
const dz=H("div",{style:"background:#FEF1E2;border-radius:9px;padding:6px 10px"},$("dashK"));dz.innerHTML=`<div style="font:800 9.5px var(--fb);letter-spacing:.12em;color:#B35F00;text-transform:uppercase">Decisões para o comitê</div><ul style="padding-left:14px;margin:3px 0 0"><li style="font:600 10.5px/1.35 var(--fb);color:#002B49">Go da onda 2 condicionado em OS</li><li style="font:600 10.5px/1.35 var(--fb);color:#002B49">Congelar o 2º legado após paridade</li></ul>`;
FXR.add(sl,fxShimmerSweep($("dashK"),{delay:3200,stagger:180}));
$("next").innerHTML=`<span style="width:30px;height:30px;border-radius:50%;background:#F78C16;display:grid;place-items:center;flex:none">${icon("flag","#fff",16)}</span><div style="font:600 12.5px/1.35 var(--fb);color:#002B49"><b style="color:#B35F00">Próximo passo ·</b> validar escopo, patrocinador e gerência piloto; a mobilização (mês 1) começa com a governança no ar na primeira semana.</div>`})();
