/* ===== Proposta 2 · TMO (PMO + Gestão de Mudanças) · escala do AXON ===== */
window.DECK={brandSub:"ONS · AXON · Transformation Office",rightLabel:"Proposta · TMO AXON",footLabel:"AXON · TMO · DO MVP À ESCALA",
parts:[["Contexto","Contexto"],["Entendimento","1 · Entendimento","O AXON, a escala e o ponto de partida","#33556D"],["Modelo TMO","2 · Modelo TMO","Pilares, governança e papéis","#5E8AB4"],["Operação","3 · Operação","Ondas, backlog, plano, RAID, adoção e valor","#1F3263"],["Plano de trabalho","4 · Plano de trabalho","Painel, roadmap e proposta","#F78C16"]],
chapters:{"1 · Entendimento":["01","Entendimento","Uma plataforma pronta para crescer, e o que falta para crescer bem."],"2 · Modelo TMO":["02","Modelo TMO","Um escritório leve que une projetos, mudança e valor numa só governança."],"3 · Operação":["03","Operação","Como o TMO prioriza, planeja, controla riscos, conduz a adoção e prova o valor."],"4 · Plano de trabalho":["04","Plano de trabalho","Seis meses para sair do MVP e entregar um programa que escala."]},
zoom:["scale","mat","pyr","cad","rasci","wave","intake","gantt","raid","adkChain","tree","dash"],
descDefault:"Tela da proposta de TMO para a escala do AXON.",
desc:{"Capa":"Abertura da proposta de TMO: um escritório de transformação que combina PMO, gestão de mudanças e gestão de valor para levar o AXON do MVP às cinco gerências em no mínimo seis meses. O anel mostra a composição do TMO e os cinco pilares ao redor; a barra inferior, o caminho do MVP à escala.",
"Resumo executivo":"A proposta em quatro atos: o desafio de escala, o modelo de TMO com cinco pilares, a cadência de operação e o que é entregue em seis meses. Abaixo, os métodos de referência, os princípios do TMO e o roteiro.",
"AXON e o desafio de escala":"Leitura do AXON em seis etapas e o salto do MVP (dois times) para cinco gerências e cerca de 150 usuários potenciais. À direita, as quatro pressões que a escala cria e a resposta do TMO para cada uma.",
"Ponto de partida":"Leitura inicial e hipotética da maturidade de gestão em seis dimensões, numa escala de 1 a 4. Alterne entre hoje e a meta de seis meses e clique numa dimensão para ver o que muda e como o TMO chega lá.",
"O modelo TMO":"O modelo em cinco pilares sob um objetivo comum, apoiados num painel único, em rituais, em métodos (PMI, ágil e ADKAR) e nas ferramentas que o ONS já usa. Clique em cada pilar para ver o que faz, os entregáveis, o ritual e o indicador-chave.",
"Governança e rituais":"A pirâmide de governança com os fóruns e o que cada um decide, a cadência de um mês típico e a regra de controle de mudanças de escopo, prazo e orçamento.",
"Papéis e responsabilidades":"Matriz RASCI das principais decisões do programa, com um único aprovador por decisão, os perfis da equipe do TMO e os papéis do ONS.",
"Portfólio de ondas":"Matriz de priorização das rotinas candidatas por valor e prontidão (candidatos ilustrativos), os critérios de pontuação e como a matriz se traduz em piloto, onda 1 e onda 2.",
"Demandas e backlog":"Fluxo de demandas em cinco etapas, da entrada ao retorno para quem pediu, aproveitando a esteira de correção assistida que o AXON já tem; a régua de prioridade, a regra de capacidade por ciclo e o time mínimo do produto.",
"Plano integrado":"Cronograma relativo de seis meses que junta governança, produto, containers, ondas, legados, pessoas e valor. As setas laranja mostram as dependências críticas antes de cada onda.",
"RAID":"Riscos, premissas, issues e dependências iniciais do programa, cada um com dono e status, e o ciclo pelo qual o RAID é mantido vivo.",
"Mudança e adoção":"O componente de gestão de mudanças dentro do TMO: a cadeia ADKAR, cinco frentes essenciais e a regra de que cada onda só avança quando as pessoas estão prontas.",
"Valor e benefícios":"Árvore de benefícios do AXON (tempo, capacidade, custo e risco) com indicadores, a evidência inicial informada pelo time e como o valor será medido.",
"Painel do TMO":"Maquete ilustrativa do status report semanal: situação das frentes, indicadores, riscos principais e decisões pendentes para o comitê.",
"Roadmap de 6 meses":"Roadmap relativo de seis meses, sem datas: cinco fases e, mês a mês, as entregas e a decisão que o comitê executivo precisa tomar.",
"Canvas da proposta":"A proposta inteira em uma tela: por quê, o quê, como, quem, como saberemos e o que entregamos, mais as cinco fases e as premissas."}};

const PHASES=[["01","Mobilizar","mês 1","Governança, equipe, inventário e linha de base","#5E8AB4"],["02","Estruturar","mês 2","Plano integrado, intake, padrões e plano de mudança","#5E8AB4"],["03","Pilotar","mês 3","Piloto com rodada paralela e painel no ar","#F78C16"],["04","Escalar","meses 4–5","Ondas, legados e releases em ritmo","#1F3263"],["05","Transferir","mês 6","Benefícios, lições e TMO operado pelo ONS","#33556D"]];
const PIL=[["flag","#002B49","Governança e portfólio","Comitês, alçadas, priorização do portfólio de ondas e decisões registradas.",["Termo de abertura e governança","Mapa de alçadas e controle de mudanças","Log de decisões"],"Comitê executivo mensal","Decisões tomadas dentro do prazo"],
["calendar","#33556D","Planejamento e execução","Plano integrado de produto, ondas, legados e pessoas, com marcos, dependências e capacidade.",["Cronograma integrado","Plano de ondas","Mapa de dependências"],"Status do TMO semanal","Marcos entregues no prazo (%)"],
["grid","#5E8AB4","Produto e backlog","Porta única de demandas, régua de prioridade e releases comunicados, integrando a esteira de correção assistida.",["Processo de intake","Backlog priorizado","Calendário de releases"],"Comitê de produto quinzenal","Tempo do pedido à entrega"],
["people","#F78C16","Mudança e adoção","Impactos, comunicação, capacitação e transição das pessoas, com ADKAR aplicado por onda.",["Mapa de impactos","Plano de comunicação e capacitação","Plano de transição das pessoas"],"Comitê de adoção quinzenal","Utilização efetiva por gerência"],
["chart","#1F3263","Valor e benefícios","Linha de base, benefícios por rotina, custo de nuvem previsto × realizado e legados desligados.",["Árvore de benefícios","Linha de base por rotina","Relatório de valor por onda"],"Revisão de valor mensal","Horas devolvidas e custo evitado"]];
const ADK={A:["#002B49","Consciência"],D:["#33556D","Desejo"],K:["#5E8AB4","Conhecimento"],H:["#F78C16","Habilidade"],R:["#1F3263","Reforço"]};
const adkChip=l=>`<span class="adk" title="${ADK[l][1]}" style="background:${ADK[l][0]};${l==="H"?"color:#0E1C39":""}">${l==="H"?"A":l}</span>`;
function rasciTable(t,leg,RL,D){const CC={A:["#002B49","#fff"],R:["#5E8AB4","#fff"],S:["#DFE8F0","#002B49"],C:["#FDE3C4","#8A4A05"],I:["#F4F5F7","#98A6B3"]},NM={A:"Aprova",R:"Responsável",S:"Apoia",C:"Consultado",I:"Informado"};
const h=H("tr",null,t);H("th",{style:"width:270px"},h,"Decisão \\ papel");RL.forEach(r=>H("th",{style:"text-align:center;font-size:9.5px;line-height:1.2"},h,r));
D.forEach(([d,l],i)=>{const tr=H("tr",{"data-a":"up",style:`--d:${4+i*.35}`},t);H("td",{style:"font-weight:700;color:#002B49"},tr,d);[...l].forEach((c,j)=>{const td=H("td",{style:`text-align:center;font:800 18px var(--fh);background:${CC[c][0]};color:${CC[c][1]};border:2px solid #fff;padding:12px 4px`},tr,c);tip(td,`${RL[j]} · ${NM[c]}`,d)})});
Object.keys(CC).forEach(k=>H("span",{style:"display:flex;align-items:center;gap:6px",html:`<i style="display:inline-grid;place-items:center;width:20px;height:20px;border-radius:4px;background:${CC[k][0]};color:${CC[k][1]};font:800 11px var(--fb);font-style:normal">${k}</i>${NM[k]}`},leg))}

/* ---------- CAPA: órbita do TMO ---------- */
(function(){const s=$("cvArt"),cx=380,cy=360,pt=(a,r)=>[cx+r*Math.cos(a),cy+r*Math.sin(a)];const df=S("defs",null,s);const rg=S("radialGradient",{id:"cvCore"},df);S("stop",{offset:0,"stop-color":"#33556D"},rg);S("stop",{offset:1,"stop-color":"#122143"},rg);
S("circle",{cx,cy,r:290,fill:"none",stroke:"rgba(255,255,255,.07)","stroke-width":1},s);S("circle",{cx,cy,r:220,fill:"none",stroke:"rgba(255,255,255,.05)","stroke-dasharray":"2 6"},s);
const P=[["flag","Governança"],["calendar","Planejamento"],["grid","Produto e backlog"],["people","Mudança e adoção"],["chart","Valor"]];
P.forEach(([ic,t],i)=>{const a=-Math.PI/2+i*2*Math.PI/5,[x,y]=pt(a,290),[ix,iy]=pt(a,170);const ln=path(`M${ix} ${iy} L${x} ${y}`,{stroke:"rgba(157,187,217,.35)","stroke-width":1.4,id:"cvl"+i},s);
const dot=S("circle",{r:4,fill:"#F78C16"},s);const am=S("animateMotion",{dur:(2.6+i*.3)+"s",repeatCount:"indefinite",begin:(i*.4)+"s"},dot);const mp=S("mpath",null,am);mp.setAttribute("href","#cvl"+i);
const g=S("g",{class:"cv-node",style:`animation-delay:${i*.45}s`},s);S("circle",{cx:x,cy:y,r:34,fill:i===3?"#F78C16":"#5E8AB4",stroke:"#9DBBD9","stroke-width":2},g);fo(g,x-14,y-14,28,28,icon(ic,"#fff",28));T(g,x,y+(y>cy?58:-48),t,{"text-anchor":"middle",fill:"#DDEAF5",style:"font:600 13px var(--fb)"})});
const R=148,L=2*Math.PI*R,SG=[["PMO",.5,"#5E8AB4"],["GMO",.3,"#F78C16"],["Valor",.2,"#BFD0E1"]],arcs=[];let off=0;
S("circle",{cx,cy,r:R,fill:"none",stroke:"rgba(255,255,255,.08)","stroke-width":18},s);
SG.forEach(([n,p,c])=>{const a=S("circle",{cx,cy,r:R,fill:"none",stroke:c,"stroke-width":18,"stroke-dasharray":`0 ${L}`,"stroke-dashoffset":-off*L,transform:`rotate(-90 ${cx} ${cy})`},s);arcs.push([a,p]);const mid=-Math.PI/2+(off+p/2)*2*Math.PI,[x,y]=pt(mid,R+32);T(s,x,y+5,n,{"text-anchor":"middle",fill:c,style:"font:800 15px var(--fh);letter-spacing:.06em"});off+=p});
S("circle",{cx,cy,r:116,fill:"url(#cvCore)",stroke:"rgba(157,187,217,.5)","stroke-width":2},s);
T(s,cx,cy-30,"ESCRITÓRIO DE TRANSFORMAÇÃO",{"text-anchor":"middle",fill:"#9DB7CE",style:"font:700 10px var(--fb);letter-spacing:.14em"});T(s,cx,cy+24,"TMO",{"text-anchor":"middle",fill:"#fff",style:"font:800 64px var(--fh);letter-spacing:.08em"});T(s,cx,cy+52,"projetos · mudança · valor",{"text-anchor":"middle",fill:"#F78C16",style:"font:700 13px var(--fb)"});
const by=712;S("rect",{x:150,y:by-5,width:460,height:10,rx:5,fill:"rgba(255,255,255,.1)"},s);const bar=S("rect",{x:150,y:by-5,width:0,height:10,rx:5,fill:"#F78C16"},s);const hd=S("circle",{cx:150,cy:by,r:9,fill:"#fff",style:"filter:drop-shadow(0 0 8px rgba(247,140,22,.9))"},s);
T(s,140,by+5,"MVP · 2 times",{"text-anchor":"end",fill:"#C8DBEB",style:"font:700 13px var(--fb)"});T(s,620,by+5,"5 gerências",{fill:"#F9A64A",style:"font:800 13px var(--fb)"});
let raf=0;ENTER["Capa"]=()=>{cancelAnimationFrame(raf);const t0=performance.now(),D=2400,dl=500;const st=t=>{const k=clamp((t-t0-dl)/D,0,1),e=1-Math.pow(1-k,3);let acc=0;arcs.forEach(([a,p])=>{const v=clamp((e-acc)/p,0,1);a.setAttribute("stroke-dasharray",`${Math.max(0,L*p*v-6)} ${L}`);acc+=p});bar.setAttribute("width",460*e);hd.setAttribute("cx",150+460*e);if(k<1)raf=requestAnimationFrame(st)};raf=requestAnimationFrame(st)}})();

/* ---------- RESUMO ---------- */
(function(){const A=[["search","#5E8AB4","Ato 1 · O desafio","2 → 5","times no MVP → gerências","O produto nasceu com um time enxuto e já roda com dois times. Escalar multiplica demandas, legados a desligar e pessoas a preparar."],
["grid","#F78C16","Ato 2 · O modelo","5 pilares","um TMO leve","Governança, planejamento, produto e backlog, mudança e adoção, valor e benefícios, com as ferramentas que o ONS já usa."],
["calendar","#1F3263","Ato 3 · Como opera","3 cadências","semanal · quinzenal · mensal","Status e RAID toda semana, produto e adoção a cada quinzena, comitê executivo todo mês: cada decisão no fórum certo."],
["flag","#33556D","Ato 4 · O que entrega","6 meses","do MVP à escala","Plano integrado, ondas priorizadas, backlog sob controle, adoção medida e benefícios provados, com o TMO transferido ao ONS."]];
A.forEach(([ic,c,e,n,l,t],i)=>{const w=H("div",{"data-a":"stack",style:`--d:${3+i*1.1};--sx:${(1.5-i)*381}px;--r:${(i-1.5)*4}deg;position:relative;padding-top:30px`},$("acts"));const cc=H("div",{class:"card tlt",style:`border-radius:12px;border-top:4px solid ${c};padding:34px 16px 14px;height:100%;min-height:200px`},w);
const b=H("div",{style:`position:absolute;left:50%;top:0;transform:translateX(-50%);width:58px;height:58px;border-radius:50%;background:${c};display:grid;place-items:center;box-shadow:0 0 0 6px #fff,0 6px 16px rgba(14,28,57,.2);z-index:3`},w);b.innerHTML=icon(ic,"#fff",28);
H("div",{class:"eye",style:`color:${c==="#F78C16"?"#B35F00":c};margin-bottom:4px`},cc,e);H("div",{style:`font:800 44px/1 var(--fh);color:${c}`},cc,n);H("div",{class:"small",style:"font-weight:700;color:#35516A;margin:2px 0 8px"},cc,l);H("p",{style:"font-size:12.5px;line-height:1.5"},cc,t)});
const M=[["PMI · PMBOK®","governança, cronograma, riscos e controle de mudanças","#002B49"],["Práticas ágeis","backlog, ciclos quinzenais e releases","#5E8AB4"],["ADKAR · Prosci","adoção por onda e prontidão das pessoas","#F78C16"],["Gestão de benefícios","linha de base e realização de valor","#33556D"],["RAID","riscos, premissas, issues e dependências","#1F3263"],["Painel único","indicadores e decisões numa só tela","#33556D"]];
M.forEach(([t,d,c],i)=>{const x=H("div",{"data-a":"up",style:`--d:${8+i*.5};background:#fff;border:1px solid var(--line);border-left:4px solid ${c};border-radius:8px;padding:8px 10px`},$("methods"));H("div",{style:"font:800 14px var(--fh);color:#002B49"},x,t);H("div",{class:"small",style:"font-size:10.5px"},x,d)});
[["target","Uma fonte da verdade","Plano, RAID e painel únicos para todos."],["fork","Decisão no fórum certo","Alçadas claras; nada decidido no corredor."],["people","Produto e adoção juntos","Onda só avança com as pessoas prontas."],["refresh","Leve e transferível","Ferramentas do ONS; TMO repassado no mês 6."]].forEach(([ic,t,d],i)=>{const x=H("div",{"data-a":"up",style:`--d:${10+i*.4};display:grid;grid-template-columns:38px 1fr;gap:10px;align-items:center;background:#EEF3F8;border-radius:10px;padding:9px 12px`},$("princ0"));H("span",{style:`width:38px;height:38px;border-radius:50%;background:${i%2?"#F78C16":"#122143"};display:grid;place-items:center`,html:icon(ic,"#fff",19)},x);const y=H("div",null,x);H("div",{style:"font:800 15px/1.1 var(--fh);color:#002B49"},y,t);H("div",{class:"small",style:"font-size:11px"},y,d)})})();

/* ---------- ESCALA ---------- */
(function(){[["box","Container","código e contrato de entrada e saída"],["grid","Catálogo de jobs","caixinhas geradas pela documentação"],["flow","Pipeline","arrastar, conectar e orquestrar"],["sliders","Estudo","interface de parâmetros por estudo"],["cloud","Execução","nuvem com custo previsto"],["out","Resultado","catálogo, download e Axon Drive"]].forEach(([ic,t,s2],i)=>{const b=H("div",{class:"pp-step","data-a":"up",style:`--d:${3+i*.5};cursor:default;padding:10px 12px;display:grid;grid-template-columns:42px 1fr;gap:10px;align-items:center`},$("pipe"));b.innerHTML=`<span class="n" style="font-size:18px">0${i+1}</span><div class="ic" style="margin:0">${icon(ic,"#fff",22)}</div><div><b>${t}</b><span style="margin-top:2px">${s2}</span></div>`});
const s=$("scale");const df=S("defs",null,s),lg=S("linearGradient",{id:"cone",x1:0,y1:0,x2:1,y2:0},df);S("stop",{offset:0,"stop-color":"#5E8AB4","stop-opacity":.25},lg);S("stop",{offset:1,"stop-color":"#F78C16","stop-opacity":.22},lg);
path("M120 120 L470 20 L470 270 L120 180 Z",{fill:"url(#cone)"},s);
const mv=S("g",{"data-a":"zoom",style:"--d:9;transform-box:fill-box;transform-origin:center"},s);S("circle",{cx:80,cy:150,r:58,fill:"#122143"},mv);[[62,138],[98,138]].forEach(([x,y])=>{S("circle",{cx:x,cy:y,r:15,fill:"#5E8AB4"},mv)});T(mv,80,178,"2 times",{"text-anchor":"middle",fill:"#fff",style:"font:800 15px var(--fh)"});tip(mv,"Hoje · MVP","2 times usando · produto com time enxuto · melhorias pela esteira assistida");
T(s,80,232,"HOJE · MVP",{"text-anchor":"middle",fill:"#002B49",style:"font:800 12px var(--fb);letter-spacing:.1em"});T(s,80,250,"time de produto enxuto",{"text-anchor":"middle",fill:"#6B7B8C",style:"font:600 11px var(--fb)"});
["PE","PR","PL","OS","PD"].forEach((g,i)=>{const y=34+i*55,c=S("g",{"data-a":"pop",style:`--d:${11+i*.4};transform-box:fill-box;transform-origin:center`},s);S("circle",{cx:530,cy:y,r:24,fill:i%2?"#5E8AB4":"#002B49"},c);T(c,530,y+6,g,{"text-anchor":"middle",fill:"#fff",style:"font:800 15px var(--fh)"});for(let k=0;k<8;k++){S("circle",{cx:566+(k%4)*9,cy:y-6+Math.floor(k/4)*12,r:3.2,fill:"#F78C16",opacity:.85},c)}tip(c,`Gerência ${g}`,"rotinas, legados e pessoas a preparar")});
const ar=S("g",{"data-a":"fade",style:"--d:10"},s);mk(s,"scA","#F78C16");path("M150 150 C230 150 300 150 440 150",{stroke:"#F78C16","stroke-width":3,fill:"none","marker-end":"url(#scA)",class:"dr",pathLength:1,style:"--d:9"},ar);S("rect",{x:240,y:122,width:110,height:24,rx:12,fill:"#F78C16"},ar);T(ar,295,139,"6 meses",{"text-anchor":"middle",fill:"#0E1C39",style:"font:800 13px var(--fb)"});
T(s,295,180,"~150 usuários potenciais",{"text-anchor":"middle",fill:"#002B49",style:"font:800 13px var(--fb)"});T(s,295,198,"legados em desnutrição gradual",{"text-anchor":"middle",fill:"#6B7B8C",style:"font:600 11.5px var(--fb)"});
const P=[["bug","Demanda de melhorias explode","Cada onda traz pedidos novos e um time enxuto não dá conta sozinho.","Porta única de entrada e régua de prioridade"],["layers","Legados para desligar com segurança","Paridade, convivência e calendário precisam estar no mesmo plano.","Portões por legado no plano integrado"],["people","Pessoas e rotinas mudando","Medo de perder o trabalho, capacitação e papéis novos.","Pilar de mudança e adoção com ADKAR"],["coin","Orçamento e valor sob escrutínio","Nuvem, licenças e retorno precisam de prova, não de intuição.","Linha de base e benefícios medidos"]];
P.forEach(([ic,t,d,r],i)=>{const x=H("div",{class:"card tlt","data-a":"up",style:`--d:${9+i*.4};border-radius:12px;padding:12px 14px;display:flex;flex-direction:column;gap:6px`},$("press"));x.innerHTML=`<div style="display:flex;align-items:center;gap:10px"><span style="width:38px;height:38px;border-radius:50%;background:${i%2?"#F78C16":"#122143"};display:grid;place-items:center;flex:none">${icon(ic,"#fff",19)}</span><h4 style="margin:0;font:800 16px/1.1 var(--fh)">${t}</h4></div><p style="font-size:12px;line-height:1.4">${d}</p><div style="margin-top:auto;background:#FEF1E2;border-radius:8px;padding:7px 10px;border-left:4px solid #F78C16"><div style="font:800 9.5px var(--fb);letter-spacing:.12em;color:#B35F00;text-transform:uppercase">Resposta do TMO</div><div style="font:700 12.5px/1.35 var(--fb);color:#002B49">${r}</div></div>`})})();

/* ---------- MATURIDADE ---------- */
(function(){const LV=["Inicial","Organizado","Integrado","Otimizado"],LD=["depende de pessoas","práticas isoladas","padrão, rituais e dados","melhoria contínua"];
const D=[["Governança e decisão",1,3,"Decisões caso a caso, sem fórum nem registro.","Comitês com alçada, controle de mudanças e log de decisões.",["Estrutura de comitês","Mapa de alçadas","Log de decisões"],0],
["Planejamento integrado",1,3,"Roadmap concentrado no dono do produto; ondas e legados sem plano comum.","Plano único de produto, ondas, legados e pessoas, com dependências.",["Cronograma integrado","Plano de ondas","Mapa de dependências"],1],
["Demandas e backlog",2,3,"Esteira de bugs já automatizada; melhorias sem priorização formal.","Porta única de entrada, régua de prioridade e releases comunicados.",["Processo de intake","Régua de prioridade","Calendário de releases"],2],
["Capacidade do produto",1,3,"Conhecimento e entregas concentrados em poucas pessoas.","Time mínimo dedicado e conhecimento distribuído e documentado.",["Time mínimo","Documentação viva","Plano de sucessão"],2],
["Adoção e mudança",1,3,"Dois times usando por iniciativa própria; sem plano de adoção.","Adoção por ondas, com prontidão das pessoas no go/no-go.",["Mapa de impactos","Trilhas e multiplicadores","Indicadores de adoção"],3],
["Medição de valor",1,3,"Ganhos conhecidos por casos isolados, como o teste de 176 mil casos.","Linha de base por rotina e benefícios medidos em cada onda.",["Árvore de benefícios","Linha de base","Relatório de valor"],4]];
const m=$("mat"),hd=H("div",{style:"display:grid;grid-template-columns:230px repeat(4,1fr);gap:6px;margin-bottom:6px"},m);H("div",{class:"small",style:"font-weight:800;letter-spacing:.1em;text-transform:uppercase;align-self:end"},hd,"Dimensão");LV.forEach((l,k)=>{const x=H("div",{style:"text-align:center"},hd);H("div",{style:`font:800 15px var(--fh);color:${["#98A6B3","#5E8AB4","#33556D","#002B49"][k]}`},x,`${k+1} · ${l}`);H("div",{class:"small",style:"font-size:10.5px"},x,LD[k])});
const rows=D.map(([n,h,g],i)=>{const r=H("div",{class:"clk","data-a":"up",style:`--d:${4+i*.4};display:grid;grid-template-columns:230px 1fr;gap:6px;align-items:center;margin-top:7px;border-radius:10px;padding:2px`},m);H("div",{style:"font:800 16px/1.15 var(--fh);color:#002B49;padding-left:6px"},r,n);const tr=H("div",{style:"position:relative;display:grid;grid-template-columns:repeat(4,1fr);gap:6px;height:66px"},r);for(let k=0;k<4;k++)H("div",{style:`border-radius:8px;background:${["#F2F5F8","#EAF0F6","#E1E9F2","#D8E3EE"][k]}`},tr);
const pos=v=>`calc(${(v-.5)*25}% - 18px)`;const ghost=H("div",{style:`position:absolute;top:15px;left:${pos(h)};width:36px;height:36px;border-radius:50%;border:2.5px dashed #98A6B3;opacity:0;transition:opacity .4s`},tr);
const mkr=H("div",{style:`position:absolute;top:15px;left:${pos(h)};width:36px;height:36px;border-radius:50%;background:#002B49;color:#fff;display:grid;place-items:center;font:800 13px var(--fb);box-shadow:0 4px 12px rgba(14,28,57,.3);transition:left .8s cubic-bezier(.2,.7,.2,1),background .4s`},tr,String(h));tip(r,n,`hoje (hipótese) ${h} · meta 6 meses ${g}`);r.addEventListener("click",()=>sel(i));return{r,mkr,ghost,h,g,pos}});
let st=0;function set(v){st=v;$("matSeg").querySelectorAll("button").forEach(b=>b.classList.toggle("on",+b.dataset.v===v));rows.forEach(o=>{o.mkr.style.left=o.pos(v?o.g:o.h);o.mkr.textContent=v?o.g:o.h;o.mkr.style.background=v?"#F78C16":"#002B49";o.ghost.style.opacity=v?1:0})}
$("matSeg").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{clearTimeout(au);set(+b.dataset.v)}));
function sel(i){rows.forEach((o,k)=>o.r.style.background=k===i?"#FEF6EC":"");const[n,h,g,hj,mt,how,p]=D[i];
$("matDet").innerHTML=`<div class="eye" style="color:#B35F00">Dimensão ${i+1} de 6</div><div style="font:800 26px/1.05 var(--fh);color:#002B49">${n}</div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px"><div style="background:#F2F5F8;border-radius:8px;padding:9px 12px"><div style="font:800 10px var(--fb);letter-spacing:.12em;color:#6B7B8C;text-transform:uppercase">Hoje · nível ${h}</div><div style="font:500 12.5px/1.4 var(--fb);color:#35516A;margin-top:3px">${hj}</div></div><div style="background:#FEF1E2;border-radius:8px;padding:9px 12px"><div style="font:800 10px var(--fb);letter-spacing:.12em;color:#B35F00;text-transform:uppercase">Meta · nível ${g}</div><div style="font:700 12.5px/1.4 var(--fb);color:#002B49;margin-top:3px">${mt}</div></div></div>
<div style="margin-top:12px;font:800 10.5px var(--fb);letter-spacing:.12em;color:#5E8AB4;text-transform:uppercase">Como o TMO chega lá</div><ul style="padding-left:18px;margin-top:4px">${how.map(x=>`<li style="font:600 13px/1.5 var(--fb);color:#002B49">${x}</li>`).join("")}</ul>
<div style="display:flex;align-items:center;gap:8px;margin-top:12px;border-top:1px solid var(--line2);padding-top:10px"><span class="small" style="font-weight:700">Pilar responsável:</span><span class="pill" style="background:${PIL[p][1]};color:#fff">${PIL[p][2]}</span></div>`}
sel(0);let au=0;ENTER["Ponto de partida"]=()=>{set(0);sel(0);clearTimeout(au);au=setTimeout(()=>set(1),2400)}})();

/* ---------- MODELO TMO ---------- */
(function(){const els=PIL.map(([ic,c,t,d,e,r,k],i)=>{const b=H("button",{class:"pil","data-a":"up",style:`--d:${3+i*.5};--c:${c};min-height:330px`},$("pillars"));b.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between"><span class="pn">0${i+1}</span><span style="width:40px;height:40px;border-radius:50%;background:${c};display:grid;place-items:center">${icon(ic,"#fff",20)}</span></div><b>${t}</b><span>${d}</span><div style="margin-top:auto;border-top:1px solid var(--line2);padding-top:8px"><div style="font:800 9.5px var(--fb);letter-spacing:.12em;color:#6B7B8C;text-transform:uppercase">Ritual</div><div style="font:700 12px/1.3 var(--fb);color:#002B49">${r}</div></div>`;b.addEventListener("click",()=>sel(i));return b});
[["chart","Painel único"],["calendar","Rituais e cadência"],["book","PMI · ágil · ADKAR"],["grid","Ferramentas do ONS"]].forEach(([ic,t],i)=>H("div",{style:`display:flex;align-items:center;justify-content:center;gap:8px;padding:12px 8px;color:#fff;font:800 14px var(--fh);letter-spacing:.04em;${i?"border-left:1px solid rgba(255,255,255,.15)":""}`,html:icon(ic,"#F9A64A",18)+t},$("found")));
function sel(i){els.forEach((b,k)=>b.classList.toggle("sel",k===i));const[ic,c,t,d,e,r,k]=PIL[i];
$("pilDet").innerHTML=`<div style="display:flex;align-items:center;gap:12px"><span style="width:50px;height:50px;border-radius:50%;background:${c};display:grid;place-items:center">${icon(ic,"#fff",26)}</span><div><div class="eye" style="margin:0;color:#B35F00">Pilar ${i+1} de 5</div><div style="font:800 25px/1.05 var(--fh);color:#002B49">${t}</div></div></div>
<p style="font-size:13.5px;line-height:1.5;margin-top:12px;color:#35516A">${d}</p>
<div style="margin-top:12px;font:800 10.5px var(--fb);letter-spacing:.12em;color:#5E8AB4;text-transform:uppercase">Entregáveis</div><ul style="padding-left:18px;margin-top:4px">${e.map(x=>`<li style="font:600 13px/1.5 var(--fb);color:#002B49">${x}</li>`).join("")}</ul>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px"><div style="background:#EEF3F8;border-radius:8px;padding:9px 12px"><div style="font:800 10px var(--fb);letter-spacing:.12em;color:#33556D;text-transform:uppercase">Ritual</div><div style="font:700 13px/1.35 var(--fb);color:#002B49;margin-top:3px">${r}</div></div><div style="background:#FEF1E2;border-radius:8px;padding:9px 12px"><div style="font:800 10px var(--fb);letter-spacing:.12em;color:#B35F00;text-transform:uppercase">Indicador-chave</div><div style="font:700 13px/1.35 var(--fb);color:#002B49;margin-top:3px">${k}</div></div></div>`}
sel(0);ENTER["O modelo TMO"]=()=>sel(0)})();

/* ---------- GOVERNANÇA ---------- */
(function(){const s=$("pyr"),cx=200,L=[["Comitê executivo","mensal","Patrocinador e líderes das gerências","Prioridades, orçamento, go/no-go das ondas e desligamento de legados","#002B49"],["Produto e arquitetura | Adoção","quinzenal","Produto, TI e segurança | gerências, RH e multiplicadores","Roadmap, padrões e releases | prontidão, impactos e transição","#33556D"],["Status do TMO","semanal","TMO, produto e líderes de onda","Plano, RAID, dependências e escalonamentos","#5E8AB4"],["Ciclos do produto e das ondas","diário","Time do produto e multiplicadores","Execução, suporte e correções","#8FAAC8"]];
const top=20,h=112,gap=10,wTop=110,wBot=400;mk(s,"pyA","#F78C16");
L.forEach(([n,f,w,d,c],i)=>{const y=top+i*(h+gap),w0=wTop+(wBot-wTop)*(i/L.length),w1=wTop+(wBot-wTop)*((i+1)/L.length),g=S("g",{"data-a":"up",style:`--d:${3+i*.6}`},s);
path(`M${cx-w0/2} ${y} L${cx+w0/2} ${y} L${cx+w1/2} ${y+h} L${cx-w1/2} ${y+h} Z`,{fill:c},g);
if(i===1){S("line",{x1:cx,y1:y+6,x2:cx,y2:y+h-6,stroke:"rgba(255,255,255,.5)","stroke-dasharray":"3 3"},g);T(g,cx-42,y+44,"Produto e",{"text-anchor":"middle",fill:"#fff",style:"font:800 14px var(--fh)"});T(g,cx-42,y+60,"arquitetura",{"text-anchor":"middle",fill:"#fff",style:"font:800 14px var(--fh)"});T(g,cx+42,y+52,"Adoção",{"text-anchor":"middle",fill:"#fff",style:"font:800 14px var(--fh)"});T(g,cx,y+84,f,{"text-anchor":"middle",fill:"#F9A64A",style:"font:700 11px var(--fb)"})}
else{const words=n.split(" ");const mid=Math.ceil(words.length/2);if(i===0){T(g,cx,y+58,"Comitê",{"text-anchor":"middle",fill:"#fff",style:"font:800 14px var(--fh)"});T(g,cx,y+74,"executivo",{"text-anchor":"middle",fill:"#fff",style:"font:800 14px var(--fh)"});T(g,cx,y+89,f,{"text-anchor":"middle",fill:"#F9A64A",style:"font:700 11px var(--fb)"})}else{T(g,cx,y+h/2,n,{"text-anchor":"middle",fill:i===3?"#002B49":"#fff",style:"font:800 17px var(--fh)"});T(g,cx,y+h/2+18,f,{"text-anchor":"middle",fill:i===3?"#002B49":"#F9A64A",style:"font:700 12px var(--fb)"})}}
const ax=cx+w1/2+18;S("line",{x1:cx+(w0+w1)/4+6,y1:y+h/2,x2:ax+6,y2:y+h/2,stroke:"#B6C0CD","stroke-dasharray":"3 4"},g);
fo(g,ax+10,y+4,250,h-6,`<div style="font:800 10px var(--fb);letter-spacing:.1em;color:${c==="#8FAAC8"?"#5E8AB4":c};text-transform:uppercase">${w}</div><div style="font:600 12.5px/1.38 var(--fb);color:#002B49;margin-top:3px">${d}</div>`);tip(g,`${n} · ${f}`,d)});
const ya=top,yb=top+4*(h+gap)-gap;path(`M18 ${yb-10} L18 ${ya+10}`,{stroke:"#F78C16","stroke-width":3,fill:"none","marker-end":"url(#pyA)"},s);T(s,10,(ya+yb)/2,"ESCALONAMENTO",{"text-anchor":"middle",fill:"#B35F00",transform:`rotate(-90 10 ${(ya+yb)/2})`,style:"font:800 10.5px var(--fb);letter-spacing:.14em"});
[["Ajuste dentro da onda","TMO + dono do produto","#5E8AB4"],["Prazo de onda ou prioridade do backlog","comitê de produto ou de adoção","#F78C16"],["Escopo, orçamento ou desligar legado","comitê executivo","#002B49"]].forEach(([a,b,c],i)=>{const x=H("div",{"data-a":"left",style:`--d:${11+i*.3};display:grid;grid-template-columns:1fr 20px 1fr;gap:6px;align-items:center;font:600 12.5px/1.3 var(--fb);color:#002B49;background:#F4F7FA;border-radius:8px;padding:7px 10px;border-left:4px solid ${c}`},$("alc"));H("span",null,x,a);H("span",{style:"color:#F78C16;font-weight:800"},x,"→");H("b",{style:`color:${c==="#5E8AB4"?"#33556D":c}`},x,b)});
const c=$("cad"),R=[["Ciclo diário do produto","#8FAAC8",[1,1,1,1],1],["Status do TMO + RAID","#5E8AB4",[1,1,1,1]],["Comitê de produto e arquitetura","#33556D",[1,0,1,0]],["Comitê de adoção","#F78C16",[0,1,0,1]],["Revisão de valor","#1F3263",[0,0,1,0]],["Comitê executivo","#002B49",[0,0,0,1]]];
const x0=230,cw=(710-x0)/4;for(let k=0;k<4;k++){S("rect",{x:x0+k*cw+2,y:0,width:cw-4,height:22,rx:4,fill:k%2?"#EEF3F8":"#E4EBF2"},c);T(c,x0+k*cw+cw/2,15,"Semana "+(k+1),{"text-anchor":"middle",fill:"#35516A",style:"font:800 11px var(--fb)"})}
R.forEach(([n,col,w,cont],i)=>{const y=34+i*36;T(c,0,y+15,n,{fill:"#002B49",style:"font:700 12.5px var(--fb)"});S("line",{x1:x0,y1:y+11,x2:710,y2:y+11,stroke:"#EEF2F5"},c);
if(cont){const r=S("rect",{x:x0+6,y:y+5,width:4*cw-12,height:12,rx:6,fill:col,opacity:.75,"data-a":"grow",style:`--d:${5+i*.4};transform-box:fill-box`},c);tip(r,n,"todos os dias, 15 minutos")}else w.forEach((v,k)=>{if(!v)return;const g=S("g",{"data-a":"pop",style:`--d:${5+i*.4+k*.2};transform-box:fill-box;transform-origin:center`},c);S("circle",{cx:x0+k*cw+cw/2,cy:y+11,r:10,fill:col,stroke:"#fff","stroke-width":2.5},g);tip(g,n,"semana "+(k+1))})})})();

/* ---------- PAPÉIS ---------- */
(function(){rasciTable($("rasci"),$("rasLeg"),["Patrocinador executivo","Dono do produto AXON","TI · arquitetura e segurança","Gerências PE–PD","RH · Pessoas","Multiplicadores","TMO · A&M"],
[["Priorizar o portfólio de ondas","ACCCIIR"],["Priorizar o backlog do produto","IACCICS"],["Aprovar uma release","IARIIIS"],["Go/no-go de cada onda","ACCRCCS"],["Desligar um legado","IRRAICS"],["Mudar escopo, prazo ou orçamento","ACCCIIR"],["Plano de transição das pessoas","CIIARIS"],["Linha de base e benefícios","ACICIIR"]]);
[["flag","Liderança do TMO","governança, comitês e patrocínio","#002B49"],["calendar","Especialista de PMO","plano integrado, RAID e ondas","#33556D"],["people","Especialista de mudança","adoção, comunicação e transição","#F78C16"],["chart","Analista de valor e dados","linha de base, painel e benefícios","#5E8AB4"]].forEach(([ic,t,d,c],i)=>{const x=H("div",{class:"card tlt","data-a":"up",style:`--d:${5+i*.4};border-radius:12px;padding:12px 14px;border-top:4px solid ${c}`},$("team"));x.innerHTML=`<span style="width:40px;height:40px;border-radius:50%;background:${c};display:grid;place-items:center">${icon(ic,"#fff",20)}</span><div style="font:800 16px/1.1 var(--fh);color:#002B49;margin-top:8px">${t}</div><div class="small" style="font-size:11.5px;margin-top:2px">${d}</div>`});
["Patrocinador executivo","Dono do produto AXON","Líder de onda por gerência","TI · arquitetura e segurança","RH · Pessoas","Multiplicadores","Guardiões dos legados"].forEach((r,i)=>H("span",{class:"pill","data-a":"pop",style:`--d:${9+i*.3};font-size:12.5px;padding:8px 12px;background:${i===6?"#FEF1E2":"#DFE8F0"};color:${i===6?"#8A4A05":"#002B49"}`},$("onsRoles"),r));
const x=H("div",{class:"card nv","data-a":"up",style:"--d:12;border-radius:12px;padding:12px 16px;margin-top:4px"},$("onsRoles").parentNode);x.innerHTML=`<div class="eye" style="color:#F9A64A">Regra de ouro</div><div style="font:800 18px/1.2 var(--fh);color:#fff">Um único A por decisão. O TMO prepara, o ONS decide.</div>`})();

/* ---------- PORTFÓLIO DE ONDAS ---------- */
(function(){const s=$("wave"),x0=70,x1=960,y0=420,y1=20,X=v=>x0+v/100*(x1-x0),Y=v=>y0-v/100*(y0-y1);
[[50,100,50,100,"#FEF1E2","Piloto e onda 1","alto valor · alta prontidão"],[0,50,50,100,"#EEF3F8","Onda 2 · preparar antes","alto valor · prontidão a construir"],[50,100,0,50,"#F2F5F8","Ganhos rápidos","encaixar nas ondas"],[0,50,0,50,"#F7F8FA","Backlog","reavaliar no próximo ciclo"]].forEach(([a,b,c,d,f,t,st],i)=>{S("rect",{x:X(a)+2,y:Y(d)+2,width:X(b)-X(a)-4,height:Y(c)-Y(d)-4,rx:8,fill:f},s);const tx=a?X(b)-12:X(a)+12,an=a?"end":"start";T(s,tx,Y(d)+24,t,{"text-anchor":an,fill:i===0?"#B35F00":"#35516A",style:"font:800 14px var(--fh);letter-spacing:.04em;text-transform:uppercase"});T(s,tx,Y(d)+40,st,{"text-anchor":an,fill:"#6B7B8C",style:"font:600 11px var(--fb)"})});
T(s,(x0+x1)/2,y0+36,"PRONTIDÃO  (técnica + pessoas) →",{"text-anchor":"middle",fill:"#35516A",style:"font:800 11px var(--fb);letter-spacing:.12em"});T(s,24,(y0+y1)/2,"VALOR →",{"text-anchor":"middle",fill:"#35516A",transform:`rotate(-90 24 ${(y0+y1)/2})`,style:"font:800 11px var(--fb);letter-spacing:.12em"});
S("line",{x1:x0,y1:y0,x2:x1,y2:y0,stroke:"#B6C0CD"},s);S("line",{x1:x0,y1:y0,x2:x0,y2:y1,stroke:"#B6C0CD"},s);
const C=[["Rotinas de hidrologia",88,66,20,"já no MVP · piloto natural","#F78C16"],["Backtests e casos em massa",74,90,26,"ganho de tempo já demonstrado","#F78C16"],["Previsão de carga",62,76,30,"alto uso recorrente","#F78C16"],["Validação de previsões de agentes",40,84,28,"Caixa de entrada · muda o canal externo","#002B49"],["Integração com o Organon",20,72,24,"depende de integração técnica","#002B49"],["Estudos de planejamento",32,58,32,"muitos usuários · prontidão a construir","#002B49"],["Relatórios recorrentes",80,34,18,"rápido, mas pouco valor","#5E8AB4"],["Rotinas pouco frequentes",24,24,14,"reavaliar depois","#98A6B3"]];
C.forEach(([n,px,v,r,d,c],i)=>{const g=S("g",{"data-a":"pop",style:`--d:${4+i*.4};transform-box:fill-box;transform-origin:center`},s);S("circle",{cx:X(px),cy:Y(v),r,fill:c,opacity:.88,stroke:"#fff","stroke-width":2.5},g);const left=px>70;T(g,X(px)+(left?-(r+8):r+8),Y(v)+4,n,{"text-anchor":left?"end":"start",fill:"#002B49",style:"font:700 12.5px var(--fb)"});tip(g,n,`valor ${v} · prontidão ${px} · ${d}`)});
[["Valor","40%","horas, frequência e criticidade da rotina","#F78C16"],["Prontidão técnica","30%","container documentado e paridade","#002B49"],["Prontidão das pessoas","20%","patrocínio, multiplicador e trilha","#5E8AB4"],["Dependência de legados","10%","quanto do legado sai com a onda","#33556D"]].forEach(([n,w,d,c],i)=>{const x=H("div",{"data-a":"up",style:`--d:${6+i*.3};display:grid;grid-template-columns:1fr 46px;gap:8px;align-items:center`},$("crit"));const y=H("div",null,x);H("div",{style:"font:800 14px var(--fh);color:#002B49"},y,n);H("div",{class:"small",style:"font-size:11px"},y,d);const bb=H("div",{style:"height:6px;border-radius:99px;background:#EEF2F5;margin-top:4px;overflow:hidden"},y);H("div",{style:`height:100%;width:${parseInt(w)*2.2}%;background:${c};border-radius:99px`},bb);H("div",{style:`font:800 22px var(--fh);color:${c};text-align:right`},x,w)});
[["Piloto","mês 3","rotinas já no MVP + um caso de alto valor, com rodada paralela","#F78C16"],["Onda 1","mês 4","alto valor e alta prontidão, por gerência","#1F3263"],["Onda 2","mês 5","alto valor que precisou de preparo técnico e das pessoas","#33556D"]].forEach(([n,m,d,c],i)=>{const x=H("div",{"data-a":"left",style:`--d:${9+i*.4};display:grid;grid-template-columns:88px 1fr;gap:10px;align-items:center;background:#fff;border:1px solid var(--line);border-left:6px solid ${c};border-radius:10px;padding:9px 12px`},$("waveList"));const y=H("div",null,x);H("div",{style:`font:800 19px/1 var(--fh);color:${c}`},y,n);H("div",{class:"small",style:"font-weight:700"},y,m);H("div",{style:"font:500 12.5px/1.4 var(--fb);color:#35516A"},x,d)})})();

/* ---------- DEMANDAS E BACKLOG ---------- */
(function(){const ST=[["chat","Entrada","#5E8AB4",["Reportar bug no AXON, com contexto automático","Fórum de usuários e multiplicadores","Inquietações da mudança"]],["search","Triagem","#33556D",["Bug simples → esteira de correção assistida por IA, com aprovação humana","Demanda → classificada por tipo e onda"]],["target","Priorização","#F78C16",["Régua única: valor × esforço × onda","Decisão no comitê de produto"]],["refresh","Entrega","#1F3263",["Ciclos quinzenais","Release com nota e treinamento rápido"]],["megaphone","Retorno","#002B49",["“Você pediu, fizemos”","Resposta a quem pediu","Tempo do pedido à entrega medido"]]];
const el=$("intake");ST.forEach(([ic,t,c,li],i)=>{if(i)H("div",{class:"arrowR","data-a":"fade",style:`--d:${3+i*.6}`},el,"›");const x=H("div",{class:"tlt","data-a":"up",style:`--d:${3+i*.6};background:#fff;border:1px solid var(--line);border-top:5px solid ${c};border-radius:12px;padding:14px 16px;min-height:236px`},el);x.innerHTML=`<div style="display:flex;align-items:center;gap:10px"><span style="width:42px;height:42px;border-radius:50%;background:${c};display:grid;place-items:center">${icon(ic,"#fff",21)}</span><div><div style="font:800 10.5px var(--fb);letter-spacing:.12em;color:#6B7B8C">ETAPA ${i+1}</div><div style="font:800 20px/1 var(--fh);color:#002B49">${t}</div></div></div><ul style="padding-left:16px;margin-top:10px">${li.map(z=>`<li style="font:500 12.5px/1.42 var(--fb);color:#35516A;margin-top:4px">${z}</li>`).join("")}</ul>`});
[["Bloqueia uma onda ou rotina crítica","#BC0404"],["Segurança, dados ou paridade com o legado","#F78C16"],["Muitas pessoas afetadas ou grande ganho de tempo","#5E8AB4"],["Melhoria de experiência pedida pelos usuários","#33556D"],["Ideia nova → fila de descoberta","#98A6B3"]].forEach(([t,c],i)=>{const x=H("div",{"data-a":"left",style:`--d:${11+i*.3};display:grid;grid-template-columns:28px 1fr;gap:8px;align-items:center`},$("rule"));H("span",{style:`display:grid;place-items:center;width:26px;height:26px;border-radius:50%;background:${c};color:#fff;font:800 12px var(--fb)`},x,String(i+1));H("span",{style:"font:600 12.5px/1.3 var(--fb);color:#002B49"},x,t)});
const s=$("alloc"),cx=88,cy=95,r=70,P=[["Ondas e adoção",60,"#F78C16"],["Melhorias pedidas pelos usuários",25,"#5E8AB4"],["Dívida técnica e segurança",15,"#002B49"]];let a0=-Math.PI/2;
P.forEach(([n,v,c],i)=>{const a1=a0+v/100*2*Math.PI,lg=v>50?1:0,p=`M${cx+r*Math.cos(a0)} ${cy+r*Math.sin(a0)} A${r} ${r} 0 ${lg} 1 ${cx+r*Math.cos(a1)} ${cy+r*Math.sin(a1)}`;const g=path(p,{fill:"none",stroke:c,"stroke-width":30,class:"dr",pathLength:1,style:`--d:${12+i}`},s);tip(g,n,v+"% da capacidade de cada ciclo");a0=a1;
const y=48+i*44;S("rect",{x:190,y:y-12,width:14,height:14,rx:3,fill:c},s);T(s,212,y,v+"%",{fill:c,style:"font:800 20px var(--fh)"});T(s,212,y+16,n,{fill:"#35516A",style:"font:600 11.5px var(--fb)"})});
T(s,cx,cy+6,"ciclo",{"text-anchor":"middle",fill:"#002B49",style:"font:800 15px var(--fh)"})})();

/* ---------- PLANO INTEGRADO ---------- */
(function(){const s=$("gantt");const R=[["Governança e PMO","#002B49",[[0,1,"Mobilização"],[1,6,"Status semanal, RAID e comitês",1]]],
["Produto e backlog","#5E8AB4",[[0,1.5,"Intake e régua"],[1.5,6,"Releases quinzenais",1]]],
["Containers e catálogo","#33556D",[[.5,2,"Padrão + containers piloto"],[2,3.5,"Containers onda 1"],[3.5,5,"Containers onda 2"]]],
["Ondas de adoção","#F78C16",[[1,2,"Plano de ondas"],[2,3.5,"Piloto"],[3.5,4.5,"Onda 1"],[4.5,5.5,"Onda 2"],[5.5,6,"Sust."]]],
["Legados","#1F3263",[[1,2,"Inventário"],[2,4,"Paralela e paridade"],[4,6,"Transferir e desligar"]]],
["Mudança e pessoas","#C96A05",[[.5,2,"Impactos e narrativa"],[2,6,"Comunicação, capacitação e transição",1]]],
["Valor e benefícios","#5E8AB4",[[.5,2,"Linha de base"],[2,6,"Medição por onda e relatório de valor",1]]]];
const lab=290,rh=55,top=40;gantt(s,R,{lab,rh,top,ms:[[1,"Governança ativa"],[2,"Go do piloto"],[3.5,"Go onda 1"],[4.5,"Go onda 2"],[6,"Transferência"]]});
const MW=(1508-10-lab)/6,XM=m=>lab+m*MW,YC=i=>top+i*rh+6+(rh-18)/2;mk(s,"dpA","#F78C16");
[[2,2,2,3,"Container pronto antes do piloto"],[5,2,2,3,"Pessoas prontas antes do piloto"],[2,3.5,3.5,3,"Containers da onda 1 antes do go"],[4,4,4,4,""]].forEach(([r0,m0,m1,r1,l],k)=>{if(!l)return;const xa=XM(m0)-10,ya=YC(r0),xb=XM(m1)+10,yb=YC(r1),mx=xa-28;const p=path(`M${xa} ${ya} C${mx} ${ya} ${mx} ${yb} ${xb-14} ${yb}`,{fill:"none",stroke:"#F78C16","stroke-width":2.6,"stroke-dasharray":"5 4","marker-end":"url(#dpA)"},s);p.setAttribute("data-a","fade");p.style.setProperty("--d",12+k);tip(p,"Dependência crítica",l)});
[["Container documentado → piloto","O catálogo só gera as caixinhas certas se a documentação de entrada e saída bater com o código."],["Pessoas prontas → go da onda","Prontidão, trilha concluída e multiplicador definido entram no critério de go/no-go."],["Paridade aceita → desligar legado","Nenhuma função sai do legado sem rodada paralela e aceite do dono."]].forEach(([t,d],i)=>{const x=H("div",{"data-a":"up",style:`--d:${14+i*.4};display:flex;gap:10px;align-items:center;background:#FEF6EC;border:1px solid #F5D2A8;border-radius:10px;padding:8px 12px`},$("deps"));H("span",{style:"flex:none;width:30px;height:30px;border-radius:50%;background:#F78C16;display:grid;place-items:center",html:icon("link","#fff",16)},x);const y=H("div",null,x);H("div",{style:"font:800 14px var(--fh);color:#002B49"},y,t);H("div",{style:"font:500 11.5px/1.35 var(--fb);color:#35516A"},y,d)})})();

/* ---------- RAID ---------- */
(function(){const ST={a:["#BC0404","alto"],m:["#F78C16","médio"],b:["#5E8AB4","baixo"],v:["#33556D","validar"],o:["#5E8AB4","aberto"]};
const C=[["R","Riscos","#BC0404",[["Conhecimento do produto concentrado em poucas pessoas","Patrocinador","a","time mínimo e documentação viva"],["Demanda de melhorias acima da capacidade","Dono do produto","a","porta única e régua de prioridade"],["Medo de perder o trabalho freia a adoção","Comitê de adoção","a","caminho combinado para cada impactado"],["Resultado divergente do legado abala a confiança","Produto + gerências","m","paridade aceita antes do go"]]],
["A","Premissas","#5E8AB4",[["Patrocínio executivo ativo nos comitês","Patrocinador","v","confirmar na abertura do programa"],["Acesso às gerências, rotinas e legados","Gerências","v","agenda do raio-x pactuada no mês 1"],["Ambiente de nuvem e orçamento por time disponíveis","TI + gestores","v","validar antes do piloto"],["RH engajado na transição das pessoas","RH","v","RH no comitê de adoção"]]],
["I","Issues","#F78C16",[["Inventário de legados ainda incompleto","TMO","o","fechar no mês 1"],["Papéis entre TI e produto não formalizados","Comitê de produto","o","RASCI aprovada no mês 1"],["Sem linha de base de tempo por rotina","TMO · valor","o","medir antes do piloto"]]],
["D","Dependências","#1F3263",[["Containers documentados antes de cada onda","Construtores","m","entra no go/no-go"],["Aprovação de arquitetura e segurança","TI","m","requisitos acordados no mês 2"],["Integrações: catálogo corporativo e Organon","Produto + TI","m","no plano integrado"],["Janelas fora de entregas com prazo","Gerências","b","calendário das ondas"]]]];
C.forEach(([k,n,c,items],i)=>{const col=H("div",{class:"col","data-a":"up",style:`--d:${3+i*.5};--c:${c}`},$("raid"));col.innerHTML=`<div class="ch"><b>${k}</b><span>${n}</span><span style="margin-left:auto;font:800 11px var(--fb);color:#6B7B8C">${items.length}</span></div>`;
items.forEach(([t,o,st,ac])=>{const it=H("div",{class:"it"},col);it.innerHTML=`<b>${t}</b><span><i style="display:inline-block;width:9px;height:9px;border-radius:50%;background:${ST[st][0]}"></i>${ST[st][1]} · dono: ${o}</span><div style="font:700 11px/1.3 var(--fb);color:#B35F00;margin-top:4px">→ ${ac}</div>`;tip(it,t,`${n} · ${ST[st][1]} · dono: ${o}`)})});
chev($("raidFlow"),[["1","Identificar","","qualquer pessoa, a qualquer momento","#5E8AB4"],["2","Registrar","","com dono, data e status (TMO)","#33556D"],["3","Revisar","","no status semanal do TMO","#F78C16"],["4","Escalar","","risco alto vai ao comitê da alçada","#1F3263"],["5","Encerrar","","quando o sinal some e o dono confirma","#002B49"]])})();

/* ---------- MUDANÇA E ADOÇÃO ---------- */
(function(){const s=$("adkChain"),A=[["A","Consciência","por que o ONS muda","#002B49"],["D","Desejo","o que eu ganho","#33556D"],["K","Conhecimento","como eu faço","#5E8AB4"],["A","Habilidade","faço no dia a dia","#F78C16"],["R","Reforço","veio para ficar","#1F3263"]],W=1508,cw=W/5;mk(s,"akA","#B6C0CD");
A.forEach(([l,n,d,c],i)=>{const cx=cw*i+cw/2,g=S("g",{"data-a":"pop",style:`--d:${3+i*.5};transform-box:fill-box;transform-origin:center`},s);if(i)path(`M${cx-cw+44} 44 L${cx-48} 44`,{stroke:"#B6C0CD","stroke-width":2.5,fill:"none","marker-end":"url(#akA)"},s);S("circle",{cx,cy:44,r:38,fill:c},g);T(g,cx,60,l,{"text-anchor":"middle",fill:i===3?"#0E1C39":"#fff",style:"font:800 44px var(--fh)"});T(g,cx,104,n,{"text-anchor":"middle",fill:"#002B49",style:"font:800 17px var(--fh);letter-spacing:.04em;text-transform:uppercase"});T(g,cx,122,"“"+d+"”",{"text-anchor":"middle",fill:"#6B7B8C",style:"font:600 12px var(--fb)"})});
[["people","Stakeholders e impactos","Mapa por gerência e perfil; quem perde o quê, quem ganha o quê.","AD"],["megaphone","Comunicação e marca AXON","Narrativa do patrocinador, vitrine da plataforma e histórias de colegas.","AD"],["cap","Capacitação e manual amigável","Trilhas por perfil, ambiente de prática e multiplicadores.","KH"],["refresh","Transição das pessoas","Menos operação, mais estudo: requalificar e realocar primeiro.","DR"],["check","Prontidão no go/no-go","Critérios de pessoas no portão de cada onda e pulso 30/60/90.","HR"]].forEach(([ic,t,d,a],i)=>{const x=H("div",{class:"fr-card tlt","data-a":"up",style:`--d:${7+i*.4};--c:${["#002B49","#33556D","#5E8AB4","#F78C16","#1F3263"][i]};display:flex;flex-direction:column;gap:6px;min-height:236px`},$("essent"));x.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between"><span style="width:38px;height:38px;border-radius:50%;background:var(--c);display:grid;place-items:center">${icon(ic,"#fff",19)}</span><span style="display:flex;gap:3px">${[...a].map(adkChip).join("")}</span></div><h4 style="font:800 18px/1.15 var(--fh);margin-top:6px">${t}</h4><p style="font-size:13px;line-height:1.45">${d}</p>`});
$("pplIc").innerHTML=icon("people","#fff",28)})();

/* ---------- VALOR ---------- */
(function(){const s=$("tree");const D=[["clock","Tempo","Rodadas mais rápidas","#F78C16",[["Tempo de rodada por estudo","antes × depois, por rotina"],["Casos processados por janela","volume por hora de execução"]]],
["people","Capacidade","Horas devolvidas às equipes","#5E8AB4",[["Horas operacionais liberadas","por rotina, contra a linha de base"],["Tempo em estudo e análise","% da agenda, por pulso"]]],
["coin","Custo","Custo previsível e legados desligados","#33556D",[["Precisão do custo de nuvem","desvio entre custo previsto e realizado por rodada"],["Legados e licenças desligados","quantidade e custo evitado"]]],
["shield","Risco","Menos dependência, mais rastreabilidade","#1F3263",[["Rotinas documentadas e versionadas","% das rotinas no AXON"],["Incidentes e retrabalho por onda","ocorrências na transição"]]]];
const root=S("g",{"data-a":"left",style:"--d:3"},s);S("rect",{x:0,y:190,width:190,height:100,rx:12,fill:"#122143"},root);fo(root,14,202,164,80,`<div style="font:800 10px var(--fb);letter-spacing:.14em;color:#F9A64A">OBJETIVO</div><div style="font:800 18px/1.15 var(--fh);color:#fff;margin-top:3px">Valor do AXON comprovado para o ONS</div>`);
D.forEach(([ic,n,d,c,K],i)=>{const y=14+i*118,yc=y+46;path(`M190 240 C230 240 230 ${yc} 270 ${yc}`,{fill:"none",stroke:"#B6C0CD","stroke-width":2,class:"dr",pathLength:1,style:`--d:${4+i*.4}`},s);
const g=S("g",{"data-a":"up",style:`--d:${5+i*.5}`},s);S("rect",{x:270,y,width:290,height:92,rx:12,fill:"#fff",stroke:c,"stroke-width":2},g);S("rect",{x:270,y,width:8,height:92,rx:4,fill:c},g);fo(g,290,y+10,262,76,`<div style="display:flex;align-items:center;gap:10px"><span style="width:36px;height:36px;border-radius:50%;background:${c};display:grid;place-items:center;flex:none">${icon(ic,"#fff",18)}</span><div><div style="font:800 10px var(--fb);letter-spacing:.12em;color:${c};text-transform:uppercase">${n}</div><div style="font:800 16px/1.15 var(--fh);color:#002B49">${d}</div></div></div>`);
K.forEach(([kn,kf],j)=>{const ky=y+j*48-2,kc=ky+22;path(`M560 ${yc} C590 ${yc} 590 ${kc} 620 ${kc}`,{fill:"none",stroke:"#D6DEE6","stroke-width":1.6},s);const kg=S("g",{"data-a":"right",style:`--d:${7+i*.5+j*.2}`},s);S("rect",{x:620,y:ky+2,width:436,height:42,rx:8,fill:"#F4F7FA"},kg);S("circle",{cx:638,cy:kc+1,r:5,fill:c},kg);T(kg,652,kc-2,kn,{fill:"#002B49",style:"font:700 13px var(--fb)"});T(kg,652,kc+14,kf,{fill:"#6B7B8C",style:"font:500 11.5px var(--fb)"});tip(kg,kn,kf)})});
const e=$("evid");T(e,0,22,"Antes · estimativa",{fill:"#C8DBEB",style:"font:700 12.5px var(--fb)"});S("rect",{x:0,y:30,width:380,height:32,rx:6,fill:"rgba(255,255,255,.1)"},e);const b1=S("rect",{class:"gbar",x:0,y:30,width:0,height:32,rx:6,fill:"#5E8AB4"},e);b1.dataset.w=370;T(e,10,52,"~3 dias (~72 h)",{fill:"#fff",style:"font:800 14px var(--fb)"});
T(e,0,92,"AXON · teste relatado",{fill:"#F9A64A",style:"font:700 12.5px var(--fb)"});S("rect",{x:0,y:100,width:380,height:32,rx:6,fill:"rgba(255,255,255,.1)"},e);const b2=S("rect",{class:"gbar",x:0,y:100,width:0,height:32,rx:6,fill:"#F78C16"},e);b2.dataset.w=12;T(e,22,122,"~2 h · 176 mil casos",{fill:"#fff",style:"font:800 14px var(--fb)"});
T(e,0,172,"≈ 36× mais rápido",{fill:"#fff",style:"font:800 30px var(--fh)"});T(e,380,172,"a confirmar na linha de base",{"text-anchor":"end",fill:"#9DB7CE",style:"font:600 11px var(--fb)"})})();

/* ---------- PAINEL DO TMO ---------- */
(function(){const d=$("dash");d.innerHTML=`<div style="display:flex;align-items:center;gap:14px;background:linear-gradient(100deg,#0E1C39,#1F3263);color:#fff;padding:12px 18px"><span class="cv-prod" style="font-size:20px"><i></i>AXON</span><span style="font:800 18px var(--fh);letter-spacing:.06em;text-transform:uppercase">Status do TMO · semana 11</span><span style="margin-left:auto;font:600 12px var(--fb);color:#9DB7CE">Fase 03 · Pilotar</span><span style="display:flex;align-items:center;gap:6px;background:rgba(247,140,22,.18);border:1px solid rgba(247,140,22,.6);border-radius:99px;padding:5px 12px;font:800 11.5px var(--fb);color:#F9A64A"><i class="dot d-a" style="width:12px;height:12px"></i>No prazo, com atenção</span></div>
<div style="display:grid;grid-template-columns:1.25fr 1fr;gap:14px;padding:14px 18px"><div><div class="ttl" style="color:#002B49;font-size:13px">Frentes</div><table class="tbl" id="dashT" style="margin-top:6px;font-size:12px"></table></div>
<div style="display:flex;flex-direction:column;gap:10px"><div id="dashK" style="display:grid;grid-template-columns:repeat(2,1fr);gap:8px"></div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><div style="background:#FBEDEC;border-radius:10px;padding:8px 12px"><div style="font:800 10px var(--fb);letter-spacing:.12em;color:#BC0404;text-transform:uppercase">Top riscos</div><ul style="padding-left:16px;margin-top:4px" id="dashR"></ul></div><div style="background:#FEF1E2;border-radius:10px;padding:8px 12px"><div style="font:800 10px var(--fb);letter-spacing:.12em;color:#B35F00;text-transform:uppercase">Decisões para o comitê</div><ul style="padding-left:16px;margin-top:4px" id="dashD"></ul></div></div></div></div><div style="padding:0 18px 14px"><div class="ttl" style="color:#002B49;font-size:13px">Próximas 4 semanas</div><div id="dashN" style="display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:6px"></div></div>`;
[["sem 12","Comitê executivo","go da onda 1 condicionado"],["sem 12","Release 6","3 melhorias da onda"],["sem 13","Relatório do piloto","valor e lições"],["sem 14","Turma onda 1","PE e PR"]].forEach(([w,t,d],i)=>{const x=H("div",{style:`display:grid;grid-template-columns:54px 1fr;gap:8px;align-items:center;background:#F4F7FA;border-radius:8px;padding:8px 10px;border-top:3px solid ${["#002B49","#5E8AB4","#33556D","#F78C16"][i]}`},$("dashN"));H("span",{style:"font:800 16px var(--fh);color:#B35F00"},x,w);const y=H("div",null,x);H("div",{style:"font:800 14px var(--fh);color:#002B49"},y,t);H("div",{class:"small"},y,d)});
const t=$("dashT"),h=H("tr",null,t);["Frente","Status","Progresso","Próximo marco"].forEach(x=>H("th",null,h,x));
[["Governança e PMO","g",80,"comitê executivo · sem 12"],["Produto e backlog","g",62,"release 6 · sem 12"],["Containers e catálogo","a",48,"containers onda 1 · sem 14"],["Ondas de adoção","a",40,"lições do piloto · sem 13"],["Legados","r",25,"paridade do piloto · sem 12"],["Mudança e pessoas","g",55,"turma onda 1 · sem 14"],["Valor e benefícios","g",50,"relatório do piloto · sem 13"]].forEach(([n,s,p,m])=>{const tr=H("tr",null,t);H("td",null,tr).innerHTML=`<b>${n}</b>`;H("td",null,tr).innerHTML=`<i class="dot d-${s}" style="width:14px;height:14px"></i>`;H("td",null,tr).innerHTML=`<div style="display:flex;align-items:center;gap:6px"><div style="flex:1;height:8px;border-radius:99px;background:#EEF2F5;overflow:hidden"><div style="height:100%;width:${p}%;background:${s==="r"?"#BC0404":s==="a"?"#F78C16":"#5E8AB4"}"></div></div><span style="font:700 11px var(--fb);color:#002B49;width:30px">${p}%</span></div>`;H("td",{style:"font-size:11.5px"},tr,m)});
[["34%","utilização efetiva na onda","#F78C16"],["86%","marcos no prazo","#002B49"],["9 dias","do pedido à entrega","#5E8AB4"],["420 h","devolvidas às equipes","#33556D"]].forEach(([v,l,c])=>{const x=H("div",{style:`background:#F4F7FA;border-radius:10px;padding:14px 14px;border-left:5px solid ${c}`},$("dashK"));H("div",{style:`font:800 30px/1 var(--fh);color:${c}`},x,v);H("div",{class:"small",style:"font-weight:700"},x,l)});
["Paridade do modelo piloto fora da tolerância","Fila de melhorias acima da capacidade","Turma da onda 1 sem multiplicador em OS"].forEach(r=>H("li",{style:"font:600 12px/1.4 var(--fb);color:#002B49"},$("dashR"),r));
["Go da onda 1 condicionado à paridade","Priorizar 3 melhorias da onda","Confirmar guardião do legado em PL"].forEach(r=>H("li",{style:"font:600 12px/1.4 var(--fb);color:#002B49"},$("dashD"),r))})();

/* ---------- ROADMAP ---------- */
(function(){chev($("rmPh"),PHASES);const M=[["Mobilizar","#5E8AB4",["Governança e alçadas pactuadas","Equipe e rituais ativos","Inventário de rotinas e legados","Linha de base de valor"],"Aprovar plano e portfólio de ondas"],
["Estruturar","#5E8AB4",["Plano integrado e RAID","Intake e régua de prioridade","Padrão de container e documentação","Plano de mudança e trilhas"],"Go do piloto"],
["Pilotar","#F78C16",["Piloto com rodada paralela","Primeiros releases quinzenais","Painel do TMO no ar","Lições do piloto"],"Ajustes e go da onda 1"],
["Escalar","#1F3263",["Onda 1 em produção","Primeiras funções de legado transferidas","Capacitação por onda","Relatório de valor da onda"],"Go da onda 2"],
["Escalar","#1F3263",["Onda 2 em produção","Legados congelados","Backlog estabilizado","Transição das pessoas acompanhada"],"Legados a desligar"],
["Transferir","#33556D",["Relatório final de benefícios","TMO operado pelo ONS","Plano dos próximos ciclos","Lições aprendidas"],"Próximo ciclo e orçamento"]];
M.forEach(([ph,c,e,dc],i)=>{const x=H("div",{class:"tlt","data-a":"up",style:`--d:${5+i*.45};background:#fff;border:1px solid var(--line);border-radius:12px;overflow:hidden;display:flex;flex-direction:column;min-height:480px`},$("months"));x.innerHTML=`<div style="background:${c};color:#fff;padding:10px 14px"><div style="font:800 26px/1 var(--fh)">Mês ${i+1}</div><div style="font:700 11px var(--fb);letter-spacing:.12em;text-transform:uppercase;opacity:.9;margin-top:3px">${ph}</div></div>
<div style="padding:12px 14px;display:flex;flex-direction:column;gap:8px;flex:1"><div style="font:800 10px var(--fb);letter-spacing:.12em;color:#5E8AB4;text-transform:uppercase">Entregas</div>${e.map(z=>`<div style="display:grid;grid-template-columns:18px 1fr;gap:6px;font:600 12.5px/1.38 var(--fb);color:#002B49"><span style="margin-top:1px">${icon("check",c==="#5E8AB4"?"#5E8AB4":c,16)}</span><span>${z}</span></div>`).join("")}
<div style="margin-top:auto;background:#FEF1E2;border-radius:8px;padding:9px 11px;border-left:4px solid #F78C16"><div style="font:800 9.5px var(--fb);letter-spacing:.12em;color:#B35F00;text-transform:uppercase">Decisão do comitê</div><div style="font:800 14px/1.2 var(--fh);color:#002B49;margin-top:2px">${dc}</div></div></div>`})})();

/* ---------- CANVAS DA PROPOSTA ---------- */
(function(){const pl=PIL.map((p,i)=>`<span class="pill" style="background:${p[1]};color:#fff;margin:2px 3px 0 0;display:inline-block">${i+1} ${p[2]}</span>`).join("");
canvas($("canvas"),[["warn","Por quê","O desafio","O AXON provou valor com dois times. Escalar para cinco gerências com um time de produto enxuto exige prioridade, plano, controle de riscos e adoção sob uma só governança.",1],
["grid","O quê","5 pilares do TMO",pl],
["refresh","Como","Método","Governança em fóruns com alçada, plano integrado com dependências, porta única de demandas, ADKAR por onda e benefícios com linha de base."],
["people","Quem","Papéis","<b style='color:#002B49'>ONS:</b> patrocinador, dono do produto, líderes de onda, TI, RH, multiplicadores e guardiões dos legados. <b style='color:#002B49'>A&amp;M:</b> liderança do TMO e especialistas de PMO, mudança e valor."],
["target","Como saberemos","Sucesso","Marcos no prazo, ondas liberadas com prontidão atendida, utilização efetiva por gerência e benefícios medidos contra a linha de base."],
["check","O que entregamos","Entregáveis","Governança e alçadas · plano integrado e portfólio de ondas · porta de demandas e backlog · adoção por onda · árvore de benefícios e painel do TMO · TMO transferido ao ONS."]]);chev($("ptPh"),PHASES)})();
